version: "3.9"

services:
  metadata:
    profiles:
      - sh
    build:
      context: .
      dockerfile: build/statshouse-metadata.Dockerfile
    container_name: sh-metadata
    command: --db-path=/var/lib/statshouse/metadata/db --binlog-prefix=/var/lib/statshouse/metadata/binlog/bl --rpc-crypto-path=/etc/statshouse/key1.txt
    expose:
      - 2442
  aggregator:
    profiles:
      - sh
    image: aggregator
    build:
      context: .
      dockerfile: build/aggregator.Dockerfile
    container_name: sh-aggregator
    command: aggregator --cluster=test_shard_localhost --log-level=trace --agg-addr='0.0.0.0:13336' --kh=localhost:8123 --metadata-addr metadata:2442 --cache-dir=/var/lib/statshouse/cache/aggregator --aes-pwd-file=/etc/statshouse/key1.txt
    hostname: aggregator
    expose:
      - 8123
      - 9000
      - 13336
    depends_on:
      - metadata
  agent:
    profiles:
      - sh
    image: statshouse
    build:
      context: .
      dockerfile: build/statshouse.Dockerfile
    container_name: sh-agent
    command: agent --cluster=test_shard_localhost --log-level=trace --agg-addr='aggregator:13336,aggregator:13336,aggregator:13336' --cache-dir=/var/lib/statshouse/cache/agent --aes-pwd-file=/etc/statshouse/key1.txt
    expose:
      - 13337/udp
    ports:
      - "13337:13337/udp"
    depends_on:
      - aggregator
  api:
    profiles:
      - sh
    build:
      context: .
      dockerfile: build/statshouse-api.Dockerfile
    container_name: sh-api
    command: --verbose --local-mode --access-log --clickhouse-v1-addrs= --clickhouse-v2-addrs=aggregator:9000 --listen-addr 0.0.0.0:10888 --metadata-addr metadata:2442 --statshouse-addr=agent:13337 --disk-cache=/var/lib/statshouse/cache/api/mapping_cache.sqlite3 --rpc-crypto-path=/etc/statshouse/key1.txt
    expose:
      - 10888
    ports:
      - "10888:10888"
  kh:
    profiles:
      - kh
    build:
      context: .
      dockerfile: build/clickhouse.Dockerfile
    container_name: kh
    expose:
      - 8123
      - 9000
    ports:
      - "8123:8123"
      - "9000:9000"
