version: "3.9"

services:
  all:
    image: vkcom/statshouse-localrun-all:latest
    container_name: sh
    user: "root:root"
    ports:
      - "2442:2442"
      - "8123:8123"
      - "9000:9000"
      - "10888:10888"
      - "13336:13336"
      - "13337:13337/udp"
      - "13337:13337/tcp"
    volumes:
      - metadata:/var/lib/statshouse/metadata
      - kh:/var/lib/clickhouse

volumes:
  kh:
  metadata:
