version: "3.9"

services:
  metadata:
    profiles:
      - sh
    build:
      context: .
      dockerfile: build/statshouse-metadata.Dockerfile
    container_name: sh-metadata
    command: --statshouse-addr=agent:13337 --db-path=/var/lib/statshouse/metadata/db --binlog-prefix=/var/lib/statshouse/metadata/binlog/bl --rpc-crypto-path=/etc/statshouse/key1.txt
    expose:
      - 2442
  aggregator-kh:
    profiles:
      - sh
    build:
      context: .
      dockerfile: build/aggregator-kh.Dockerfile
    container_name: sh-aggregator-kh
    hostname: aggregator
    expose:
      - 8123
      - 9000
    healthcheck:
      test: ["CMD-SHELL", "clickhouse-client --query='SELECT 1'"]
      interval: 200ms
      timeout: 1s
      retries: 1500
  aggregator:
    profiles:
      - sh
    build:
      context: .
      dockerfile: build/statshouse.Dockerfile
    container_name: sh-aggregator
    command: aggregator --cluster=test_shard_aggregator --log-level=trace --agg-addr=':13336' --kh=aggregator-kh:8123 --metadata-addr=metadata:2442 --auto-create --cache-dir=/var/lib/statshouse/cache/aggregator --aes-pwd-file=/etc/statshouse/key1.txt
    expose:
      - 13336
    depends_on:
      aggregator-kh:
        condition: service_healthy
  agent:
    profiles:
      - sh
    build:
      context: .
      dockerfile: build/statshouse.Dockerfile
    container_name: sh-agent
    command: agent --cluster=test_shard_aggregator --log-level=trace --agg-addr='aggregator:13336,aggregator:13336,aggregator:13336' --cache-dir=/var/lib/statshouse/cache/agent --aes-pwd-file=/etc/statshouse/key1.txt
    expose:
      - 13337/udp
    ports:
      - "13337:13337/udp"
    depends_on:
      - aggregator
  api:
    profiles:
      - sh
    build:
      context: .
      dockerfile: build/statshouse-api.Dockerfile
    container_name: sh-api
    command: --verbose --local-mode --access-log --clickhouse-v1-addrs= --clickhouse-v2-addrs=aggregator-kh:9000 --listen-addr=:10888 --metadata-addr=metadata:2442 --statshouse-addr=agent:13337 --disk-cache=/var/lib/statshouse/cache/api/mapping_cache.sqlite3 --rpc-crypto-path=/etc/statshouse/key1.txt
    expose:
      - 10888
    ports:
      - "10888:10888"
    depends_on:
      aggregator-kh:
        condition: service_healthy
  kh:
    profiles:
      - kh
    build:
      context: .
      dockerfile: build/clickhouse.Dockerfile
    expose:
      - 8123
      - 9000
    ports:
      - "8123:8123"
      - "9000:9000"
