version: "3.9"

services:
  metadata:
    build:
      context: .
      dockerfile: build/statshouse-metadata.Dockerfile
      args:
        - BUILD_TRUSTED_SUBNET_GROUPS=0.0.0.0/0
    container_name: sh-metadata
    user: "root:root"
    command: --statshouse-addr=agent:13337 --db-path=/var/lib/statshouse/metadata/db --binlog-prefix=/var/lib/statshouse/metadata/binlog/bl
    volumes:
      - metadata:/var/lib/statshouse/metadata
    ports:
      - "2442:2442"
  kh:
    build:
      context: .
      dockerfile: build/clickhouse.Dockerfile
    container_name: kh
    hostname: aggregator
    environment:
      # that is fine only for local run
      - CLICKHOUSE_SKIP_USER_SETUP=1
    volumes:
      - kh:/var/lib/clickhouse
      - type: bind
        source: ./build/clickhouse-config.xml
        target: /etc/clickhouse-server/config.d/clickhouse-config.xml
    ports:
      - "8123:8123"
      - "9000:9000"
      - "9363:9363"
    healthcheck:
      test: ["CMD-SHELL", "clickhouse-client --query='SELECT 1'"]
      interval: 200ms
      timeout: 1s
      retries: 1500
  aggregator:
    build:
      context: .
      dockerfile: build/statshouse-agg.Dockerfile
      args:
        - BUILD_TRUSTED_SUBNET_GROUPS=0.0.0.0/0
        - BUILD_COMMIT
        - BUILD_COMMIT_TS
        - BUILD_MACHINE
        - BUILD_TIME
    container_name: sh-aggregator
    user: "root:root"
    command: -u=root -g=root --cluster=local_test_cluster --log-level=trace --agg-addr=':13336' --kh=kh:8123 --metadata-addr=metadata:2442 --auto-create --auto-create-default-namespace --cache-dir=/var/lib/statshouse/cache/aggregator
    ports:
      - "13336:13336"
    depends_on:
      kh:
        condition: service_healthy
  agent:
    build:
      context: .
      dockerfile: build/statshouse.Dockerfile
      args:
        - BUILD_TRUSTED_SUBNET_GROUPS=0.0.0.0/0
        - BUILD_COMMIT
        - BUILD_COMMIT_TS
        - BUILD_MACHINE
        - BUILD_TIME
    container_name: sh-agent
    user: "root:root"
    command: agent -u=root -g=root --cluster=local_test_cluster --log-level=trace --agg-addr='aggregator:13336,aggregator:13336,aggregator:13336' --cache-dir=/var/lib/statshouse/cache/agent --remote-write-enabled
    ports:
      - "13337:13337/udp"
      - "13337:13337/tcp"
      - "13380:13380"
    depends_on:
      - aggregator
  api:
    build:
      context: .
      dockerfile: build/statshouse-api.Dockerfile
      args:
        - BUILD_TRUSTED_SUBNET_GROUPS=0.0.0.0/0
        - BUILD_COMMIT
        - BUILD_COMMIT_TS
        - BUILD_MACHINE
        - BUILD_TIME
    container_name: sh-api
    user: "root:root"
    command: --verbose --insecure-mode --local-mode --access-log --clickhouse-v1-addrs= --clickhouse-v2-addrs=kh:9000 --listen-addr=:10888 --metadata-addr=metadata:2442 --statshouse-addr=agent:13337 --disk-cache=/var/lib/statshouse/cache/api/mapping_cache.sqlite3
    ports:
      - "10888:10888"
    depends_on:
      kh:
        condition: service_healthy

volumes:
  kh:
  metadata:
  prometheus:
