services:
  kh-0-0:
    build:
      context: .
      dockerfile: build/clickhouse.Dockerfile
    container_name: kh-0-0
    hostname: aggregator-0-0
    volumes:
      - kh-0-0:/var/lib/clickhouse
      - type: bind
        source: ./build/clickhouse-config.xml
        target: /etc/clickhouse-server/config.d/clickhouse-config.xml
    expose:
      - 8123
      - 9000
      - 9363
    healthcheck:
      test: ["CMD-SHELL", "clickhouse-client --query='SELECT 1'"]
      interval: 200ms
      timeout: 1s
      retries: 1500
  kh-0-1:
    build:
      context: .
      dockerfile: build/clickhouse.Dockerfile
    container_name: kh-0-1
    hostname: aggregator-0-1
    volumes:
      - kh-0-1:/var/lib/clickhouse
      - type: bind
        source: ./build/clickhouse-config.xml
        target: /etc/clickhouse-server/config.d/clickhouse-config.xml
    expose:
      - 8123
      - 9000
      - 9363
    healthcheck:
      test: ["CMD-SHELL", "clickhouse-client --query='SELECT 1'"]
      interval: 200ms
      timeout: 1s
      retries: 1500
  kh-0-2:
    build:
      context: .
      dockerfile: build/clickhouse.Dockerfile
    container_name: kh-0-2
    hostname: aggregator-0-2
    volumes:
      - kh-0-2:/var/lib/clickhouse
      - type: bind
        source: ./build/clickhouse-config.xml
        target: /etc/clickhouse-server/config.d/clickhouse-config.xml
    expose:
      - 8123
      - 9000
      - 9363
    healthcheck:
      test: ["CMD-SHELL", "clickhouse-client --query='SELECT 1'"]
      interval: 200ms
      timeout: 1s
      retries: 1500
  kh-1-0:
    build:
      context: .
      dockerfile: build/clickhouse.Dockerfile
    container_name: kh-1-0
    hostname: aggregator-1-0
    volumes:
      - kh-1-0:/var/lib/clickhouse
      - type: bind
        source: ./build/clickhouse-config.xml
        target: /etc/clickhouse-server/config.d/clickhouse-config.xml
    expose:
      - 8123
      - 9000
      - 9363
    healthcheck:
      test: ["CMD-SHELL", "clickhouse-client --query='SELECT 1'"]
      interval: 200ms
      timeout: 1s
      retries: 1500
  kh-1-1:
    build:
      context: .
      dockerfile: build/clickhouse.Dockerfile
    container_name: kh-1-1
    hostname: aggregator-1-1
    volumes:
      - kh-1-1:/var/lib/clickhouse
      - type: bind
        source: ./build/clickhouse-config.xml
        target: /etc/clickhouse-server/config.d/clickhouse-config.xml
    expose:
      - 8123
      - 9000
      - 9363
    healthcheck:
      test: ["CMD-SHELL", "clickhouse-client --query='SELECT 1'"]
      interval: 200ms
      timeout: 1s
      retries: 1500
  kh-1-2:
    build:
      context: .
      dockerfile: build/clickhouse.Dockerfile
    container_name: kh-1-2
    hostname: aggregator-1-2
    volumes:
      - kh-1-2:/var/lib/clickhouse
      - type: bind
        source: ./build/clickhouse-config.xml
        target: /etc/clickhouse-server/config.d/clickhouse-config.xml
    expose:
      - 8123
      - 9000
      - 9363
    healthcheck:
      test: ["CMD-SHELL", "clickhouse-client --query='SELECT 1'"]
      interval: 200ms
      timeout: 1s
      retries: 1500
  kh-2-0:
    build:
      context: .
      dockerfile: build/clickhouse.Dockerfile
    container_name: kh-2-0
    hostname: aggregator-2-0
    volumes:
      - kh-2-0:/var/lib/clickhouse
      - type: bind
        source: ./build/clickhouse-config.xml
        target: /etc/clickhouse-server/config.d/clickhouse-config.xml
    expose:
      - 8123
      - 9000
      - 9363
    healthcheck:
      test: ["CMD-SHELL", "clickhouse-client --query='SELECT 1'"]
      interval: 200ms
      timeout: 1s
      retries: 1500
  kh-2-1:
    build:
      context: .
      dockerfile: build/clickhouse.Dockerfile
    container_name: kh-2-1
    hostname: aggregator-2-1
    volumes:
      - kh-2-1:/var/lib/clickhouse
      - type: bind
        source: ./build/clickhouse-config.xml
        target: /etc/clickhouse-server/config.d/clickhouse-config.xml
    expose:
      - 8123
      - 9000
      - 9363
    healthcheck:
      test: ["CMD-SHELL", "clickhouse-client --query='SELECT 1'"]
      interval: 200ms
      timeout: 1s
      retries: 1500
  kh-2-2:
    build:
      context: .
      dockerfile: build/clickhouse.Dockerfile
    container_name: kh-2-2
    hostname: aggregator-2-2
    volumes:
      - kh-2-2:/var/lib/clickhouse
      - type: bind
        source: ./build/clickhouse-config.xml
        target: /etc/clickhouse-server/config.d/clickhouse-config.xml
    expose:
      - 8123
      - 9000
      - 9363
    healthcheck:
      test: ["CMD-SHELL", "clickhouse-client --query='SELECT 1'"]
      interval: 200ms
      timeout: 1s
      retries: 1500

  aggregator-0-0:
    build:
      context: .
      dockerfile: build/statshouse.Dockerfile
      args:
        - BUILD_TRUSTED_SUBNET_GROUPS=0.0.0.0/0
        - BUILD_COMMIT
        - BUILD_COMMIT_TS
        - BUILD_MACHINE
        - BUILD_TIME
    user: "root:root"
    command: aggregator -u=root -g=root --cluster=test_shard_aggregator --agg-addr=':13336' --kh=kh-0-0:8123 --metadata-addr=metadata:2442 --auto-create --auto-create-default-namespace --cache-dir=/var/lib/statshouse/cache/aggregator
    expose:
      - 13336
    depends_on:
      kh-0-0:
        condition: service_healthy
  aggregator-0-1:
    build:
      context: .
      dockerfile: build/statshouse.Dockerfile
      args:
        - BUILD_TRUSTED_SUBNET_GROUPS=0.0.0.0/0
        - BUILD_COMMIT
        - BUILD_COMMIT_TS
        - BUILD_MACHINE
        - BUILD_TIME
    user: "root:root"
    command: aggregator -u=root -g=root --cluster=test_shard_aggregator --agg-addr=':13336' --kh=kh-0-1:8123 --metadata-addr=metadata:2442 --auto-create --auto-create-default-namespace --cache-dir=/var/lib/statshouse/cache/aggregator
    expose:
      - 13336
    depends_on:
      kh-0-1:
        condition: service_healthy
  aggregator-0-2:
    build:
      context: .
      dockerfile: build/statshouse.Dockerfile
      args:
        - BUILD_TRUSTED_SUBNET_GROUPS=0.0.0.0/0
        - BUILD_COMMIT
        - BUILD_COMMIT_TS
        - BUILD_MACHINE
        - BUILD_TIME
    user: "root:root"
    command: aggregator -u=root -g=root --cluster=test_shard_aggregator --agg-addr=':13336' --kh=kh-0-2:8123 --metadata-addr=metadata:2442 --auto-create --auto-create-default-namespace --cache-dir=/var/lib/statshouse/cache/aggregator
    expose:
      - 13336
    depends_on:
      kh-0-2:
        condition: service_healthy
  aggregator-1-0:
    build:
      context: .
      dockerfile: build/statshouse.Dockerfile
      args:
        - BUILD_TRUSTED_SUBNET_GROUPS=0.0.0.0/0
        - BUILD_COMMIT
        - BUILD_COMMIT_TS
        - BUILD_MACHINE
        - BUILD_TIME
    user: "root:root"
    command: aggregator -u=root -g=root --cluster=test_shard_aggregator --agg-addr=':13336' --kh=kh-1-0:8123 --metadata-addr=metadata:2442 --auto-create --auto-create-default-namespace --cache-dir=/var/lib/statshouse/cache/aggregator
    expose:
      - 13336
    depends_on:
      kh-1-0:
        condition: service_healthy
  aggregator-1-1:
    build:
      context: .
      dockerfile: build/statshouse.Dockerfile
      args:
        - BUILD_TRUSTED_SUBNET_GROUPS=0.0.0.0/0
        - BUILD_COMMIT
        - BUILD_COMMIT_TS
        - BUILD_MACHINE
        - BUILD_TIME
    user: "root:root"
    command: aggregator -u=root -g=root --cluster=test_shard_aggregator --agg-addr=':13336' --kh=kh-1-1:8123 --metadata-addr=metadata:2442 --auto-create --auto-create-default-namespace --cache-dir=/var/lib/statshouse/cache/aggregator
    expose:
      - 13336
    depends_on:
      kh-1-1:
        condition: service_healthy
  aggregator-1-2:
    build:
      context: .
      dockerfile: build/statshouse.Dockerfile
      args:
        - BUILD_TRUSTED_SUBNET_GROUPS=0.0.0.0/0
        - BUILD_COMMIT
        - BUILD_COMMIT_TS
        - BUILD_MACHINE
        - BUILD_TIME
    user: "root:root"
    command: aggregator -u=root -g=root --cluster=test_shard_aggregator --agg-addr=':13336' --kh=kh-1-2:8123 --metadata-addr=metadata:2442 --auto-create --auto-create-default-namespace --cache-dir=/var/lib/statshouse/cache/aggregator
    expose:
      - 13336
    depends_on:
      kh-1-2:
        condition: service_healthy
  aggregator-2-0:
    build:
      context: .
      dockerfile: build/statshouse.Dockerfile
      args:
        - BUILD_TRUSTED_SUBNET_GROUPS=0.0.0.0/0
        - BUILD_COMMIT
        - BUILD_COMMIT_TS
        - BUILD_MACHINE
        - BUILD_TIME
    user: "root:root"
    command: aggregator -u=root -g=root --cluster=test_shard_aggregator --agg-addr=':13336' --kh=kh-2-0:8123 --metadata-addr=metadata:2442 --auto-create --auto-create-default-namespace --cache-dir=/var/lib/statshouse/cache/aggregator
    expose:
      - 13336
    depends_on:
      kh-2-0:
        condition: service_healthy
  aggregator-2-1:
    build:
      context: .
      dockerfile: build/statshouse.Dockerfile
      args:
        - BUILD_TRUSTED_SUBNET_GROUPS=0.0.0.0/0
        - BUILD_COMMIT
        - BUILD_COMMIT_TS
        - BUILD_MACHINE
        - BUILD_TIME
    user: "root:root"
    command: aggregator -u=root -g=root --cluster=test_shard_aggregator --agg-addr=':13336' --kh=kh-2-1:8123 --metadata-addr=metadata:2442 --auto-create --auto-create-default-namespace --cache-dir=/var/lib/statshouse/cache/aggregator
    expose:
      - 13336
    depends_on:
      kh-2-1:
        condition: service_healthy
  aggregator-2-2:
    build:
      context: .
      dockerfile: build/statshouse.Dockerfile
      args:
        - BUILD_TRUSTED_SUBNET_GROUPS=0.0.0.0/0
        - BUILD_COMMIT
        - BUILD_COMMIT_TS
        - BUILD_MACHINE
        - BUILD_TIME
    user: "root:root"
    command: aggregator -u=root -g=root --cluster=test_shard_aggregator --agg-addr=':13336' --kh=kh-2-2:8123 --metadata-addr=metadata:2442 --auto-create --auto-create-default-namespace --cache-dir=/var/lib/statshouse/cache/aggregator
    expose:
      - 13336
    depends_on:
      kh-2-2:
        condition: service_healthy

  metadata:
    build:
      context: .
      dockerfile: build/statshouse-metadata.Dockerfile
      args:
        - BUILD_TRUSTED_SUBNET_GROUPS=0.0.0.0/0
    container_name: sh-metadata
    user: "root:root"
    command: --statshouse-addr=agent:13337 --db-path=/var/lib/statshouse/metadata/db --binlog-prefix=/var/lib/statshouse/metadata/binlog/bl
    volumes:
      - metadata:/var/lib/statshouse/metadata
    expose:
      - 2442
  agent:
    build:
      context: .
      dockerfile: build/statshouse.Dockerfile
      args:
        - BUILD_TRUSTED_SUBNET_GROUPS=0.0.0.0/0
        - BUILD_COMMIT
        - BUILD_COMMIT_TS
        - BUILD_MACHINE
        - BUILD_TIME
    container_name: sh-agent
    user: "root:root"
    command: agent -u=root -g=root --cluster=test_shard_aggregator --agg-addr='aggregator-0-0:13336,aggregator-0-1:13336,aggregator-0-2:13336' --cache-dir=/var/lib/statshouse/cache/agent --remote-write-enabled
    expose:
      - 13337
      - 13380
  api:
    build:
      context: .
      dockerfile: build/statshouse-api.Dockerfile
      args:
        - BUILD_TRUSTED_SUBNET_GROUPS=0.0.0.0/0
        - BUILD_COMMIT
        - BUILD_COMMIT_TS
        - BUILD_MACHINE
        - BUILD_TIME
    container_name: sh-api
    user: "root:root"
    command: --verbose --insecure-mode --local-mode --access-log --clickhouse-v2-addrs=kh-0-0:9000,kh-0-1:9000,kh-0-2:9000 --listen-addr=:10888 --metadata-addr=metadata:2442 --statshouse-addr=agent:13337 --disk-cache=/var/lib/statshouse/cache/api/mapping_cache.sqlite3
    ports:
      - "10888:10888"
    depends_on:
      kh-0-0:
        condition: service_healthy
      kh-0-1:
        condition: service_healthy
      kh-0-2:
        condition: service_healthy
      kh-1-0:
        condition: service_healthy
      kh-1-1:
        condition: service_healthy
      kh-1-2:
        condition: service_healthy
      kh-2-0:
        condition: service_healthy
      kh-2-1:
        condition: service_healthy
      kh-2-2:
        condition: service_healthy


volumes:
  kh-0-0:
  kh-0-1:
  kh-0-2:
  kh-1-0:
  kh-1-1:
  kh-1-2:
  kh-2-0:
  kh-2-1:
  kh-2-2:
  metadata:
  prometheus:
