services:
  zookeeper:
    image: zookeeper:3.7
    container_name: zookeeper
    hostname: zookeeper
    expose:
      - 2181
    volumes:
      - zookeeper-data:/data
      - zookeeper-datalog:/datalog
  kh:
    image: clickhouse/clickhouse-server:${CH_VERSION}
    container_name: kh
    hostname: localhost  # in order for autoconfigure to work
    environment:
      # that is fine only for local run
      - CLICKHOUSE_SKIP_USER_SETUP=1
    volumes:
      - kh:/var/lib/clickhouse
      - type: bind
        source: ./configs/ch/config.xml
        target: /etc/clickhouse-server/config.d/config.xml
      - type: bind
        source: ./scripts/v2-cluster-init.sql
        target: /docker-entrypoint-initdb.d/v2-cluster-init.sql
      - type: bind
        source: ./scripts/v3-cluster-init.sql
        target: /docker-entrypoint-initdb.d/v3-cluster-init.sql
    expose:
      - 8123
      - 9000
      - 9363
    ports:
      - 9000:9000
      - 8123:8123
    healthcheck:
      test: ["CMD-SHELL", "clickhouse-client --query='SELECT 1'"]
      interval: 200ms
      timeout: 1s
      retries: 1500
    depends_on:
      - zookeeper

volumes:
  kh:
  zookeeper-data:
  zookeeper-datalog:
