// Copyright 2025 V Kontakte LLC
//
// This Source Code Form is subject to the terms of the Mozilla Public
// License, v. 2.0. If a copy of the MPL was not distributed with this
// file, You can obtain one at https://mozilla.org/MPL/2.0/.

// Code generated by tl2gen; DO NOT EDIT.
package internal

import (
	"github.com/VKCOM/statshouse/internal/vkgo/basictl"
)

var _ = basictl.NatWrite

// same as nop, but assumed as write in proxy
type EngineWriteNop struct {
}

func (EngineWriteNop) TLName() string { return "engine.writeNop" }
func (EngineWriteNop) TLTag() uint32  { return 0x58160af4 }

func (item *EngineWriteNop) Reset() {}

func (item *EngineWriteNop) FillRandom(rg *basictl.RandGenerator) {}

func (item *EngineWriteNop) ReadTL1(w []byte) (_ []byte, err error) { return w, nil }

func (item *EngineWriteNop) WriteTL1General(w []byte) (_ []byte, err error) {
	return item.WriteTL1(w), nil
}

func (item *EngineWriteNop) WriteTL1(w []byte) []byte {
	return w
}

func (item *EngineWriteNop) ReadTL1Boxed(w []byte) (_ []byte, err error) {
	if w, err = basictl.NatReadExactTag(w, 0x58160af4); err != nil {
		return w, err
	}
	return item.ReadTL1(w)
}

func (item *EngineWriteNop) WriteTL1BoxedGeneral(w []byte) (_ []byte, err error) {
	return item.WriteTL1Boxed(w), nil
}

func (item *EngineWriteNop) WriteTL1Boxed(w []byte) []byte {
	w = basictl.NatWrite(w, 0x58160af4)
	return item.WriteTL1(w)
}

func (item *EngineWriteNop) ReadResultTL1(w []byte, ret *True) (_ []byte, err error) {
	return ret.ReadTL1Boxed(w)
}

func (item *EngineWriteNop) WriteResultTL1(w []byte, ret True) (_ []byte, err error) {
	w = ret.WriteTL1Boxed(w)
	return w, nil
}

func (item *EngineWriteNop) ReadResultJSON(legacyTypeNames bool, in *basictl.JsonLexer, ret *True) error {
	tctx := &basictl.JSONReadContext{LegacyTypeNames: legacyTypeNames}
	if err := ret.ReadJSONGeneral(tctx, in); err != nil {
		return err
	}
	return nil
}

func (item *EngineWriteNop) WriteResultJSON(w []byte, ret True) (_ []byte, err error) {
	tctx := basictl.JSONWriteContext{}
	return item.writeResultJSON(&tctx, w, ret)
}

func (item *EngineWriteNop) writeResultJSON(tctx *basictl.JSONWriteContext, w []byte, ret True) (_ []byte, err error) {
	w = ret.WriteJSONOpt(tctx, w)
	return w, nil
}

func (item *EngineWriteNop) FillRandomResultTL1(rg *basictl.RandGenerator, w []byte) ([]byte, error) {
	var ret True
	ret.FillRandom(rg)
	return item.WriteResultTL1(w, ret)
}

func (item *EngineWriteNop) ReadResultTL1WriteResultJSON(tctx *basictl.JSONWriteContext, r []byte, w []byte) (_ []byte, _ []byte, err error) {
	var ret True
	if r, err = item.ReadResultTL1(r, &ret); err != nil {
		return r, w, err
	}
	w, err = item.writeResultJSON(tctx, w, ret)
	return r, w, err
}

func (item *EngineWriteNop) ReadResultJSONWriteResultTL1(r []byte, w []byte) (_ []byte, _ []byte, err error) {
	var ret True
	if err = item.ReadResultJSON(true, &basictl.JsonLexer{Data: r}, &ret); err != nil {
		return r, w, err
	}
	w, err = item.WriteResultTL1(w, ret)
	return r, w, err
}

func (item *EngineWriteNop) ReadResultTL1WriteResultTL2(tctx *basictl.TL2WriteContext, r []byte, w []byte) (_ []byte, _ []byte, err error) {
	return r, w, ErrorTL2SerializersNotGenerated("engine.writeNop")
}

func (item *EngineWriteNop) ReadResultTL2WriteResultTL1(tctx *basictl.TL2ReadContext, r []byte, w []byte) (_ []byte, _ []byte, err error) {
	return r, w, ErrorTL2SerializersNotGenerated("engine.writeNop")
}

func (item *EngineWriteNop) ReadResultTL2WriteResultJSON(tctx *basictl.TL2ReadContext, jctx *basictl.JSONWriteContext, r []byte, w []byte) (_ []byte, _ []byte, err error) {
	return r, w, ErrorTL2SerializersNotGenerated("engine.writeNop")
}

func (item *EngineWriteNop) ReadResultJSONWriteResultTL2(tctx *basictl.TL2WriteContext, r []byte, w []byte) (_ []byte, _ []byte, err error) {
	return r, w, ErrorTL2SerializersNotGenerated("engine.writeNop")
}

func (item EngineWriteNop) String() string {
	return string(item.WriteJSON(nil))
}

func (item *EngineWriteNop) ReadJSON(legacyTypeNames bool, in *basictl.JsonLexer) error {
	tctx := basictl.JSONReadContext{LegacyTypeNames: legacyTypeNames}
	return item.ReadJSONGeneral(&tctx, in)
}

func (item *EngineWriteNop) ReadJSONGeneral(tctx *basictl.JSONReadContext, in *basictl.JsonLexer) error {
	if in != nil {
		in.Delim('{')
		if !in.Ok() {
			return in.Error()
		}
		for !in.IsDelim('}') {
			return ErrorInvalidJSON("engine.writeNop", "this object can't have properties")
		}
		in.Delim('}')
		if !in.Ok() {
			return in.Error()
		}
	}
	return nil
}

// This method is general version of WriteJSON, use it instead!
func (item *EngineWriteNop) WriteJSONGeneral(tctx *basictl.JSONWriteContext, w []byte) (_ []byte, err error) {
	return item.WriteJSONOpt(tctx, w), nil
}

func (item *EngineWriteNop) WriteJSON(w []byte) []byte {
	tctx := basictl.JSONWriteContext{}
	return item.WriteJSONOpt(&tctx, w)
}
func (item *EngineWriteNop) WriteJSONOpt(tctx *basictl.JSONWriteContext, w []byte) []byte {
	w = append(w, '{')
	return append(w, '}')
}

func (item *EngineWriteNop) MarshalJSON() ([]byte, error) {
	return item.WriteJSON(nil), nil
}

func (item *EngineWriteNop) UnmarshalJSON(b []byte) error {
	if err := item.ReadJSON(true, &basictl.JsonLexer{Data: b}); err != nil {
		return ErrorInvalidJSON("engine.writeNop", err.Error())
	}
	return nil
}

func (item *EngineWriteNop) WriteTL2(w []byte, ctx *basictl.TL2WriteContext) []byte {
	panic(ErrorTL2SerializersNotGenerated("engine.writeNop"))
}

func (item *EngineWriteNop) ReadTL2(r []byte, ctx *basictl.TL2ReadContext) (_ []byte, err error) {
	return r, ErrorTL2SerializersNotGenerated("engine.writeNop")
}
