// Copyright 2025 V Kontakte LLC
//
// This Source Code Form is subject to the terms of the Mozilla Public
// License, v. 2.0. If a copy of the MPL was not distributed with this
// file, You can obtain one at https://mozilla.org/MPL/2.0/.

// Code generated by vktl/cmd/tlgen2; DO NOT EDIT.
package internal

import (
	"github.com/vkcom/statshouse/internal/vkgo/basictl"
)

var _ = basictl.NatWrite

type EngineEnableMetafilesAnalyzer struct {
	Enable bool
}

func (EngineEnableMetafilesAnalyzer) TLName() string { return "engine.enableMetafilesAnalyzer" }
func (EngineEnableMetafilesAnalyzer) TLTag() uint32  { return 0x88836cdc }

func (item *EngineEnableMetafilesAnalyzer) Reset() {
	item.Enable = false
}

func (item *EngineEnableMetafilesAnalyzer) Read(w []byte) (_ []byte, err error) {
	return BoolReadBoxed(w, &item.Enable)
}

// This method is general version of Write, use it instead!
func (item *EngineEnableMetafilesAnalyzer) WriteGeneral(w []byte) (_ []byte, err error) {
	return item.Write(w), nil
}

func (item *EngineEnableMetafilesAnalyzer) Write(w []byte) []byte {
	w = BoolWriteBoxed(w, item.Enable)
	return w
}

func (item *EngineEnableMetafilesAnalyzer) ReadBoxed(w []byte) (_ []byte, err error) {
	if w, err = basictl.NatReadExactTag(w, 0x88836cdc); err != nil {
		return w, err
	}
	return item.Read(w)
}

// This method is general version of WriteBoxed, use it instead!
func (item *EngineEnableMetafilesAnalyzer) WriteBoxedGeneral(w []byte) (_ []byte, err error) {
	return item.WriteBoxed(w), nil
}

func (item *EngineEnableMetafilesAnalyzer) WriteBoxed(w []byte) []byte {
	w = basictl.NatWrite(w, 0x88836cdc)
	return item.Write(w)
}

func (item *EngineEnableMetafilesAnalyzer) ReadResult(w []byte, ret *bool) (_ []byte, err error) {
	return BoolReadBoxed(w, ret)
}

func (item *EngineEnableMetafilesAnalyzer) WriteResult(w []byte, ret bool) (_ []byte, err error) {
	w = BoolWriteBoxed(w, ret)
	return w, nil
}

func (item *EngineEnableMetafilesAnalyzer) ReadResultJSON(legacyTypeNames bool, in *basictl.JsonLexer, ret *bool) error {
	if err := Json2ReadBool(in, ret); err != nil {
		return err
	}
	return nil
}

func (item *EngineEnableMetafilesAnalyzer) WriteResultJSON(w []byte, ret bool) (_ []byte, err error) {
	return item.writeResultJSON(true, false, w, ret)
}

func (item *EngineEnableMetafilesAnalyzer) writeResultJSON(newTypeNames bool, short bool, w []byte, ret bool) (_ []byte, err error) {
	w = basictl.JSONWriteBool(w, ret)
	return w, nil
}

func (item *EngineEnableMetafilesAnalyzer) ReadResultWriteResultJSON(r []byte, w []byte) (_ []byte, _ []byte, err error) {
	var ret bool
	if r, err = item.ReadResult(r, &ret); err != nil {
		return r, w, err
	}
	w, err = item.WriteResultJSON(w, ret)
	return r, w, err
}

func (item *EngineEnableMetafilesAnalyzer) ReadResultWriteResultJSONOpt(newTypeNames bool, short bool, r []byte, w []byte) (_ []byte, _ []byte, err error) {
	var ret bool
	if r, err = item.ReadResult(r, &ret); err != nil {
		return r, w, err
	}
	w, err = item.writeResultJSON(newTypeNames, short, w, ret)
	return r, w, err
}

func (item *EngineEnableMetafilesAnalyzer) ReadResultJSONWriteResult(r []byte, w []byte) ([]byte, []byte, error) {
	var ret bool
	err := item.ReadResultJSON(true, &basictl.JsonLexer{Data: r}, &ret)
	if err != nil {
		return r, w, err
	}
	w, err = item.WriteResult(w, ret)
	return r, w, err
}

func (item EngineEnableMetafilesAnalyzer) String() string {
	return string(item.WriteJSON(nil))
}

func (item *EngineEnableMetafilesAnalyzer) ReadJSON(legacyTypeNames bool, in *basictl.JsonLexer) error {
	var propEnablePresented bool

	if in != nil {
		in.Delim('{')
		if !in.Ok() {
			return in.Error()
		}
		for !in.IsDelim('}') {
			key := in.UnsafeFieldName(true)
			in.WantColon()
			switch key {
			case "enable":
				if propEnablePresented {
					return ErrorInvalidJSONWithDuplicatingKeys("engine.enableMetafilesAnalyzer", "enable")
				}
				if err := Json2ReadBool(in, &item.Enable); err != nil {
					return err
				}
				propEnablePresented = true
			default:
				return ErrorInvalidJSONExcessElement("engine.enableMetafilesAnalyzer", key)
			}
			in.WantComma()
		}
		in.Delim('}')
		if !in.Ok() {
			return in.Error()
		}
	}
	if !propEnablePresented {
		item.Enable = false
	}
	return nil
}

// This method is general version of WriteJSON, use it instead!
func (item *EngineEnableMetafilesAnalyzer) WriteJSONGeneral(w []byte) (_ []byte, err error) {
	return item.WriteJSONOpt(true, false, w), nil
}

func (item *EngineEnableMetafilesAnalyzer) WriteJSON(w []byte) []byte {
	return item.WriteJSONOpt(true, false, w)
}
func (item *EngineEnableMetafilesAnalyzer) WriteJSONOpt(newTypeNames bool, short bool, w []byte) []byte {
	w = append(w, '{')
	backupIndexEnable := len(w)
	w = basictl.JSONAddCommaIfNeeded(w)
	w = append(w, `"enable":`...)
	w = basictl.JSONWriteBool(w, item.Enable)
	if (item.Enable) == false {
		w = w[:backupIndexEnable]
	}
	return append(w, '}')
}

func (item *EngineEnableMetafilesAnalyzer) MarshalJSON() ([]byte, error) {
	return item.WriteJSON(nil), nil
}

func (item *EngineEnableMetafilesAnalyzer) UnmarshalJSON(b []byte) error {
	if err := item.ReadJSON(true, &basictl.JsonLexer{Data: b}); err != nil {
		return ErrorInvalidJSON("engine.enableMetafilesAnalyzer", err.Error())
	}
	return nil
}
