// Copyright 2025 V Kontakte LLC
//
// This Source Code Form is subject to the terms of the Mozilla Public
// License, v. 2.0. If a copy of the MPL was not distributed with this
// file, You can obtain one at https://mozilla.org/MPL/2.0/.

// Code generated by tl2gen; DO NOT EDIT.
package internal

import (
	"github.com/VKCOM/statshouse/internal/vkgo/basictl"
)

var _ = basictl.NatWrite

type EngineSwitchToReplicaMode struct {
}

func (EngineSwitchToReplicaMode) TLName() string { return "engine.switchToReplicaMode" }
func (EngineSwitchToReplicaMode) TLTag() uint32  { return 0x23c3a87e }

func (item *EngineSwitchToReplicaMode) Reset() {}

func (item *EngineSwitchToReplicaMode) FillRandom(rg *basictl.RandGenerator) {}

func (item *EngineSwitchToReplicaMode) ReadTL1(w []byte) (_ []byte, err error) { return w, nil }

func (item *EngineSwitchToReplicaMode) WriteTL1General(w []byte) (_ []byte, err error) {
	return item.WriteTL1(w), nil
}

func (item *EngineSwitchToReplicaMode) WriteTL1(w []byte) []byte {
	return w
}

func (item *EngineSwitchToReplicaMode) ReadTL1Boxed(w []byte) (_ []byte, err error) {
	if w, err = basictl.NatReadExactTag(w, 0x23c3a87e); err != nil {
		return w, err
	}
	return item.ReadTL1(w)
}

func (item *EngineSwitchToReplicaMode) WriteTL1BoxedGeneral(w []byte) (_ []byte, err error) {
	return item.WriteTL1Boxed(w), nil
}

func (item *EngineSwitchToReplicaMode) WriteTL1Boxed(w []byte) []byte {
	w = basictl.NatWrite(w, 0x23c3a87e)
	return item.WriteTL1(w)
}

func (item *EngineSwitchToReplicaMode) ReadResultTL1(w []byte, ret *EngineSwitchMasterReplicaModeResult) (_ []byte, err error) {
	return ret.ReadTL1Boxed(w)
}

func (item *EngineSwitchToReplicaMode) WriteResultTL1(w []byte, ret EngineSwitchMasterReplicaModeResult) (_ []byte, err error) {
	w = ret.WriteTL1Boxed(w)
	return w, nil
}

func (item *EngineSwitchToReplicaMode) ReadResultJSON(jctx *basictl.JSONReadContext, in *basictl.JsonLexer, ret *EngineSwitchMasterReplicaModeResult) error {
	if err := ret.ReadJSONGeneral(jctx, in); err != nil {
		return err
	}
	return nil
}

func (item *EngineSwitchToReplicaMode) WriteResultJSON(w []byte, ret EngineSwitchMasterReplicaModeResult) (_ []byte, err error) {
	return item.writeResultJSON(nil, w, ret)
}

func (item *EngineSwitchToReplicaMode) writeResultJSON(jctx *basictl.JSONWriteContext, w []byte, ret EngineSwitchMasterReplicaModeResult) (_ []byte, err error) {
	w = ret.WriteJSONOpt(jctx, w)
	return w, nil
}

func (item *EngineSwitchToReplicaMode) FillRandomResultTL1(rg *basictl.RandGenerator, w []byte) ([]byte, error) {
	var ret EngineSwitchMasterReplicaModeResult
	ret.FillRandom(rg)
	return item.WriteResultTL1(w, ret)
}

func (item *EngineSwitchToReplicaMode) ReadResultTL1WriteResultJSON(jctx *basictl.JSONWriteContext, r []byte, w []byte) (_ []byte, _ []byte, err error) {
	var ret EngineSwitchMasterReplicaModeResult
	if r, err = item.ReadResultTL1(r, &ret); err != nil {
		return r, w, err
	}
	w, err = item.writeResultJSON(jctx, w, ret)
	return r, w, err
}

func (item *EngineSwitchToReplicaMode) ReadResultJSONWriteResultTL1(jctx *basictl.JSONReadContext, r []byte, w []byte) (_ []byte, _ []byte, err error) {
	var ret EngineSwitchMasterReplicaModeResult
	if err = item.ReadResultJSON(jctx, &basictl.JsonLexer{Data: r}, &ret); err != nil {
		return r, w, err
	}
	w, err = item.WriteResultTL1(w, ret)
	return r, w, err
}

func (item *EngineSwitchToReplicaMode) ReadResultTL1WriteResultTL2(tctx *basictl.TL2WriteContext, r []byte, w []byte) (_ []byte, _ []byte, err error) {
	return r, w, ErrorTL2SerializersNotGenerated("engine.switchToReplicaMode")
}

func (item *EngineSwitchToReplicaMode) ReadResultTL2WriteResultTL1(tctx *basictl.TL2ReadContext, r []byte, w []byte) (_ []byte, _ []byte, err error) {
	return r, w, ErrorTL2SerializersNotGenerated("engine.switchToReplicaMode")
}

func (item *EngineSwitchToReplicaMode) ReadResultTL2WriteResultJSON(tctx *basictl.TL2ReadContext, jctx *basictl.JSONWriteContext, r []byte, w []byte) (_ []byte, _ []byte, err error) {
	return r, w, ErrorTL2SerializersNotGenerated("engine.switchToReplicaMode")
}

func (item *EngineSwitchToReplicaMode) ReadResultJSONWriteResultTL2(jctx *basictl.JSONReadContext, tctx *basictl.TL2WriteContext, r []byte, w []byte) (_ []byte, _ []byte, err error) {
	return r, w, ErrorTL2SerializersNotGenerated("engine.switchToReplicaMode")
}

func (item EngineSwitchToReplicaMode) String() string {
	return string(item.WriteJSON(nil))
}

func (item *EngineSwitchToReplicaMode) ReadJSON(legacyTypeNames bool, in *basictl.JsonLexer) error {
	jctx := basictl.JSONReadContext{LegacyTypeNames: legacyTypeNames}
	return item.ReadJSONGeneral(&jctx, in)
}

func (item *EngineSwitchToReplicaMode) ReadJSONGeneral(jctx *basictl.JSONReadContext, in *basictl.JsonLexer) error {
	if in != nil {
		in.Delim('{')
		if !in.Ok() {
			return in.Error()
		}
		for !in.IsDelim('}') {
			return ErrorInvalidJSON("engine.switchToReplicaMode", "this object can't have properties")
		}
		in.Delim('}')
		if !in.Ok() {
			return in.Error()
		}
	}
	return nil
}

// This method is general version of WriteJSON, use it instead!
func (item *EngineSwitchToReplicaMode) WriteJSONGeneral(jctx *basictl.JSONWriteContext, w []byte) (_ []byte, err error) {
	return item.WriteJSONOpt(jctx, w), nil
}

func (item *EngineSwitchToReplicaMode) WriteJSON(w []byte) []byte {
	return item.WriteJSONOpt(nil, w)
}
func (item *EngineSwitchToReplicaMode) WriteJSONOpt(jctx *basictl.JSONWriteContext, w []byte) []byte {
	w = append(w, '{')
	return append(w, '}')
}

func (item *EngineSwitchToReplicaMode) MarshalJSON() ([]byte, error) {
	return item.WriteJSON(nil), nil
}

func (item *EngineSwitchToReplicaMode) UnmarshalJSON(b []byte) error {
	jctx := basictl.JSONReadContext{LegacyTypeNames: true}
	if err := item.ReadJSONGeneral(&jctx, &basictl.JsonLexer{Data: b}); err != nil {
		return ErrorInvalidJSON("engine.switchToReplicaMode", err.Error())
	}
	return nil
}

func (item *EngineSwitchToReplicaMode) WriteTL2(w []byte, tctx *basictl.TL2WriteContext) []byte {
	panic(ErrorTL2SerializersNotGenerated("engine.switchToReplicaMode"))
}

func (item *EngineSwitchToReplicaMode) ReadTL2(r []byte, tctx *basictl.TL2ReadContext) (_ []byte, err error) {
	return r, ErrorTL2SerializersNotGenerated("engine.switchToReplicaMode")
}
