// Copyright 2023 V Kontakte LLC
//
// This Source Code Form is subject to the terms of the Mozilla Public
// License, v. 2.0. If a copy of the MPL was not distributed with this
// file, You can obtain one at https://mozilla.org/MPL/2.0/.

// Code generated by vktl/cmd/tlgen2; DO NOT EDIT.
package internal

import (
	"github.com/vkcom/statshouse/internal/vkgo/basictl"
)

var _ = basictl.NatWrite

type EngineNop struct {
}

func (EngineNop) TLName() string { return "engine.nop" }
func (EngineNop) TLTag() uint32  { return 0x166bb7c6 }

func (item *EngineNop) Reset()                         {}
func (item *EngineNop) Read(w []byte) ([]byte, error)  { return w, nil }
func (item *EngineNop) Write(w []byte) ([]byte, error) { return w, nil }
func (item *EngineNop) ReadBoxed(w []byte) ([]byte, error) {
	return basictl.NatReadExactTag(w, 0x166bb7c6)
}
func (item *EngineNop) WriteBoxed(w []byte) ([]byte, error) {
	return basictl.NatWrite(w, 0x166bb7c6), nil
}

func (item *EngineNop) ReadResult(w []byte, ret *True) (_ []byte, err error) {
	return ret.ReadBoxed(w)
}

func (item *EngineNop) WriteResult(w []byte, ret True) (_ []byte, err error) {
	return ret.WriteBoxed(w)
}

func (item *EngineNop) ReadResultJSON(j interface{}, ret *True) error {
	if err := True__ReadJSON(ret, j); err != nil {
		return err
	}
	return nil
}

func (item *EngineNop) WriteResultJSON(w []byte, ret True) (_ []byte, err error) {
	if w, err = ret.WriteJSON(w); err != nil {
		return w, err
	}
	return w, nil
}

func (item *EngineNop) ReadResultWriteResultJSON(r []byte, w []byte) (_ []byte, _ []byte, err error) {
	var ret True
	if r, err = item.ReadResult(r, &ret); err != nil {
		return r, w, err
	}
	w, err = item.WriteResultJSON(w, ret)
	return r, w, err
}

func (item *EngineNop) ReadResultJSONWriteResult(r []byte, w []byte) ([]byte, []byte, error) {
	j, err := JsonBytesToInterface(r)
	if err != nil {
		return r, w, ErrorInvalidJSON("engine.nop", err.Error())
	}
	var ret True
	if err = item.ReadResultJSON(j, &ret); err != nil {
		return r, w, err
	}
	w, err = item.WriteResult(w, ret)
	return r, w, err
}

func (item EngineNop) String() string {
	w, err := item.WriteJSON(nil)
	if err != nil {
		return err.Error()
	}
	return string(w)
}

func EngineNop__ReadJSON(item *EngineNop, j interface{}) error { return item.readJSON(j) }
func (item *EngineNop) readJSON(j interface{}) error {
	_jm, _ok := j.(map[string]interface{})
	if j != nil && !_ok {
		return ErrorInvalidJSON("engine.nop", "expected json object")
	}
	for k := range _jm {
		return ErrorInvalidJSONExcessElement("engine.nop", k)
	}
	return nil
}

func (item *EngineNop) WriteJSON(w []byte) (_ []byte, err error) {
	w = append(w, '{')
	return append(w, '}'), nil
}

func (item *EngineNop) MarshalJSON() ([]byte, error) {
	return item.WriteJSON(nil)
}

func (item *EngineNop) UnmarshalJSON(b []byte) error {
	j, err := JsonBytesToInterface(b)
	if err != nil {
		return ErrorInvalidJSON("engine.nop", err.Error())
	}
	if err = item.readJSON(j); err != nil {
		return ErrorInvalidJSON("engine.nop", err.Error())
	}
	return nil
}
