// Copyright 2025 V Kontakte LLC
//
// This Source Code Form is subject to the terms of the Mozilla Public
// License, v. 2.0. If a copy of the MPL was not distributed with this
// file, You can obtain one at https://mozilla.org/MPL/2.0/.

// Code generated by tl2gen; DO NOT EDIT.
package internal

import (
	"github.com/VKCOM/statshouse/internal/vkgo/basictl"
)

var _ = basictl.NatWrite

// same as nop, but assumed as read in proxy
type EngineReadNop struct {
}

func (EngineReadNop) TLName() string { return "engine.readNop" }
func (EngineReadNop) TLTag() uint32  { return 0x9d2b841f }

func (item *EngineReadNop) Reset() {}

func (item *EngineReadNop) FillRandom(rg *basictl.RandGenerator) {}

func (item *EngineReadNop) ReadTL1(w []byte) (_ []byte, err error) { return w, nil }

func (item *EngineReadNop) WriteTL1General(w []byte) (_ []byte, err error) {
	return item.WriteTL1(w), nil
}

func (item *EngineReadNop) WriteTL1(w []byte) []byte {
	return w
}

func (item *EngineReadNop) ReadTL1Boxed(w []byte) (_ []byte, err error) {
	if w, err = basictl.NatReadExactTag(w, 0x9d2b841f); err != nil {
		return w, err
	}
	return item.ReadTL1(w)
}

func (item *EngineReadNop) WriteTL1BoxedGeneral(w []byte) (_ []byte, err error) {
	return item.WriteTL1Boxed(w), nil
}

func (item *EngineReadNop) WriteTL1Boxed(w []byte) []byte {
	w = basictl.NatWrite(w, 0x9d2b841f)
	return item.WriteTL1(w)
}

func (item *EngineReadNop) ReadResultTL1(w []byte, ret *True) (_ []byte, err error) {
	return ret.ReadTL1Boxed(w)
}

func (item *EngineReadNop) WriteResultTL1(w []byte, ret True) (_ []byte, err error) {
	w = ret.WriteTL1Boxed(w)
	return w, nil
}

func (item *EngineReadNop) ReadResultJSON(jctx *basictl.JSONReadContext, in *basictl.JsonLexer, ret *True) error {
	if err := ret.ReadJSONGeneral(jctx, in); err != nil {
		return err
	}
	return nil
}

func (item *EngineReadNop) WriteResultJSON(w []byte, ret True) (_ []byte, err error) {
	return item.writeResultJSON(nil, w, ret)
}

func (item *EngineReadNop) writeResultJSON(jctx *basictl.JSONWriteContext, w []byte, ret True) (_ []byte, err error) {
	w = ret.WriteJSONOpt(jctx, w)
	return w, nil
}

func (item *EngineReadNop) FillRandomResultTL1(rg *basictl.RandGenerator, w []byte) ([]byte, error) {
	var ret True
	ret.FillRandom(rg)
	return item.WriteResultTL1(w, ret)
}

func (item *EngineReadNop) ReadResultTL1WriteResultJSON(jctx *basictl.JSONWriteContext, r []byte, w []byte) (_ []byte, _ []byte, err error) {
	var ret True
	if r, err = item.ReadResultTL1(r, &ret); err != nil {
		return r, w, err
	}
	w, err = item.writeResultJSON(jctx, w, ret)
	return r, w, err
}

func (item *EngineReadNop) ReadResultJSONWriteResultTL1(jctx *basictl.JSONReadContext, r []byte, w []byte) (_ []byte, _ []byte, err error) {
	var ret True
	if err = item.ReadResultJSON(jctx, &basictl.JsonLexer{Data: r}, &ret); err != nil {
		return r, w, err
	}
	w, err = item.WriteResultTL1(w, ret)
	return r, w, err
}

func (item *EngineReadNop) ReadResultTL1WriteResultTL2(tctx *basictl.TL2WriteContext, r []byte, w []byte) (_ []byte, _ []byte, err error) {
	return r, w, ErrorTL2SerializersNotGenerated("engine.readNop")
}

func (item *EngineReadNop) ReadResultTL2WriteResultTL1(tctx *basictl.TL2ReadContext, r []byte, w []byte) (_ []byte, _ []byte, err error) {
	return r, w, ErrorTL2SerializersNotGenerated("engine.readNop")
}

func (item *EngineReadNop) ReadResultTL2WriteResultJSON(tctx *basictl.TL2ReadContext, jctx *basictl.JSONWriteContext, r []byte, w []byte) (_ []byte, _ []byte, err error) {
	return r, w, ErrorTL2SerializersNotGenerated("engine.readNop")
}

func (item *EngineReadNop) ReadResultJSONWriteResultTL2(jctx *basictl.JSONReadContext, tctx *basictl.TL2WriteContext, r []byte, w []byte) (_ []byte, _ []byte, err error) {
	return r, w, ErrorTL2SerializersNotGenerated("engine.readNop")
}

func (item EngineReadNop) String() string {
	return string(item.WriteJSON(nil))
}

func (item *EngineReadNop) ReadJSON(legacyTypeNames bool, in *basictl.JsonLexer) error {
	jctx := basictl.JSONReadContext{LegacyTypeNames: legacyTypeNames}
	return item.ReadJSONGeneral(&jctx, in)
}

func (item *EngineReadNop) ReadJSONGeneral(jctx *basictl.JSONReadContext, in *basictl.JsonLexer) error {
	if in != nil {
		in.Delim('{')
		if !in.Ok() {
			return in.Error()
		}
		for !in.IsDelim('}') {
			return ErrorInvalidJSON("engine.readNop", "this object can't have properties")
		}
		in.Delim('}')
		if !in.Ok() {
			return in.Error()
		}
	}
	return nil
}

// This method is general version of WriteJSON, use it instead!
func (item *EngineReadNop) WriteJSONGeneral(jctx *basictl.JSONWriteContext, w []byte) (_ []byte, err error) {
	return item.WriteJSONOpt(jctx, w), nil
}

func (item *EngineReadNop) WriteJSON(w []byte) []byte {
	return item.WriteJSONOpt(nil, w)
}
func (item *EngineReadNop) WriteJSONOpt(jctx *basictl.JSONWriteContext, w []byte) []byte {
	w = append(w, '{')
	return append(w, '}')
}

func (item *EngineReadNop) MarshalJSON() ([]byte, error) {
	return item.WriteJSON(nil), nil
}

func (item *EngineReadNop) UnmarshalJSON(b []byte) error {
	jctx := basictl.JSONReadContext{LegacyTypeNames: true}
	if err := item.ReadJSONGeneral(&jctx, &basictl.JsonLexer{Data: b}); err != nil {
		return ErrorInvalidJSON("engine.readNop", err.Error())
	}
	return nil
}

func (item *EngineReadNop) WriteTL2(w []byte, tctx *basictl.TL2WriteContext) []byte {
	panic(ErrorTL2SerializersNotGenerated("engine.readNop"))
}

func (item *EngineReadNop) ReadTL2(r []byte, tctx *basictl.TL2ReadContext) (_ []byte, err error) {
	return r, ErrorTL2SerializersNotGenerated("engine.readNop")
}
