// Copyright 2025 V Kontakte LLC
//
// This Source Code Form is subject to the terms of the Mozilla Public
// License, v. 2.0. If a copy of the MPL was not distributed with this
// file, You can obtain one at https://mozilla.org/MPL/2.0/.

// Code generated by tl2gen; DO NOT EDIT.
package internal

import (
	"github.com/VKCOM/statshouse/internal/vkgo/basictl"
)

var _ = basictl.NatWrite

type EngineGetReadWriteMode struct {
	FieldsMask uint32
}

func (EngineGetReadWriteMode) TLName() string { return "engine.getReadWriteMode" }
func (EngineGetReadWriteMode) TLTag() uint32  { return 0x61b3f593 }

func (item *EngineGetReadWriteMode) Reset() {
	item.FieldsMask = 0
}

func (item *EngineGetReadWriteMode) FillRandom(rg *basictl.RandGenerator) {
	item.FieldsMask = basictl.RandomFieldMask(rg, 0b11)
}

func (item *EngineGetReadWriteMode) ReadTL1(w []byte) (_ []byte, err error) {
	return basictl.NatRead(w, &item.FieldsMask)
}

func (item *EngineGetReadWriteMode) WriteTL1General(w []byte) (_ []byte, err error) {
	return item.WriteTL1(w), nil
}

func (item *EngineGetReadWriteMode) WriteTL1(w []byte) []byte {
	w = basictl.NatWrite(w, item.FieldsMask)
	return w
}

func (item *EngineGetReadWriteMode) ReadTL1Boxed(w []byte) (_ []byte, err error) {
	if w, err = basictl.NatReadExactTag(w, 0x61b3f593); err != nil {
		return w, err
	}
	return item.ReadTL1(w)
}

func (item *EngineGetReadWriteMode) WriteTL1BoxedGeneral(w []byte) (_ []byte, err error) {
	return item.WriteTL1Boxed(w), nil
}

func (item *EngineGetReadWriteMode) WriteTL1Boxed(w []byte) []byte {
	w = basictl.NatWrite(w, 0x61b3f593)
	return item.WriteTL1(w)
}

func (item *EngineGetReadWriteMode) ReadResultTL1(w []byte, ret *EngineMode) (_ []byte, err error) {
	return ret.ReadTL1Boxed(w, item.FieldsMask)
}

func (item *EngineGetReadWriteMode) WriteResultTL1(w []byte, ret EngineMode) (_ []byte, err error) {
	w = ret.WriteTL1Boxed(w, item.FieldsMask)
	return w, nil
}

func (item *EngineGetReadWriteMode) ReadResultJSON(legacyTypeNames bool, in *basictl.JsonLexer, ret *EngineMode) error {
	tctx := &basictl.JSONReadContext{LegacyTypeNames: legacyTypeNames}
	if err := ret.ReadJSONGeneral(tctx, in, item.FieldsMask); err != nil {
		return err
	}
	return nil
}

func (item *EngineGetReadWriteMode) WriteResultJSON(w []byte, ret EngineMode) (_ []byte, err error) {
	tctx := basictl.JSONWriteContext{}
	return item.writeResultJSON(&tctx, w, ret)
}

func (item *EngineGetReadWriteMode) writeResultJSON(tctx *basictl.JSONWriteContext, w []byte, ret EngineMode) (_ []byte, err error) {
	w = ret.WriteJSONOpt(tctx, w, item.FieldsMask)
	return w, nil
}

func (item *EngineGetReadWriteMode) FillRandomResultTL1(rg *basictl.RandGenerator, w []byte) ([]byte, error) {
	var ret EngineMode
	ret.FillRandom(rg, item.FieldsMask)
	return item.WriteResultTL1(w, ret)
}

func (item *EngineGetReadWriteMode) ReadResultTL1WriteResultJSON(tctx *basictl.JSONWriteContext, r []byte, w []byte) (_ []byte, _ []byte, err error) {
	var ret EngineMode
	if r, err = item.ReadResultTL1(r, &ret); err != nil {
		return r, w, err
	}
	w, err = item.writeResultJSON(tctx, w, ret)
	return r, w, err
}

func (item *EngineGetReadWriteMode) ReadResultJSONWriteResultTL1(r []byte, w []byte) (_ []byte, _ []byte, err error) {
	var ret EngineMode
	if err = item.ReadResultJSON(true, &basictl.JsonLexer{Data: r}, &ret); err != nil {
		return r, w, err
	}
	w, err = item.WriteResultTL1(w, ret)
	return r, w, err
}

func (item *EngineGetReadWriteMode) ReadResultTL1WriteResultTL2(tctx *basictl.TL2WriteContext, r []byte, w []byte) (_ []byte, _ []byte, err error) {
	return r, w, ErrorTL2SerializersNotGenerated("engine.getReadWriteMode")
}

func (item *EngineGetReadWriteMode) ReadResultTL2WriteResultTL1(tctx *basictl.TL2ReadContext, r []byte, w []byte) (_ []byte, _ []byte, err error) {
	return r, w, ErrorTL2SerializersNotGenerated("engine.getReadWriteMode")
}

func (item *EngineGetReadWriteMode) ReadResultTL2WriteResultJSON(tctx *basictl.TL2ReadContext, jctx *basictl.JSONWriteContext, r []byte, w []byte) (_ []byte, _ []byte, err error) {
	return r, w, ErrorTL2SerializersNotGenerated("engine.getReadWriteMode")
}

func (item *EngineGetReadWriteMode) ReadResultJSONWriteResultTL2(tctx *basictl.TL2WriteContext, r []byte, w []byte) (_ []byte, _ []byte, err error) {
	return r, w, ErrorTL2SerializersNotGenerated("engine.getReadWriteMode")
}

// Set field "read_enabled" in "engine.mode" by changing fieldMask "fields_mask"
func (item *EngineGetReadWriteMode) SetEngineModeReadEnabled(value bool) {
	if value {
		item.FieldsMask |= 1 << 0
	} else {
		item.FieldsMask &^= 1 << 0
	}
}

// Set field "write_enabled" in "engine.mode" by changing fieldMask "fields_mask"
func (item *EngineGetReadWriteMode) SetEngineModeWriteEnabled(value bool) {
	if value {
		item.FieldsMask |= 1 << 1
	} else {
		item.FieldsMask &^= 1 << 1
	}
}

func (item EngineGetReadWriteMode) String() string {
	return string(item.WriteJSON(nil))
}

func (item *EngineGetReadWriteMode) ReadJSON(legacyTypeNames bool, in *basictl.JsonLexer) error {
	tctx := basictl.JSONReadContext{LegacyTypeNames: legacyTypeNames}
	return item.ReadJSONGeneral(&tctx, in)
}

func (item *EngineGetReadWriteMode) ReadJSONGeneral(tctx *basictl.JSONReadContext, in *basictl.JsonLexer) error {
	var propFieldsMaskPresented bool
	if in != nil {
		in.Delim('{')
		if !in.Ok() {
			return in.Error()
		}
		for !in.IsDelim('}') {
			key := in.UnsafeFieldName(true)
			in.WantColon()
			switch key {
			case "fields_mask":
				if propFieldsMaskPresented {
					return ErrorInvalidJSONWithDuplicatingKeys("engine.getReadWriteMode", "fields_mask")
				}
				propFieldsMaskPresented = true
				if err := Json2ReadUint32(in, &item.FieldsMask); err != nil {
					return err
				}
			default:
				return ErrorInvalidJSONExcessElement("engine.getReadWriteMode", key)
			}
			in.WantComma()
		}
		in.Delim('}')
		if !in.Ok() {
			return in.Error()
		}
	}
	if !propFieldsMaskPresented {
		item.FieldsMask = 0
	}
	return nil
}

// This method is general version of WriteJSON, use it instead!
func (item *EngineGetReadWriteMode) WriteJSONGeneral(tctx *basictl.JSONWriteContext, w []byte) (_ []byte, err error) {
	return item.WriteJSONOpt(tctx, w), nil
}

func (item *EngineGetReadWriteMode) WriteJSON(w []byte) []byte {
	tctx := basictl.JSONWriteContext{}
	return item.WriteJSONOpt(&tctx, w)
}
func (item *EngineGetReadWriteMode) WriteJSONOpt(tctx *basictl.JSONWriteContext, w []byte) []byte {
	w = append(w, '{')
	backupIndexFieldsMask := len(w)
	w = basictl.JSONAddCommaIfNeeded(w)
	w = append(w, `"fields_mask":`...)
	w = basictl.JSONWriteUint32(w, item.FieldsMask)
	if !(item.FieldsMask != 0) {
		w = w[:backupIndexFieldsMask]
	}
	return append(w, '}')
}

func (item *EngineGetReadWriteMode) MarshalJSON() ([]byte, error) {
	return item.WriteJSON(nil), nil
}

func (item *EngineGetReadWriteMode) UnmarshalJSON(b []byte) error {
	if err := item.ReadJSON(true, &basictl.JsonLexer{Data: b}); err != nil {
		return ErrorInvalidJSON("engine.getReadWriteMode", err.Error())
	}
	return nil
}

func (item *EngineGetReadWriteMode) WriteTL2(w []byte, ctx *basictl.TL2WriteContext) []byte {
	panic(ErrorTL2SerializersNotGenerated("engine.getReadWriteMode"))
}

func (item *EngineGetReadWriteMode) ReadTL2(r []byte, ctx *basictl.TL2ReadContext) (_ []byte, err error) {
	return r, ErrorTL2SerializersNotGenerated("engine.getReadWriteMode")
}
