// Copyright 2023 V Kontakte LLC
//
// This Source Code Form is subject to the terms of the Mozilla Public
// License, v. 2.0. If a copy of the MPL was not distributed with this
// file, You can obtain one at https://mozilla.org/MPL/2.0/.

// Code generated by vktl/cmd/tlgen2; DO NOT EDIT.
package internal

import (
	"github.com/vkcom/statshouse/internal/vkgo/basictl"
)

var _ = basictl.NatWrite

type KvEngineMetaInfo struct {
	DbOffset        int64
	CommittedOffset int64
}

func (KvEngineMetaInfo) TLName() string { return "kv_engine.meta_info" }
func (KvEngineMetaInfo) TLTag() uint32  { return 0x53eeb763 }

func (item *KvEngineMetaInfo) Reset() {
	item.DbOffset = 0
	item.CommittedOffset = 0
}

func (item *KvEngineMetaInfo) Read(w []byte) (_ []byte, err error) {
	if w, err = basictl.LongRead(w, &item.DbOffset); err != nil {
		return w, err
	}
	return basictl.LongRead(w, &item.CommittedOffset)
}

func (item *KvEngineMetaInfo) Write(w []byte) (_ []byte, err error) {
	w = basictl.LongWrite(w, item.DbOffset)
	return basictl.LongWrite(w, item.CommittedOffset), nil
}

func (item *KvEngineMetaInfo) ReadBoxed(w []byte) (_ []byte, err error) {
	if w, err = basictl.NatReadExactTag(w, 0x53eeb763); err != nil {
		return w, err
	}
	return item.Read(w)
}

func (item *KvEngineMetaInfo) WriteBoxed(w []byte) ([]byte, error) {
	w = basictl.NatWrite(w, 0x53eeb763)
	return item.Write(w)
}

func (item KvEngineMetaInfo) String() string {
	w, err := item.WriteJSON(nil)
	if err != nil {
		return err.Error()
	}
	return string(w)
}

func (item *KvEngineMetaInfo) ReadJSON(legacyTypeNames bool, in *basictl.JsonLexer) error {
	var propDbOffsetPresented bool
	var propCommittedOffsetPresented bool

	if in != nil {
		in.Delim('{')
		if !in.Ok() {
			return in.Error()
		}
		for !in.IsDelim('}') {
			key := in.UnsafeFieldName(true)
			in.WantColon()
			switch key {
			case "db_offset":
				if propDbOffsetPresented {
					return ErrorInvalidJSONWithDuplicatingKeys("kv_engine.meta_info", "db_offset")
				}
				if err := Json2ReadInt64(in, &item.DbOffset); err != nil {
					return err
				}
				propDbOffsetPresented = true
			case "committed_offset":
				if propCommittedOffsetPresented {
					return ErrorInvalidJSONWithDuplicatingKeys("kv_engine.meta_info", "committed_offset")
				}
				if err := Json2ReadInt64(in, &item.CommittedOffset); err != nil {
					return err
				}
				propCommittedOffsetPresented = true
			default:
				return ErrorInvalidJSONExcessElement("kv_engine.meta_info", key)
			}
			in.WantComma()
		}
		in.Delim('}')
		if !in.Ok() {
			return in.Error()
		}
	}
	if !propDbOffsetPresented {
		item.DbOffset = 0
	}
	if !propCommittedOffsetPresented {
		item.CommittedOffset = 0
	}
	return nil
}

func (item *KvEngineMetaInfo) WriteJSON(w []byte) (_ []byte, err error) {
	return item.WriteJSONOpt(true, false, w)
}
func (item *KvEngineMetaInfo) WriteJSONOpt(newTypeNames bool, short bool, w []byte) (_ []byte, err error) {
	w = append(w, '{')
	backupIndexDbOffset := len(w)
	w = basictl.JSONAddCommaIfNeeded(w)
	w = append(w, `"db_offset":`...)
	w = basictl.JSONWriteInt64(w, item.DbOffset)
	if (item.DbOffset != 0) == false {
		w = w[:backupIndexDbOffset]
	}
	backupIndexCommittedOffset := len(w)
	w = basictl.JSONAddCommaIfNeeded(w)
	w = append(w, `"committed_offset":`...)
	w = basictl.JSONWriteInt64(w, item.CommittedOffset)
	if (item.CommittedOffset != 0) == false {
		w = w[:backupIndexCommittedOffset]
	}
	return append(w, '}'), nil
}

func (item *KvEngineMetaInfo) MarshalJSON() ([]byte, error) {
	return item.WriteJSON(nil)
}

func (item *KvEngineMetaInfo) UnmarshalJSON(b []byte) error {
	if err := item.ReadJSON(true, &basictl.JsonLexer{Data: b}); err != nil {
		return ErrorInvalidJSON("kv_engine.meta_info", err.Error())
	}
	return nil
}
