// Copyright 2023 V Kontakte LLC
//
// This Source Code Form is subject to the terms of the Mozilla Public
// License, v. 2.0. If a copy of the MPL was not distributed with this
// file, You can obtain one at https://mozilla.org/MPL/2.0/.

// Code generated by vktl/cmd/tlgen2; DO NOT EDIT.
package internal

import (
	"github.com/vkcom/statshouse/internal/vkgo/basictl"
)

var _ = basictl.NatWrite

type KvEngineInc struct {
	Key  int64
	Incr int64
}

func (KvEngineInc) TLName() string { return "kv_engine.inc" }
func (KvEngineInc) TLTag() uint32  { return 0x3c7239bb }

func (item *KvEngineInc) Reset() {
	item.Key = 0
	item.Incr = 0
}

func (item *KvEngineInc) Read(w []byte) (_ []byte, err error) {
	if w, err = basictl.LongRead(w, &item.Key); err != nil {
		return w, err
	}
	return basictl.LongRead(w, &item.Incr)
}

func (item *KvEngineInc) Write(w []byte) (_ []byte, err error) {
	w = basictl.LongWrite(w, item.Key)
	return basictl.LongWrite(w, item.Incr), nil
}

func (item *KvEngineInc) ReadBoxed(w []byte) (_ []byte, err error) {
	if w, err = basictl.NatReadExactTag(w, 0x3c7239bb); err != nil {
		return w, err
	}
	return item.Read(w)
}

func (item *KvEngineInc) WriteBoxed(w []byte) ([]byte, error) {
	w = basictl.NatWrite(w, 0x3c7239bb)
	return item.Write(w)
}

func (item *KvEngineInc) ReadResult(w []byte, ret *KvEngineChangeResponse) (_ []byte, err error) {
	return ret.ReadBoxed(w)
}

func (item *KvEngineInc) WriteResult(w []byte, ret KvEngineChangeResponse) (_ []byte, err error) {
	return ret.WriteBoxed(w)
}

func (item *KvEngineInc) ReadResultJSON(legacyTypeNames bool, in *basictl.JsonLexer, ret *KvEngineChangeResponse) error {
	if err := ret.ReadJSON(legacyTypeNames, in); err != nil {
		return err
	}
	return nil
}

func (item *KvEngineInc) WriteResultJSON(w []byte, ret KvEngineChangeResponse) (_ []byte, err error) {
	return item.writeResultJSON(true, false, w, ret)
}

func (item *KvEngineInc) writeResultJSON(newTypeNames bool, short bool, w []byte, ret KvEngineChangeResponse) (_ []byte, err error) {
	if w, err = ret.WriteJSONOpt(newTypeNames, short, w); err != nil {
		return w, err
	}
	return w, nil
}

func (item *KvEngineInc) ReadResultWriteResultJSON(r []byte, w []byte) (_ []byte, _ []byte, err error) {
	var ret KvEngineChangeResponse
	if r, err = item.ReadResult(r, &ret); err != nil {
		return r, w, err
	}
	w, err = item.WriteResultJSON(w, ret)
	return r, w, err
}

func (item *KvEngineInc) ReadResultWriteResultJSONOpt(newTypeNames bool, short bool, r []byte, w []byte) (_ []byte, _ []byte, err error) {
	var ret KvEngineChangeResponse
	if r, err = item.ReadResult(r, &ret); err != nil {
		return r, w, err
	}
	w, err = item.writeResultJSON(newTypeNames, short, w, ret)
	return r, w, err
}

func (item *KvEngineInc) ReadResultJSONWriteResult(r []byte, w []byte) ([]byte, []byte, error) {
	var ret KvEngineChangeResponse
	err := item.ReadResultJSON(true, &basictl.JsonLexer{Data: r}, &ret)
	if err != nil {
		return r, w, err
	}
	w, err = item.WriteResult(w, ret)
	return r, w, err
}

func (item KvEngineInc) String() string {
	w, err := item.WriteJSON(nil)
	if err != nil {
		return err.Error()
	}
	return string(w)
}

func (item *KvEngineInc) ReadJSON(legacyTypeNames bool, in *basictl.JsonLexer) error {
	var propKeyPresented bool
	var propIncrPresented bool

	if in != nil {
		in.Delim('{')
		if !in.Ok() {
			return in.Error()
		}
		for !in.IsDelim('}') {
			key := in.UnsafeFieldName(true)
			in.WantColon()
			switch key {
			case "key":
				if propKeyPresented {
					return ErrorInvalidJSONWithDuplicatingKeys("kv_engine.inc", "key")
				}
				if err := Json2ReadInt64(in, &item.Key); err != nil {
					return err
				}
				propKeyPresented = true
			case "incr":
				if propIncrPresented {
					return ErrorInvalidJSONWithDuplicatingKeys("kv_engine.inc", "incr")
				}
				if err := Json2ReadInt64(in, &item.Incr); err != nil {
					return err
				}
				propIncrPresented = true
			default:
				return ErrorInvalidJSONExcessElement("kv_engine.inc", key)
			}
			in.WantComma()
		}
		in.Delim('}')
		if !in.Ok() {
			return in.Error()
		}
	}
	if !propKeyPresented {
		item.Key = 0
	}
	if !propIncrPresented {
		item.Incr = 0
	}
	return nil
}

func (item *KvEngineInc) WriteJSON(w []byte) (_ []byte, err error) {
	return item.WriteJSONOpt(true, false, w)
}
func (item *KvEngineInc) WriteJSONOpt(newTypeNames bool, short bool, w []byte) (_ []byte, err error) {
	w = append(w, '{')
	backupIndexKey := len(w)
	w = basictl.JSONAddCommaIfNeeded(w)
	w = append(w, `"key":`...)
	w = basictl.JSONWriteInt64(w, item.Key)
	if (item.Key != 0) == false {
		w = w[:backupIndexKey]
	}
	backupIndexIncr := len(w)
	w = basictl.JSONAddCommaIfNeeded(w)
	w = append(w, `"incr":`...)
	w = basictl.JSONWriteInt64(w, item.Incr)
	if (item.Incr != 0) == false {
		w = w[:backupIndexIncr]
	}
	return append(w, '}'), nil
}

func (item *KvEngineInc) MarshalJSON() ([]byte, error) {
	return item.WriteJSON(nil)
}

func (item *KvEngineInc) UnmarshalJSON(b []byte) error {
	if err := item.ReadJSON(true, &basictl.JsonLexer{Data: b}); err != nil {
		return ErrorInvalidJSON("kv_engine.inc", err.Error())
	}
	return nil
}
