// Copyright 2025 V Kontakte LLC
//
// This Source Code Form is subject to the terms of the Mozilla Public
// License, v. 2.0. If a copy of the MPL was not distributed with this
// file, You can obtain one at https://mozilla.org/MPL/2.0/.

// Code generated by vktl/cmd/tlgen2; DO NOT EDIT.
package internal

import (
	"github.com/VKCOM/statshouse/internal/vkgo/basictl"
)

var _ = basictl.NatWrite

type MetadataResetFloodResponse2 struct {
	BudgetBefore int32
	BudgetAfter  int32
}

func (MetadataResetFloodResponse2) TLName() string { return "metadata.resetFloodResponse2" }
func (MetadataResetFloodResponse2) TLTag() uint32  { return 0x9286abef }

func (item *MetadataResetFloodResponse2) Reset() {
	item.BudgetBefore = 0
	item.BudgetAfter = 0
}

func (item *MetadataResetFloodResponse2) FillRandom(rg *basictl.RandGenerator) {
	item.BudgetBefore = basictl.RandomInt(rg)
	item.BudgetAfter = basictl.RandomInt(rg)
}

func (item *MetadataResetFloodResponse2) Read(w []byte) (_ []byte, err error) {
	if w, err = basictl.IntRead(w, &item.BudgetBefore); err != nil {
		return w, err
	}
	return basictl.IntRead(w, &item.BudgetAfter)
}

func (item *MetadataResetFloodResponse2) WriteGeneral(w []byte) (_ []byte, err error) {
	return item.Write(w), nil
}

func (item *MetadataResetFloodResponse2) Write(w []byte) []byte {
	w = basictl.IntWrite(w, item.BudgetBefore)
	w = basictl.IntWrite(w, item.BudgetAfter)
	return w
}

func (item *MetadataResetFloodResponse2) ReadBoxed(w []byte) (_ []byte, err error) {
	if w, err = basictl.NatReadExactTag(w, 0x9286abef); err != nil {
		return w, err
	}
	return item.Read(w)
}

func (item *MetadataResetFloodResponse2) WriteBoxedGeneral(w []byte) (_ []byte, err error) {
	return item.WriteBoxed(w), nil
}

func (item *MetadataResetFloodResponse2) WriteBoxed(w []byte) []byte {
	w = basictl.NatWrite(w, 0x9286abef)
	return item.Write(w)
}

func (item MetadataResetFloodResponse2) String() string {
	return string(item.WriteJSON(nil))
}

func (item *MetadataResetFloodResponse2) ReadJSON(legacyTypeNames bool, in *basictl.JsonLexer) error {
	tctx := basictl.JSONReadContext{LegacyTypeNames: legacyTypeNames}
	return item.ReadJSONGeneral(&tctx, in)
}

func (item *MetadataResetFloodResponse2) ReadJSONGeneral(tctx *basictl.JSONReadContext, in *basictl.JsonLexer) error {
	var propBudgetBeforePresented bool
	var propBudgetAfterPresented bool

	if in != nil {
		in.Delim('{')
		if !in.Ok() {
			return in.Error()
		}
		for !in.IsDelim('}') {
			key := in.UnsafeFieldName(true)
			in.WantColon()
			switch key {
			case "budget_before":
				if propBudgetBeforePresented {
					return ErrorInvalidJSONWithDuplicatingKeys("metadata.resetFloodResponse2", "budget_before")
				}
				if err := Json2ReadInt32(in, &item.BudgetBefore); err != nil {
					return err
				}
				propBudgetBeforePresented = true
			case "budget_after":
				if propBudgetAfterPresented {
					return ErrorInvalidJSONWithDuplicatingKeys("metadata.resetFloodResponse2", "budget_after")
				}
				if err := Json2ReadInt32(in, &item.BudgetAfter); err != nil {
					return err
				}
				propBudgetAfterPresented = true
			default:
				return ErrorInvalidJSONExcessElement("metadata.resetFloodResponse2", key)
			}
			in.WantComma()
		}
		in.Delim('}')
		if !in.Ok() {
			return in.Error()
		}
	}
	if !propBudgetBeforePresented {
		item.BudgetBefore = 0
	}
	if !propBudgetAfterPresented {
		item.BudgetAfter = 0
	}
	return nil
}

// This method is general version of WriteJSON, use it instead!
func (item *MetadataResetFloodResponse2) WriteJSONGeneral(tctx *basictl.JSONWriteContext, w []byte) (_ []byte, err error) {
	return item.WriteJSONOpt(tctx, w), nil
}

func (item *MetadataResetFloodResponse2) WriteJSON(w []byte) []byte {
	tctx := basictl.JSONWriteContext{}
	return item.WriteJSONOpt(&tctx, w)
}
func (item *MetadataResetFloodResponse2) WriteJSONOpt(tctx *basictl.JSONWriteContext, w []byte) []byte {
	w = append(w, '{')
	backupIndexBudgetBefore := len(w)
	w = basictl.JSONAddCommaIfNeeded(w)
	w = append(w, `"budget_before":`...)
	w = basictl.JSONWriteInt32(w, item.BudgetBefore)
	if (item.BudgetBefore != 0) == false {
		w = w[:backupIndexBudgetBefore]
	}
	backupIndexBudgetAfter := len(w)
	w = basictl.JSONAddCommaIfNeeded(w)
	w = append(w, `"budget_after":`...)
	w = basictl.JSONWriteInt32(w, item.BudgetAfter)
	if (item.BudgetAfter != 0) == false {
		w = w[:backupIndexBudgetAfter]
	}
	return append(w, '}')
}

func (item *MetadataResetFloodResponse2) MarshalJSON() ([]byte, error) {
	return item.WriteJSON(nil), nil
}

func (item *MetadataResetFloodResponse2) UnmarshalJSON(b []byte) error {
	if err := item.ReadJSON(true, &basictl.JsonLexer{Data: b}); err != nil {
		return ErrorInvalidJSON("metadata.resetFloodResponse2", err.Error())
	}
	return nil
}

func (item *MetadataResetFloodResponse2) WriteTL2(w []byte, ctx *basictl.TL2WriteContext) []byte {
	return w
}

func (item *MetadataResetFloodResponse2) ReadTL2(r []byte, ctx *basictl.TL2ReadContext) (_ []byte, err error) {
	return r, ErrorTL2SerializersNotGenerated("metadata.resetFloodResponse2")
}
