// Copyright 2025 V Kontakte LLC
//
// This Source Code Form is subject to the terms of the Mozilla Public
// License, v. 2.0. If a copy of the MPL was not distributed with this
// file, You can obtain one at https://mozilla.org/MPL/2.0/.

// Code generated by vktl/cmd/tlgen2; DO NOT EDIT.
package internal

import (
	"github.com/VKCOM/statshouse/internal/vkgo/basictl"
)

var _ = basictl.NatWrite

type MetadataPutTagMappingBootstrap struct {
	FieldsMask uint32
	Mappings   []StatshouseMapping
}

func (MetadataPutTagMappingBootstrap) TLName() string { return "metadata.putTagMappingBootstrap" }
func (MetadataPutTagMappingBootstrap) TLTag() uint32  { return 0x5fc8ab9b }

func (item *MetadataPutTagMappingBootstrap) Reset() {
	item.FieldsMask = 0
	item.Mappings = item.Mappings[:0]
}

func (item *MetadataPutTagMappingBootstrap) Read(w []byte) (_ []byte, err error) {
	if w, err = basictl.NatRead(w, &item.FieldsMask); err != nil {
		return w, err
	}
	return BuiltinVectorStatshouseMappingRead(w, &item.Mappings)
}

func (item *MetadataPutTagMappingBootstrap) WriteGeneral(w []byte) (_ []byte, err error) {
	return item.Write(w), nil
}

func (item *MetadataPutTagMappingBootstrap) Write(w []byte) []byte {
	w = basictl.NatWrite(w, item.FieldsMask)
	w = BuiltinVectorStatshouseMappingWrite(w, item.Mappings)
	return w
}

func (item *MetadataPutTagMappingBootstrap) ReadBoxed(w []byte) (_ []byte, err error) {
	if w, err = basictl.NatReadExactTag(w, 0x5fc8ab9b); err != nil {
		return w, err
	}
	return item.Read(w)
}

func (item *MetadataPutTagMappingBootstrap) WriteBoxedGeneral(w []byte) (_ []byte, err error) {
	return item.WriteBoxed(w), nil
}

func (item *MetadataPutTagMappingBootstrap) WriteBoxed(w []byte) []byte {
	w = basictl.NatWrite(w, 0x5fc8ab9b)
	return item.Write(w)
}

func (item *MetadataPutTagMappingBootstrap) ReadResult(w []byte, ret *StatshousePutTagMappingBootstrapResult) (_ []byte, err error) {
	return ret.ReadBoxed(w)
}

func (item *MetadataPutTagMappingBootstrap) WriteResult(w []byte, ret StatshousePutTagMappingBootstrapResult) (_ []byte, err error) {
	w = ret.WriteBoxed(w)
	return w, nil
}

func (item *MetadataPutTagMappingBootstrap) ReadResultJSON(legacyTypeNames bool, in *basictl.JsonLexer, ret *StatshousePutTagMappingBootstrapResult) error {
	tctx := &basictl.JSONReadContext{LegacyTypeNames: legacyTypeNames}
	if err := ret.ReadJSONGeneral(tctx, in); err != nil {
		return err
	}
	return nil
}

func (item *MetadataPutTagMappingBootstrap) WriteResultJSON(w []byte, ret StatshousePutTagMappingBootstrapResult) (_ []byte, err error) {
	tctx := basictl.JSONWriteContext{}
	return item.writeResultJSON(&tctx, w, ret)
}

func (item *MetadataPutTagMappingBootstrap) writeResultJSON(tctx *basictl.JSONWriteContext, w []byte, ret StatshousePutTagMappingBootstrapResult) (_ []byte, err error) {
	w = ret.WriteJSONOpt(tctx, w)
	return w, nil
}

func (item *MetadataPutTagMappingBootstrap) ReadResultWriteResultJSON(tctx *basictl.JSONWriteContext, r []byte, w []byte) (_ []byte, _ []byte, err error) {
	var ret StatshousePutTagMappingBootstrapResult
	if r, err = item.ReadResult(r, &ret); err != nil {
		return r, w, err
	}
	w, err = item.writeResultJSON(tctx, w, ret)
	return r, w, err
}

func (item *MetadataPutTagMappingBootstrap) ReadResultJSONWriteResult(r []byte, w []byte) ([]byte, []byte, error) {
	var ret StatshousePutTagMappingBootstrapResult
	err := item.ReadResultJSON(true, &basictl.JsonLexer{Data: r}, &ret)
	if err != nil {
		return r, w, err
	}
	w, err = item.WriteResult(w, ret)
	return r, w, err
}

func (item MetadataPutTagMappingBootstrap) String() string {
	return string(item.WriteJSON(nil))
}

func (item *MetadataPutTagMappingBootstrap) ReadJSON(legacyTypeNames bool, in *basictl.JsonLexer) error {
	tctx := basictl.JSONReadContext{LegacyTypeNames: legacyTypeNames}
	return item.ReadJSONGeneral(&tctx, in)
}

func (item *MetadataPutTagMappingBootstrap) ReadJSONGeneral(tctx *basictl.JSONReadContext, in *basictl.JsonLexer) error {
	var propFieldsMaskPresented bool
	var propMappingsPresented bool

	if in != nil {
		in.Delim('{')
		if !in.Ok() {
			return in.Error()
		}
		for !in.IsDelim('}') {
			key := in.UnsafeFieldName(true)
			in.WantColon()
			switch key {
			case "fields_mask":
				if propFieldsMaskPresented {
					return ErrorInvalidJSONWithDuplicatingKeys("metadata.putTagMappingBootstrap", "fields_mask")
				}
				if err := Json2ReadUint32(in, &item.FieldsMask); err != nil {
					return err
				}
				propFieldsMaskPresented = true
			case "mappings":
				if propMappingsPresented {
					return ErrorInvalidJSONWithDuplicatingKeys("metadata.putTagMappingBootstrap", "mappings")
				}
				if err := BuiltinVectorStatshouseMappingReadJSONGeneral(tctx, in, &item.Mappings); err != nil {
					return err
				}
				propMappingsPresented = true
			default:
				return ErrorInvalidJSONExcessElement("metadata.putTagMappingBootstrap", key)
			}
			in.WantComma()
		}
		in.Delim('}')
		if !in.Ok() {
			return in.Error()
		}
	}
	if !propFieldsMaskPresented {
		item.FieldsMask = 0
	}
	if !propMappingsPresented {
		item.Mappings = item.Mappings[:0]
	}
	return nil
}

// This method is general version of WriteJSON, use it instead!
func (item *MetadataPutTagMappingBootstrap) WriteJSONGeneral(tctx *basictl.JSONWriteContext, w []byte) (_ []byte, err error) {
	return item.WriteJSONOpt(tctx, w), nil
}

func (item *MetadataPutTagMappingBootstrap) WriteJSON(w []byte) []byte {
	tctx := basictl.JSONWriteContext{}
	return item.WriteJSONOpt(&tctx, w)
}
func (item *MetadataPutTagMappingBootstrap) WriteJSONOpt(tctx *basictl.JSONWriteContext, w []byte) []byte {
	w = append(w, '{')
	backupIndexFieldsMask := len(w)
	w = basictl.JSONAddCommaIfNeeded(w)
	w = append(w, `"fields_mask":`...)
	w = basictl.JSONWriteUint32(w, item.FieldsMask)
	if (item.FieldsMask != 0) == false {
		w = w[:backupIndexFieldsMask]
	}
	backupIndexMappings := len(w)
	w = basictl.JSONAddCommaIfNeeded(w)
	w = append(w, `"mappings":`...)
	w = BuiltinVectorStatshouseMappingWriteJSONOpt(tctx, w, item.Mappings)
	if (len(item.Mappings) != 0) == false {
		w = w[:backupIndexMappings]
	}
	return append(w, '}')
}

func (item *MetadataPutTagMappingBootstrap) MarshalJSON() ([]byte, error) {
	return item.WriteJSON(nil), nil
}

func (item *MetadataPutTagMappingBootstrap) UnmarshalJSON(b []byte) error {
	if err := item.ReadJSON(true, &basictl.JsonLexer{Data: b}); err != nil {
		return ErrorInvalidJSON("metadata.putTagMappingBootstrap", err.Error())
	}
	return nil
}
