// Copyright 2025 V Kontakte LLC
//
// This Source Code Form is subject to the terms of the Mozilla Public
// License, v. 2.0. If a copy of the MPL was not distributed with this
// file, You can obtain one at https://mozilla.org/MPL/2.0/.

// Code generated by tl2gen; DO NOT EDIT.
package internal

import (
	"github.com/VKCOM/statshouse/internal/vkgo/basictl"
)

var _ = basictl.NatWrite

// deprecated
type MetadataEditMetricEvent struct {
	FieldsMask uint32
	Metric     MetadataMetricOld
	OldVersion int64
}

func (MetadataEditMetricEvent) TLName() string { return "metadata.editMetricEvent" }
func (MetadataEditMetricEvent) TLTag() uint32  { return 0x12345677 }

func (item *MetadataEditMetricEvent) Reset() {
	item.FieldsMask = 0
	item.Metric.Reset()
	item.OldVersion = 0
}

func (item *MetadataEditMetricEvent) FillRandom(rg *basictl.RandGenerator) {
	item.FieldsMask = basictl.RandomFieldMask(rg, 0b1100)
	item.Metric.FillRandom(rg, item.FieldsMask)
	item.OldVersion = basictl.RandomLong(rg)
}

func (item *MetadataEditMetricEvent) ReadTL1(w []byte) (_ []byte, err error) {
	if w, err = basictl.NatRead(w, &item.FieldsMask); err != nil {
		return w, err
	}
	if w, err = item.Metric.ReadTL1(w, item.FieldsMask); err != nil {
		return w, err
	}
	return basictl.LongRead(w, &item.OldVersion)
}

func (item *MetadataEditMetricEvent) WriteTL1General(w []byte) (_ []byte, err error) {
	return item.WriteTL1(w), nil
}

func (item *MetadataEditMetricEvent) WriteTL1(w []byte) []byte {
	w = basictl.NatWrite(w, item.FieldsMask)
	w = item.Metric.WriteTL1(w, item.FieldsMask)
	w = basictl.LongWrite(w, item.OldVersion)
	return w
}

func (item *MetadataEditMetricEvent) ReadTL1Boxed(w []byte) (_ []byte, err error) {
	if w, err = basictl.NatReadExactTag(w, 0x12345677); err != nil {
		return w, err
	}
	return item.ReadTL1(w)
}

func (item *MetadataEditMetricEvent) WriteTL1BoxedGeneral(w []byte) (_ []byte, err error) {
	return item.WriteTL1Boxed(w), nil
}

func (item *MetadataEditMetricEvent) WriteTL1Boxed(w []byte) []byte {
	w = basictl.NatWrite(w, 0x12345677)
	return item.WriteTL1(w)
}

func (item MetadataEditMetricEvent) String() string {
	return string(item.WriteJSON(nil))
}

func (item *MetadataEditMetricEvent) ReadJSON(legacyTypeNames bool, in *basictl.JsonLexer) error {
	tctx := basictl.JSONReadContext{LegacyTypeNames: legacyTypeNames}
	return item.ReadJSONGeneral(&tctx, in)
}

func (item *MetadataEditMetricEvent) ReadJSONGeneral(tctx *basictl.JSONReadContext, in *basictl.JsonLexer) error {
	var propFieldsMaskPresented bool
	var propMetricPresented bool
	var rawMetric []byte
	var propOldVersionPresented bool
	if in != nil {
		in.Delim('{')
		if !in.Ok() {
			return in.Error()
		}
		for !in.IsDelim('}') {
			key := in.UnsafeFieldName(true)
			in.WantColon()
			switch key {
			case "fields_mask":
				if propFieldsMaskPresented {
					return ErrorInvalidJSONWithDuplicatingKeys("metadata.editMetricEvent", "fields_mask")
				}
				propFieldsMaskPresented = true
				if err := Json2ReadUint32(in, &item.FieldsMask); err != nil {
					return err
				}
			case "metric":
				if propMetricPresented {
					return ErrorInvalidJSONWithDuplicatingKeys("metadata.editMetricEvent", "metric")
				}
				propMetricPresented = true
				rawMetric = in.Raw()
				if !in.Ok() {
					return in.Error()
				}
			case "old_version":
				if propOldVersionPresented {
					return ErrorInvalidJSONWithDuplicatingKeys("metadata.editMetricEvent", "old_version")
				}
				propOldVersionPresented = true
				if err := Json2ReadInt64(in, &item.OldVersion); err != nil {
					return err
				}
			default:
				return ErrorInvalidJSONExcessElement("metadata.editMetricEvent", key)
			}
			in.WantComma()
		}
		in.Delim('}')
		if !in.Ok() {
			return in.Error()
		}
	}
	if !propFieldsMaskPresented {
		item.FieldsMask = 0
	}
	if !propOldVersionPresented {
		item.OldVersion = 0
	}
	if propMetricPresented {
		inMetric := &basictl.JsonLexer{Data: rawMetric}
		if err := item.Metric.ReadJSONGeneral(tctx, inMetric, item.FieldsMask); err != nil {
			return err
		}
	}
	if !propMetricPresented {
		if err := item.Metric.ReadJSONGeneral(tctx, nil, item.FieldsMask); err != nil {
			return err
		}
	}
	return nil
}

// This method is general version of WriteJSON, use it instead!
func (item *MetadataEditMetricEvent) WriteJSONGeneral(tctx *basictl.JSONWriteContext, w []byte) (_ []byte, err error) {
	return item.WriteJSONOpt(tctx, w), nil
}

func (item *MetadataEditMetricEvent) WriteJSON(w []byte) []byte {
	tctx := basictl.JSONWriteContext{}
	return item.WriteJSONOpt(&tctx, w)
}
func (item *MetadataEditMetricEvent) WriteJSONOpt(tctx *basictl.JSONWriteContext, w []byte) []byte {
	w = append(w, '{')
	backupIndexFieldsMask := len(w)
	w = basictl.JSONAddCommaIfNeeded(w)
	w = append(w, `"fields_mask":`...)
	w = basictl.JSONWriteUint32(w, item.FieldsMask)
	if !(item.FieldsMask != 0) {
		w = w[:backupIndexFieldsMask]
	}
	w = basictl.JSONAddCommaIfNeeded(w)
	w = append(w, `"metric":`...)
	w = item.Metric.WriteJSONOpt(tctx, w, item.FieldsMask)
	backupIndexOldVersion := len(w)
	w = basictl.JSONAddCommaIfNeeded(w)
	w = append(w, `"old_version":`...)
	w = basictl.JSONWriteInt64(w, item.OldVersion)
	if !(item.OldVersion != 0) {
		w = w[:backupIndexOldVersion]
	}
	return append(w, '}')
}

func (item *MetadataEditMetricEvent) MarshalJSON() ([]byte, error) {
	return item.WriteJSON(nil), nil
}

func (item *MetadataEditMetricEvent) UnmarshalJSON(b []byte) error {
	if err := item.ReadJSON(true, &basictl.JsonLexer{Data: b}); err != nil {
		return ErrorInvalidJSON("metadata.editMetricEvent", err.Error())
	}
	return nil
}

func (item *MetadataEditMetricEvent) WriteTL2(w []byte, ctx *basictl.TL2WriteContext) []byte {
	panic(ErrorTL2SerializersNotGenerated("metadata.editMetricEvent"))
}

func (item *MetadataEditMetricEvent) ReadTL2(r []byte, ctx *basictl.TL2ReadContext) (_ []byte, err error) {
	return r, ErrorTL2SerializersNotGenerated("metadata.editMetricEvent")
}
