// Copyright 2023 V Kontakte LLC
//
// This Source Code Form is subject to the terms of the Mozilla Public
// License, v. 2.0. If a copy of the MPL was not distributed with this
// file, You can obtain one at https://mozilla.org/MPL/2.0/.

// Code generated by vktl/cmd/tlgen2; DO NOT EDIT.
package internal

import (
	"github.com/vkcom/statshouse/internal/vkgo/basictl"
)

var _ = basictl.NatWrite

type MetadataCreateEntityEvent struct {
	FieldsMask uint32
	Metric     MetadataEvent
}

func (MetadataCreateEntityEvent) TLName() string { return "metadata.createEntityEvent" }
func (MetadataCreateEntityEvent) TLTag() uint32  { return 0x1a345674 }

func (item *MetadataCreateEntityEvent) Reset() {
	item.FieldsMask = 0
	item.Metric.Reset()
}

func (item *MetadataCreateEntityEvent) Read(w []byte) (_ []byte, err error) {
	if w, err = basictl.NatRead(w, &item.FieldsMask); err != nil {
		return w, err
	}
	return item.Metric.Read(w)
}

// This method is general version of Write, use it instead!
func (item *MetadataCreateEntityEvent) WriteGeneral(w []byte) (_ []byte, err error) {
	return item.Write(w), nil
}

func (item *MetadataCreateEntityEvent) Write(w []byte) []byte {
	w = basictl.NatWrite(w, item.FieldsMask)
	w = item.Metric.Write(w)
	return w
}

func (item *MetadataCreateEntityEvent) ReadBoxed(w []byte) (_ []byte, err error) {
	if w, err = basictl.NatReadExactTag(w, 0x1a345674); err != nil {
		return w, err
	}
	return item.Read(w)
}

// This method is general version of WriteBoxed, use it instead!
func (item *MetadataCreateEntityEvent) WriteBoxedGeneral(w []byte) (_ []byte, err error) {
	return item.WriteBoxed(w), nil
}

func (item *MetadataCreateEntityEvent) WriteBoxed(w []byte) []byte {
	w = basictl.NatWrite(w, 0x1a345674)
	return item.Write(w)
}

func (item MetadataCreateEntityEvent) String() string {
	return string(item.WriteJSON(nil))
}

func (item *MetadataCreateEntityEvent) ReadJSON(legacyTypeNames bool, in *basictl.JsonLexer) error {
	var propFieldsMaskPresented bool
	var propMetricPresented bool

	if in != nil {
		in.Delim('{')
		if !in.Ok() {
			return in.Error()
		}
		for !in.IsDelim('}') {
			key := in.UnsafeFieldName(true)
			in.WantColon()
			switch key {
			case "fields_mask":
				if propFieldsMaskPresented {
					return ErrorInvalidJSONWithDuplicatingKeys("metadata.createEntityEvent", "fields_mask")
				}
				if err := Json2ReadUint32(in, &item.FieldsMask); err != nil {
					return err
				}
				propFieldsMaskPresented = true
			case "metric":
				if propMetricPresented {
					return ErrorInvalidJSONWithDuplicatingKeys("metadata.createEntityEvent", "metric")
				}
				if err := item.Metric.ReadJSON(legacyTypeNames, in); err != nil {
					return err
				}
				propMetricPresented = true
			default:
				return ErrorInvalidJSONExcessElement("metadata.createEntityEvent", key)
			}
			in.WantComma()
		}
		in.Delim('}')
		if !in.Ok() {
			return in.Error()
		}
	}
	if !propFieldsMaskPresented {
		item.FieldsMask = 0
	}
	if !propMetricPresented {
		item.Metric.Reset()
	}
	return nil
}

// This method is general version of WriteJSON, use it instead!
func (item *MetadataCreateEntityEvent) WriteJSONGeneral(w []byte) (_ []byte, err error) {
	return item.WriteJSONOpt(true, false, w), nil
}

func (item *MetadataCreateEntityEvent) WriteJSON(w []byte) []byte {
	return item.WriteJSONOpt(true, false, w)
}
func (item *MetadataCreateEntityEvent) WriteJSONOpt(newTypeNames bool, short bool, w []byte) []byte {
	w = append(w, '{')
	backupIndexFieldsMask := len(w)
	w = basictl.JSONAddCommaIfNeeded(w)
	w = append(w, `"fields_mask":`...)
	w = basictl.JSONWriteUint32(w, item.FieldsMask)
	if (item.FieldsMask != 0) == false {
		w = w[:backupIndexFieldsMask]
	}
	w = basictl.JSONAddCommaIfNeeded(w)
	w = append(w, `"metric":`...)
	w = item.Metric.WriteJSONOpt(newTypeNames, short, w)
	return append(w, '}')
}

func (item *MetadataCreateEntityEvent) MarshalJSON() ([]byte, error) {
	return item.WriteJSON(nil), nil
}

func (item *MetadataCreateEntityEvent) UnmarshalJSON(b []byte) error {
	if err := item.ReadJSON(true, &basictl.JsonLexer{Data: b}); err != nil {
		return ErrorInvalidJSON("metadata.createEntityEvent", err.Error())
	}
	return nil
}
