// Copyright 2023 V Kontakte LLC
//
// This Source Code Form is subject to the terms of the Mozilla Public
// License, v. 2.0. If a copy of the MPL was not distributed with this
// file, You can obtain one at https://mozilla.org/MPL/2.0/.

// Code generated by vktl/cmd/tlgen2; DO NOT EDIT.
package internal

import (
	"github.com/vkcom/statshouse/internal/vkgo/basictl"
)

var _ = basictl.NatWrite

type MetadataEditMetricEvent struct {
	FieldsMask uint32
	Metric     MetadataMetricOld
	OldVersion int64
}

func (MetadataEditMetricEvent) TLName() string { return "metadata.editMetricEvent" }
func (MetadataEditMetricEvent) TLTag() uint32  { return 0x12345677 }

func (item *MetadataEditMetricEvent) Reset() {
	item.FieldsMask = 0
	item.Metric.Reset()
	item.OldVersion = 0
}

func (item *MetadataEditMetricEvent) Read(w []byte) (_ []byte, err error) {
	if w, err = basictl.NatRead(w, &item.FieldsMask); err != nil {
		return w, err
	}
	if w, err = item.Metric.Read(w, item.FieldsMask); err != nil {
		return w, err
	}
	return basictl.LongRead(w, &item.OldVersion)
}

func (item *MetadataEditMetricEvent) Write(w []byte) (_ []byte, err error) {
	w = basictl.NatWrite(w, item.FieldsMask)
	if w, err = item.Metric.Write(w, item.FieldsMask); err != nil {
		return w, err
	}
	return basictl.LongWrite(w, item.OldVersion), nil
}

func (item *MetadataEditMetricEvent) ReadBoxed(w []byte) (_ []byte, err error) {
	if w, err = basictl.NatReadExactTag(w, 0x12345677); err != nil {
		return w, err
	}
	return item.Read(w)
}

func (item *MetadataEditMetricEvent) WriteBoxed(w []byte) ([]byte, error) {
	w = basictl.NatWrite(w, 0x12345677)
	return item.Write(w)
}

func (item MetadataEditMetricEvent) String() string {
	w, err := item.WriteJSON(nil)
	if err != nil {
		return err.Error()
	}
	return string(w)
}

func (item *MetadataEditMetricEvent) ReadJSON(legacyTypeNames bool, in *basictl.JsonLexer) error {
	var propFieldsMaskPresented bool
	var rawMetric []byte
	var propOldVersionPresented bool

	if in != nil {
		in.Delim('{')
		if !in.Ok() {
			return in.Error()
		}
		for !in.IsDelim('}') {
			key := in.UnsafeFieldName(true)
			in.WantColon()
			switch key {
			case "fields_mask":
				if propFieldsMaskPresented {
					return ErrorInvalidJSONWithDuplicatingKeys("metadata.editMetricEvent", "fields_mask")
				}
				if err := Json2ReadUint32(in, &item.FieldsMask); err != nil {
					return err
				}
				propFieldsMaskPresented = true
			case "metric":
				if rawMetric != nil {
					return ErrorInvalidJSONWithDuplicatingKeys("metadata.editMetricEvent", "metric")
				}
				rawMetric = in.Raw()
				if !in.Ok() {
					return in.Error()
				}
			case "old_version":
				if propOldVersionPresented {
					return ErrorInvalidJSONWithDuplicatingKeys("metadata.editMetricEvent", "old_version")
				}
				if err := Json2ReadInt64(in, &item.OldVersion); err != nil {
					return err
				}
				propOldVersionPresented = true
			default:
				return ErrorInvalidJSONExcessElement("metadata.editMetricEvent", key)
			}
			in.WantComma()
		}
		in.Delim('}')
		if !in.Ok() {
			return in.Error()
		}
	}
	if !propFieldsMaskPresented {
		item.FieldsMask = 0
	}
	if !propOldVersionPresented {
		item.OldVersion = 0
	}
	var inMetricPointer *basictl.JsonLexer
	inMetric := basictl.JsonLexer{Data: rawMetric}
	if rawMetric != nil {
		inMetricPointer = &inMetric
	}
	if err := item.Metric.ReadJSON(legacyTypeNames, inMetricPointer, item.FieldsMask); err != nil {
		return err
	}

	return nil
}

func (item *MetadataEditMetricEvent) WriteJSON(w []byte) (_ []byte, err error) {
	return item.WriteJSONOpt(true, false, w)
}
func (item *MetadataEditMetricEvent) WriteJSONOpt(newTypeNames bool, short bool, w []byte) (_ []byte, err error) {
	w = append(w, '{')
	backupIndexFieldsMask := len(w)
	w = basictl.JSONAddCommaIfNeeded(w)
	w = append(w, `"fields_mask":`...)
	w = basictl.JSONWriteUint32(w, item.FieldsMask)
	if (item.FieldsMask != 0) == false {
		w = w[:backupIndexFieldsMask]
	}
	w = basictl.JSONAddCommaIfNeeded(w)
	w = append(w, `"metric":`...)
	if w, err = item.Metric.WriteJSONOpt(newTypeNames, short, w, item.FieldsMask); err != nil {
		return w, err
	}
	backupIndexOldVersion := len(w)
	w = basictl.JSONAddCommaIfNeeded(w)
	w = append(w, `"old_version":`...)
	w = basictl.JSONWriteInt64(w, item.OldVersion)
	if (item.OldVersion != 0) == false {
		w = w[:backupIndexOldVersion]
	}
	return append(w, '}'), nil
}

func (item *MetadataEditMetricEvent) MarshalJSON() ([]byte, error) {
	return item.WriteJSON(nil)
}

func (item *MetadataEditMetricEvent) UnmarshalJSON(b []byte) error {
	if err := item.ReadJSON(true, &basictl.JsonLexer{Data: b}); err != nil {
		return ErrorInvalidJSON("metadata.editMetricEvent", err.Error())
	}
	return nil
}
