// Copyright 2023 V Kontakte LLC
//
// This Source Code Form is subject to the terms of the Mozilla Public
// License, v. 2.0. If a copy of the MPL was not distributed with this
// file, You can obtain one at https://mozilla.org/MPL/2.0/.

// Code generated by vktl/cmd/tlgen2; DO NOT EDIT.
package internal

import (
	"github.com/vkcom/statshouse/internal/vkgo/basictl"
)

var _ = basictl.NatWrite

type MetadataGetMapping struct {
	FieldMask uint32
	Metric    string
	Key       string
	// CreateIfAbsent (TrueType) // Conditional: item.FieldMask.1
}

func (MetadataGetMapping) TLName() string { return "metadata.getMapping" }
func (MetadataGetMapping) TLTag() uint32  { return 0x9dfa7a83 }

func (item *MetadataGetMapping) SetCreateIfAbsent(v bool) {
	if v {
		item.FieldMask |= 1 << 1
	} else {
		item.FieldMask &^= 1 << 1
	}
}
func (item MetadataGetMapping) IsSetCreateIfAbsent() bool { return item.FieldMask&(1<<1) != 0 }

func (item *MetadataGetMapping) Reset() {
	item.FieldMask = 0
	item.Metric = ""
	item.Key = ""
}

func (item *MetadataGetMapping) Read(w []byte) (_ []byte, err error) {
	if w, err = basictl.NatRead(w, &item.FieldMask); err != nil {
		return w, err
	}
	if w, err = basictl.StringRead(w, &item.Metric); err != nil {
		return w, err
	}
	if w, err = basictl.StringRead(w, &item.Key); err != nil {
		return w, err
	}
	return w, nil
}

func (item *MetadataGetMapping) Write(w []byte) (_ []byte, err error) {
	w = basictl.NatWrite(w, item.FieldMask)
	if w, err = basictl.StringWrite(w, item.Metric); err != nil {
		return w, err
	}
	if w, err = basictl.StringWrite(w, item.Key); err != nil {
		return w, err
	}
	return w, nil
}

func (item *MetadataGetMapping) ReadBoxed(w []byte) (_ []byte, err error) {
	if w, err = basictl.NatReadExactTag(w, 0x9dfa7a83); err != nil {
		return w, err
	}
	return item.Read(w)
}

func (item *MetadataGetMapping) WriteBoxed(w []byte) ([]byte, error) {
	w = basictl.NatWrite(w, 0x9dfa7a83)
	return item.Write(w)
}

func (item *MetadataGetMapping) ReadResult(w []byte, ret *MetadataGetMappingResponseUnion) (_ []byte, err error) {
	return ret.ReadBoxed(w, item.FieldMask)
}

func (item *MetadataGetMapping) WriteResult(w []byte, ret MetadataGetMappingResponseUnion) (_ []byte, err error) {
	return ret.WriteBoxed(w, item.FieldMask)
}

func (item *MetadataGetMapping) ReadResultJSON(j interface{}, ret *MetadataGetMappingResponseUnion) error {
	if err := MetadataGetMappingResponseUnion__ReadJSON(ret, j, item.FieldMask); err != nil {
		return err
	}
	return nil
}

func (item *MetadataGetMapping) WriteResultJSON(w []byte, ret MetadataGetMappingResponseUnion) (_ []byte, err error) {
	if w, err = ret.WriteJSON(w, item.FieldMask); err != nil {
		return w, err
	}
	return w, nil
}

func (item *MetadataGetMapping) ReadResultWriteResultJSON(r []byte, w []byte) (_ []byte, _ []byte, err error) {
	var ret MetadataGetMappingResponseUnion
	if r, err = item.ReadResult(r, &ret); err != nil {
		return r, w, err
	}
	w, err = item.WriteResultJSON(w, ret)
	return r, w, err
}

func (item *MetadataGetMapping) ReadResultJSONWriteResult(r []byte, w []byte) ([]byte, []byte, error) {
	j, err := JsonBytesToInterface(r)
	if err != nil {
		return r, w, ErrorInvalidJSON("metadata.getMapping", err.Error())
	}
	var ret MetadataGetMappingResponseUnion
	if err = item.ReadResultJSON(j, &ret); err != nil {
		return r, w, err
	}
	w, err = item.WriteResult(w, ret)
	return r, w, err
}

func (item MetadataGetMapping) String() string {
	w, err := item.WriteJSON(nil)
	if err != nil {
		return err.Error()
	}
	return string(w)
}

func MetadataGetMapping__ReadJSON(item *MetadataGetMapping, j interface{}) error {
	return item.readJSON(j)
}
func (item *MetadataGetMapping) readJSON(j interface{}) error {
	_jm, _ok := j.(map[string]interface{})
	if j != nil && !_ok {
		return ErrorInvalidJSON("metadata.getMapping", "expected json object")
	}
	_jFieldMask := _jm["field_mask"]
	delete(_jm, "field_mask")
	if err := JsonReadUint32(_jFieldMask, &item.FieldMask); err != nil {
		return err
	}
	_jMetric := _jm["metric"]
	delete(_jm, "metric")
	if err := JsonReadString(_jMetric, &item.Metric); err != nil {
		return err
	}
	_jKey := _jm["key"]
	delete(_jm, "key")
	if err := JsonReadString(_jKey, &item.Key); err != nil {
		return err
	}
	_jCreateIfAbsent := _jm["createIfAbsent"]
	delete(_jm, "createIfAbsent")
	for k := range _jm {
		return ErrorInvalidJSONExcessElement("metadata.getMapping", k)
	}
	if _jCreateIfAbsent != nil {
		_bit := false
		if err := JsonReadBool(_jCreateIfAbsent, &_bit); err != nil {
			return err
		}
		if _bit {
			item.FieldMask |= 1 << 1
		} else {
			item.FieldMask &^= 1 << 1
		}
	}
	return nil
}

func (item *MetadataGetMapping) WriteJSON(w []byte) (_ []byte, err error) {
	w = append(w, '{')
	if item.FieldMask != 0 {
		w = basictl.JSONAddCommaIfNeeded(w)
		w = append(w, `"field_mask":`...)
		w = basictl.JSONWriteUint32(w, item.FieldMask)
	}
	if len(item.Metric) != 0 {
		w = basictl.JSONAddCommaIfNeeded(w)
		w = append(w, `"metric":`...)
		w = basictl.JSONWriteString(w, item.Metric)
	}
	if len(item.Key) != 0 {
		w = basictl.JSONAddCommaIfNeeded(w)
		w = append(w, `"key":`...)
		w = basictl.JSONWriteString(w, item.Key)
	}
	if item.FieldMask&(1<<1) != 0 {
		w = basictl.JSONAddCommaIfNeeded(w)
		w = append(w, `"createIfAbsent":true`...)
	}
	return append(w, '}'), nil
}

func (item *MetadataGetMapping) MarshalJSON() ([]byte, error) {
	return item.WriteJSON(nil)
}

func (item *MetadataGetMapping) UnmarshalJSON(b []byte) error {
	j, err := JsonBytesToInterface(b)
	if err != nil {
		return ErrorInvalidJSON("metadata.getMapping", err.Error())
	}
	if err = item.readJSON(j); err != nil {
		return ErrorInvalidJSON("metadata.getMapping", err.Error())
	}
	return nil
}
