// Copyright 2025 V Kontakte LLC
//
// This Source Code Form is subject to the terms of the Mozilla Public
// License, v. 2.0. If a copy of the MPL was not distributed with this
// file, You can obtain one at https://mozilla.org/MPL/2.0/.

// Code generated by tl2gen; DO NOT EDIT.
package internal

import (
	"github.com/VKCOM/statshouse/internal/vkgo/basictl"
)

var _ = basictl.NatWrite

type StatshouseGetTargetsResult struct {
	Targets      []StatshousePromTarget
	Hash         string
	GaugeMetrics []string // Conditional: nat_fields_mask.0
}

func (StatshouseGetTargetsResult) TLName() string { return "statshouse.getTargetsResult" }
func (StatshouseGetTargetsResult) TLTag() uint32  { return 0x51ac86df }

func (item *StatshouseGetTargetsResult) SetGaugeMetrics(v []string, nat_fields_mask *uint32) {
	item.GaugeMetrics = v
	if nat_fields_mask != nil {
		*nat_fields_mask |= 1 << 0
	}
}
func (item *StatshouseGetTargetsResult) ClearGaugeMetrics(nat_fields_mask *uint32) {
	item.GaugeMetrics = item.GaugeMetrics[:0]
	if nat_fields_mask != nil {
		*nat_fields_mask &^= 1 << 0
	}
}
func (item *StatshouseGetTargetsResult) IsSetGaugeMetrics(nat_fields_mask uint32) bool {
	return nat_fields_mask&(1<<0) != 0
}

func (item *StatshouseGetTargetsResult) Reset() {
	item.Targets = item.Targets[:0]
	item.Hash = ""
	item.GaugeMetrics = item.GaugeMetrics[:0]
}

func (item *StatshouseGetTargetsResult) FillRandom(rg *basictl.RandGenerator, nat_fields_mask uint32) {
	BuiltinVectorStatshousePromTargetFillRandom(rg, &item.Targets, nat_fields_mask)
	item.Hash = basictl.RandomString(rg)
	if nat_fields_mask&(1<<0) != 0 {
		BuiltinVectorStringFillRandom(rg, &item.GaugeMetrics)
	} else {
		item.GaugeMetrics = item.GaugeMetrics[:0]
	}
}

func (item *StatshouseGetTargetsResult) ReadTL1(w []byte, nat_fields_mask uint32) (_ []byte, err error) {
	if w, err = BuiltinVectorStatshousePromTargetReadTL1(w, &item.Targets, nat_fields_mask); err != nil {
		return w, err
	}
	if w, err = basictl.StringRead(w, &item.Hash); err != nil {
		return w, err
	}
	if nat_fields_mask&(1<<0) != 0 {
		if w, err = BuiltinVectorStringReadTL1(w, &item.GaugeMetrics); err != nil {
			return w, err
		}
	} else {
		item.GaugeMetrics = item.GaugeMetrics[:0]
	}
	return w, nil
}

func (item *StatshouseGetTargetsResult) WriteTL1(w []byte, nat_fields_mask uint32) []byte {
	w = BuiltinVectorStatshousePromTargetWriteTL1(w, item.Targets, nat_fields_mask)
	w = basictl.StringWrite(w, item.Hash)
	if nat_fields_mask&(1<<0) != 0 {
		w = BuiltinVectorStringWriteTL1(w, item.GaugeMetrics)
	}
	return w
}

func (item *StatshouseGetTargetsResult) ReadTL1Boxed(w []byte, nat_fields_mask uint32) (_ []byte, err error) {
	if w, err = basictl.NatReadExactTag(w, 0x51ac86df); err != nil {
		return w, err
	}
	return item.ReadTL1(w, nat_fields_mask)
}

func (item *StatshouseGetTargetsResult) WriteTL1Boxed(w []byte, nat_fields_mask uint32) []byte {
	w = basictl.NatWrite(w, 0x51ac86df)
	return item.WriteTL1(w, nat_fields_mask)
}

func (item *StatshouseGetTargetsResult) ReadJSONGeneral(tctx *basictl.JSONReadContext, in *basictl.JsonLexer, nat_fields_mask uint32) error {
	var propTargetsPresented bool
	var propHashPresented bool
	var propGaugeMetricsPresented bool
	if in != nil {
		in.Delim('{')
		if !in.Ok() {
			return in.Error()
		}
		for !in.IsDelim('}') {
			key := in.UnsafeFieldName(true)
			in.WantColon()
			switch key {
			case "targets":
				if propTargetsPresented {
					return ErrorInvalidJSONWithDuplicatingKeys("statshouse.getTargetsResult", "targets")
				}
				propTargetsPresented = true
				if err := BuiltinVectorStatshousePromTargetReadJSONGeneral(tctx, in, &item.Targets, nat_fields_mask); err != nil {
					return err
				}
			case "hash":
				if propHashPresented {
					return ErrorInvalidJSONWithDuplicatingKeys("statshouse.getTargetsResult", "hash")
				}
				propHashPresented = true
				if err := Json2ReadString(in, &item.Hash); err != nil {
					return err
				}
			case "gauge_metrics":
				if propGaugeMetricsPresented {
					return ErrorInvalidJSONWithDuplicatingKeys("statshouse.getTargetsResult", "gauge_metrics")
				}
				propGaugeMetricsPresented = true
				if err := BuiltinVectorStringReadJSONGeneral(tctx, in, &item.GaugeMetrics); err != nil {
					return err
				}
			default:
				return ErrorInvalidJSONExcessElement("statshouse.getTargetsResult", key)
			}
			in.WantComma()
		}
		in.Delim('}')
		if !in.Ok() {
			return in.Error()
		}
	}
	if !propHashPresented {
		item.Hash = ""
	}
	if !propGaugeMetricsPresented {
		item.GaugeMetrics = item.GaugeMetrics[:0]
	}
	if propGaugeMetricsPresented {
		if nat_fields_mask&(1<<0) == 0 {
			return ErrorInvalidJSON("statshouse.getTargetsResult", "field 'gauge_metrics' is set, but will be ignored, because corresponding fieldmask nat_fields_mask bit 0 is 0")
		}
	}
	if !propTargetsPresented {
		if err := BuiltinVectorStatshousePromTargetReadJSONGeneral(tctx, nil, &item.Targets, nat_fields_mask); err != nil {
			return err
		}
	}
	return nil
}

// This method is general version of WriteJSON, use it instead!
func (item *StatshouseGetTargetsResult) WriteJSONGeneral(tctx *basictl.JSONWriteContext, w []byte, nat_fields_mask uint32) (_ []byte, err error) {
	return item.WriteJSONOpt(tctx, w, nat_fields_mask), nil
}

func (item *StatshouseGetTargetsResult) WriteJSON(w []byte, nat_fields_mask uint32) []byte {
	tctx := basictl.JSONWriteContext{}
	return item.WriteJSONOpt(&tctx, w, nat_fields_mask)
}
func (item *StatshouseGetTargetsResult) WriteJSONOpt(tctx *basictl.JSONWriteContext, w []byte, nat_fields_mask uint32) []byte {
	w = append(w, '{')
	backupIndexTargets := len(w)
	w = basictl.JSONAddCommaIfNeeded(w)
	w = append(w, `"targets":`...)
	w = BuiltinVectorStatshousePromTargetWriteJSONOpt(tctx, w, item.Targets, nat_fields_mask)
	if !(len(item.Targets) != 0) {
		w = w[:backupIndexTargets]
	}
	backupIndexHash := len(w)
	w = basictl.JSONAddCommaIfNeeded(w)
	w = append(w, `"hash":`...)
	w = basictl.JSONWriteString(w, item.Hash)
	if !(len(item.Hash) != 0) {
		w = w[:backupIndexHash]
	}
	if nat_fields_mask&(1<<0) != 0 {
		w = basictl.JSONAddCommaIfNeeded(w)
		w = append(w, `"gauge_metrics":`...)
		w = BuiltinVectorStringWriteJSONOpt(tctx, w, item.GaugeMetrics)
	}
	return append(w, '}')
}

func (item *StatshouseGetTargetsResult) WriteTL2(w []byte, ctx *basictl.TL2WriteContext) []byte {
	panic(ErrorTL2SerializersNotGenerated("statshouse.getTargetsResult"))
}

func (item *StatshouseGetTargetsResult) ReadTL2(r []byte, ctx *basictl.TL2ReadContext) (_ []byte, err error) {
	return r, ErrorTL2SerializersNotGenerated("statshouse.getTargetsResult")
}

type StatshouseGetTargetsResultBytes struct {
	Targets      []StatshousePromTargetBytes
	Hash         []byte
	GaugeMetrics [][]byte // Conditional: nat_fields_mask.0
}

func (StatshouseGetTargetsResultBytes) TLName() string { return "statshouse.getTargetsResult" }
func (StatshouseGetTargetsResultBytes) TLTag() uint32  { return 0x51ac86df }

func (item *StatshouseGetTargetsResultBytes) SetGaugeMetrics(v [][]byte, nat_fields_mask *uint32) {
	item.GaugeMetrics = v
	if nat_fields_mask != nil {
		*nat_fields_mask |= 1 << 0
	}
}
func (item *StatshouseGetTargetsResultBytes) ClearGaugeMetrics(nat_fields_mask *uint32) {
	item.GaugeMetrics = item.GaugeMetrics[:0]
	if nat_fields_mask != nil {
		*nat_fields_mask &^= 1 << 0
	}
}
func (item *StatshouseGetTargetsResultBytes) IsSetGaugeMetrics(nat_fields_mask uint32) bool {
	return nat_fields_mask&(1<<0) != 0
}

func (item *StatshouseGetTargetsResultBytes) Reset() {
	item.Targets = item.Targets[:0]
	item.Hash = item.Hash[:0]
	item.GaugeMetrics = item.GaugeMetrics[:0]
}

func (item *StatshouseGetTargetsResultBytes) FillRandom(rg *basictl.RandGenerator, nat_fields_mask uint32) {
	BuiltinVectorStatshousePromTargetBytesFillRandom(rg, &item.Targets, nat_fields_mask)
	item.Hash = basictl.RandomStringBytes(rg)
	if nat_fields_mask&(1<<0) != 0 {
		BuiltinVectorStringBytesFillRandom(rg, &item.GaugeMetrics)
	} else {
		item.GaugeMetrics = item.GaugeMetrics[:0]
	}
}

func (item *StatshouseGetTargetsResultBytes) ReadTL1(w []byte, nat_fields_mask uint32) (_ []byte, err error) {
	if w, err = BuiltinVectorStatshousePromTargetBytesReadTL1(w, &item.Targets, nat_fields_mask); err != nil {
		return w, err
	}
	if w, err = basictl.StringReadBytes(w, &item.Hash); err != nil {
		return w, err
	}
	if nat_fields_mask&(1<<0) != 0 {
		if w, err = BuiltinVectorStringBytesReadTL1(w, &item.GaugeMetrics); err != nil {
			return w, err
		}
	} else {
		item.GaugeMetrics = item.GaugeMetrics[:0]
	}
	return w, nil
}

func (item *StatshouseGetTargetsResultBytes) WriteTL1(w []byte, nat_fields_mask uint32) []byte {
	w = BuiltinVectorStatshousePromTargetBytesWriteTL1(w, item.Targets, nat_fields_mask)
	w = basictl.StringWriteBytes(w, item.Hash)
	if nat_fields_mask&(1<<0) != 0 {
		w = BuiltinVectorStringBytesWriteTL1(w, item.GaugeMetrics)
	}
	return w
}

func (item *StatshouseGetTargetsResultBytes) ReadTL1Boxed(w []byte, nat_fields_mask uint32) (_ []byte, err error) {
	if w, err = basictl.NatReadExactTag(w, 0x51ac86df); err != nil {
		return w, err
	}
	return item.ReadTL1(w, nat_fields_mask)
}

func (item *StatshouseGetTargetsResultBytes) WriteTL1Boxed(w []byte, nat_fields_mask uint32) []byte {
	w = basictl.NatWrite(w, 0x51ac86df)
	return item.WriteTL1(w, nat_fields_mask)
}

func (item *StatshouseGetTargetsResultBytes) ReadJSONGeneral(tctx *basictl.JSONReadContext, in *basictl.JsonLexer, nat_fields_mask uint32) error {
	var propTargetsPresented bool
	var propHashPresented bool
	var propGaugeMetricsPresented bool
	if in != nil {
		in.Delim('{')
		if !in.Ok() {
			return in.Error()
		}
		for !in.IsDelim('}') {
			key := in.UnsafeFieldName(true)
			in.WantColon()
			switch key {
			case "targets":
				if propTargetsPresented {
					return ErrorInvalidJSONWithDuplicatingKeys("statshouse.getTargetsResult", "targets")
				}
				propTargetsPresented = true
				if err := BuiltinVectorStatshousePromTargetBytesReadJSONGeneral(tctx, in, &item.Targets, nat_fields_mask); err != nil {
					return err
				}
			case "hash":
				if propHashPresented {
					return ErrorInvalidJSONWithDuplicatingKeys("statshouse.getTargetsResult", "hash")
				}
				propHashPresented = true
				if err := Json2ReadStringBytes(in, &item.Hash); err != nil {
					return err
				}
			case "gauge_metrics":
				if propGaugeMetricsPresented {
					return ErrorInvalidJSONWithDuplicatingKeys("statshouse.getTargetsResult", "gauge_metrics")
				}
				propGaugeMetricsPresented = true
				if err := BuiltinVectorStringBytesReadJSONGeneral(tctx, in, &item.GaugeMetrics); err != nil {
					return err
				}
			default:
				return ErrorInvalidJSONExcessElement("statshouse.getTargetsResult", key)
			}
			in.WantComma()
		}
		in.Delim('}')
		if !in.Ok() {
			return in.Error()
		}
	}
	if !propHashPresented {
		item.Hash = item.Hash[:0]
	}
	if !propGaugeMetricsPresented {
		item.GaugeMetrics = item.GaugeMetrics[:0]
	}
	if propGaugeMetricsPresented {
		if nat_fields_mask&(1<<0) == 0 {
			return ErrorInvalidJSON("statshouse.getTargetsResult", "field 'gauge_metrics' is set, but will be ignored, because corresponding fieldmask nat_fields_mask bit 0 is 0")
		}
	}
	if !propTargetsPresented {
		if err := BuiltinVectorStatshousePromTargetBytesReadJSONGeneral(tctx, nil, &item.Targets, nat_fields_mask); err != nil {
			return err
		}
	}
	return nil
}

// This method is general version of WriteJSON, use it instead!
func (item *StatshouseGetTargetsResultBytes) WriteJSONGeneral(tctx *basictl.JSONWriteContext, w []byte, nat_fields_mask uint32) (_ []byte, err error) {
	return item.WriteJSONOpt(tctx, w, nat_fields_mask), nil
}

func (item *StatshouseGetTargetsResultBytes) WriteJSON(w []byte, nat_fields_mask uint32) []byte {
	tctx := basictl.JSONWriteContext{}
	return item.WriteJSONOpt(&tctx, w, nat_fields_mask)
}
func (item *StatshouseGetTargetsResultBytes) WriteJSONOpt(tctx *basictl.JSONWriteContext, w []byte, nat_fields_mask uint32) []byte {
	w = append(w, '{')
	backupIndexTargets := len(w)
	w = basictl.JSONAddCommaIfNeeded(w)
	w = append(w, `"targets":`...)
	w = BuiltinVectorStatshousePromTargetBytesWriteJSONOpt(tctx, w, item.Targets, nat_fields_mask)
	if !(len(item.Targets) != 0) {
		w = w[:backupIndexTargets]
	}
	backupIndexHash := len(w)
	w = basictl.JSONAddCommaIfNeeded(w)
	w = append(w, `"hash":`...)
	w = basictl.JSONWriteStringBytes(w, item.Hash)
	if !(len(item.Hash) != 0) {
		w = w[:backupIndexHash]
	}
	if nat_fields_mask&(1<<0) != 0 {
		w = basictl.JSONAddCommaIfNeeded(w)
		w = append(w, `"gauge_metrics":`...)
		w = BuiltinVectorStringBytesWriteJSONOpt(tctx, w, item.GaugeMetrics)
	}
	return append(w, '}')
}

func (item *StatshouseGetTargetsResultBytes) WriteTL2(w []byte, ctx *basictl.TL2WriteContext) []byte {
	panic(ErrorTL2SerializersNotGenerated("statshouse.getTargetsResult"))
}

func (item *StatshouseGetTargetsResultBytes) ReadTL2(r []byte, ctx *basictl.TL2ReadContext) (_ []byte, err error) {
	return r, ErrorTL2SerializersNotGenerated("statshouse.getTargetsResult")
}
