// Copyright 2025 V Kontakte LLC
//
// This Source Code Form is subject to the terms of the Mozilla Public
// License, v. 2.0. If a copy of the MPL was not distributed with this
// file, You can obtain one at https://mozilla.org/MPL/2.0/.

// Code generated by tl2gen; DO NOT EDIT.
package internal

import (
	"github.com/VKCOM/statshouse/internal/vkgo/basictl"
)

var _ = basictl.NatWrite

// when local cache is empty, statshouse will ask aggregator for common mappings
type StatshouseGetTagMappingBootstrap struct {
	FieldsMask uint32
	Header     StatshouseCommonProxyHeader
}

func (StatshouseGetTagMappingBootstrap) TLName() string { return "statshouse.getTagMappingBootstrap" }
func (StatshouseGetTagMappingBootstrap) TLTag() uint32  { return 0x75a7f68e }

func (item *StatshouseGetTagMappingBootstrap) Reset() {
	item.FieldsMask = 0
	item.Header.Reset()
}

func (item *StatshouseGetTagMappingBootstrap) FillRandom(rg *basictl.RandGenerator) {
	item.FieldsMask = basictl.RandomFieldMask(rg, 0b11110000000000000000000000000000)
	item.Header.FillRandom(rg, item.FieldsMask)
}

func (item *StatshouseGetTagMappingBootstrap) ReadTL1(w []byte) (_ []byte, err error) {
	if w, err = basictl.NatRead(w, &item.FieldsMask); err != nil {
		return w, err
	}
	return item.Header.ReadTL1(w, item.FieldsMask)
}

func (item *StatshouseGetTagMappingBootstrap) WriteTL1General(w []byte) (_ []byte, err error) {
	return item.WriteTL1(w), nil
}

func (item *StatshouseGetTagMappingBootstrap) WriteTL1(w []byte) []byte {
	w = basictl.NatWrite(w, item.FieldsMask)
	w = item.Header.WriteTL1(w, item.FieldsMask)
	return w
}

func (item *StatshouseGetTagMappingBootstrap) ReadTL1Boxed(w []byte) (_ []byte, err error) {
	if w, err = basictl.NatReadExactTag(w, 0x75a7f68e); err != nil {
		return w, err
	}
	return item.ReadTL1(w)
}

func (item *StatshouseGetTagMappingBootstrap) WriteTL1BoxedGeneral(w []byte) (_ []byte, err error) {
	return item.WriteTL1Boxed(w), nil
}

func (item *StatshouseGetTagMappingBootstrap) WriteTL1Boxed(w []byte) []byte {
	w = basictl.NatWrite(w, 0x75a7f68e)
	return item.WriteTL1(w)
}

func (item *StatshouseGetTagMappingBootstrap) ReadResultTL1(w []byte, ret *StatshouseGetTagMappingBootstrapResult) (_ []byte, err error) {
	return ret.ReadTL1Boxed(w)
}

func (item *StatshouseGetTagMappingBootstrap) WriteResultTL1(w []byte, ret StatshouseGetTagMappingBootstrapResult) (_ []byte, err error) {
	w = ret.WriteTL1Boxed(w)
	return w, nil
}

func (item *StatshouseGetTagMappingBootstrap) ReadResultJSON(legacyTypeNames bool, in *basictl.JsonLexer, ret *StatshouseGetTagMappingBootstrapResult) error {
	tctx := &basictl.JSONReadContext{LegacyTypeNames: legacyTypeNames}
	if err := ret.ReadJSONGeneral(tctx, in); err != nil {
		return err
	}
	return nil
}

func (item *StatshouseGetTagMappingBootstrap) WriteResultJSON(w []byte, ret StatshouseGetTagMappingBootstrapResult) (_ []byte, err error) {
	tctx := basictl.JSONWriteContext{}
	return item.writeResultJSON(&tctx, w, ret)
}

func (item *StatshouseGetTagMappingBootstrap) writeResultJSON(tctx *basictl.JSONWriteContext, w []byte, ret StatshouseGetTagMappingBootstrapResult) (_ []byte, err error) {
	w = ret.WriteJSONOpt(tctx, w)
	return w, nil
}

func (item *StatshouseGetTagMappingBootstrap) FillRandomResultTL1(rg *basictl.RandGenerator, w []byte) ([]byte, error) {
	var ret StatshouseGetTagMappingBootstrapResult
	ret.FillRandom(rg)
	return item.WriteResultTL1(w, ret)
}

func (item *StatshouseGetTagMappingBootstrap) ReadResultTL1WriteResultJSON(tctx *basictl.JSONWriteContext, r []byte, w []byte) (_ []byte, _ []byte, err error) {
	var ret StatshouseGetTagMappingBootstrapResult
	if r, err = item.ReadResultTL1(r, &ret); err != nil {
		return r, w, err
	}
	w, err = item.writeResultJSON(tctx, w, ret)
	return r, w, err
}

func (item *StatshouseGetTagMappingBootstrap) ReadResultJSONWriteResultTL1(r []byte, w []byte) (_ []byte, _ []byte, err error) {
	var ret StatshouseGetTagMappingBootstrapResult
	if err = item.ReadResultJSON(true, &basictl.JsonLexer{Data: r}, &ret); err != nil {
		return r, w, err
	}
	w, err = item.WriteResultTL1(w, ret)
	return r, w, err
}

func (item *StatshouseGetTagMappingBootstrap) ReadResultTL1WriteResultTL2(tctx *basictl.TL2WriteContext, r []byte, w []byte) (_ []byte, _ []byte, err error) {
	return r, w, ErrorTL2SerializersNotGenerated("statshouse.getTagMappingBootstrap")
}

func (item *StatshouseGetTagMappingBootstrap) ReadResultTL2WriteResultTL1(tctx *basictl.TL2ReadContext, r []byte, w []byte) (_ []byte, _ []byte, err error) {
	return r, w, ErrorTL2SerializersNotGenerated("statshouse.getTagMappingBootstrap")
}

func (item *StatshouseGetTagMappingBootstrap) ReadResultTL2WriteResultJSON(tctx *basictl.TL2ReadContext, jctx *basictl.JSONWriteContext, r []byte, w []byte) (_ []byte, _ []byte, err error) {
	return r, w, ErrorTL2SerializersNotGenerated("statshouse.getTagMappingBootstrap")
}

func (item *StatshouseGetTagMappingBootstrap) ReadResultJSONWriteResultTL2(tctx *basictl.TL2WriteContext, r []byte, w []byte) (_ []byte, _ []byte, err error) {
	return r, w, ErrorTL2SerializersNotGenerated("statshouse.getTagMappingBootstrap")
}

func (item StatshouseGetTagMappingBootstrap) String() string {
	return string(item.WriteJSON(nil))
}

func (item *StatshouseGetTagMappingBootstrap) ReadJSON(legacyTypeNames bool, in *basictl.JsonLexer) error {
	tctx := basictl.JSONReadContext{LegacyTypeNames: legacyTypeNames}
	return item.ReadJSONGeneral(&tctx, in)
}

func (item *StatshouseGetTagMappingBootstrap) ReadJSONGeneral(tctx *basictl.JSONReadContext, in *basictl.JsonLexer) error {
	var propFieldsMaskPresented bool
	var propHeaderPresented bool
	var rawHeader []byte
	if in != nil {
		in.Delim('{')
		if !in.Ok() {
			return in.Error()
		}
		for !in.IsDelim('}') {
			key := in.UnsafeFieldName(true)
			in.WantColon()
			switch key {
			case "fields_mask":
				if propFieldsMaskPresented {
					return ErrorInvalidJSONWithDuplicatingKeys("statshouse.getTagMappingBootstrap", "fields_mask")
				}
				propFieldsMaskPresented = true
				if err := Json2ReadUint32(in, &item.FieldsMask); err != nil {
					return err
				}
			case "header":
				if propHeaderPresented {
					return ErrorInvalidJSONWithDuplicatingKeys("statshouse.getTagMappingBootstrap", "header")
				}
				propHeaderPresented = true
				rawHeader = in.Raw()
				if !in.Ok() {
					return in.Error()
				}
			default:
				return ErrorInvalidJSONExcessElement("statshouse.getTagMappingBootstrap", key)
			}
			in.WantComma()
		}
		in.Delim('}')
		if !in.Ok() {
			return in.Error()
		}
	}
	if !propFieldsMaskPresented {
		item.FieldsMask = 0
	}
	if propHeaderPresented {
		inHeader := &basictl.JsonLexer{Data: rawHeader}
		if err := item.Header.ReadJSONGeneral(tctx, inHeader, item.FieldsMask); err != nil {
			return err
		}
	}
	if !propHeaderPresented {
		if err := item.Header.ReadJSONGeneral(tctx, nil, item.FieldsMask); err != nil {
			return err
		}
	}
	return nil
}

// This method is general version of WriteJSON, use it instead!
func (item *StatshouseGetTagMappingBootstrap) WriteJSONGeneral(tctx *basictl.JSONWriteContext, w []byte) (_ []byte, err error) {
	return item.WriteJSONOpt(tctx, w), nil
}

func (item *StatshouseGetTagMappingBootstrap) WriteJSON(w []byte) []byte {
	tctx := basictl.JSONWriteContext{}
	return item.WriteJSONOpt(&tctx, w)
}
func (item *StatshouseGetTagMappingBootstrap) WriteJSONOpt(tctx *basictl.JSONWriteContext, w []byte) []byte {
	w = append(w, '{')
	backupIndexFieldsMask := len(w)
	w = basictl.JSONAddCommaIfNeeded(w)
	w = append(w, `"fields_mask":`...)
	w = basictl.JSONWriteUint32(w, item.FieldsMask)
	if !(item.FieldsMask != 0) {
		w = w[:backupIndexFieldsMask]
	}
	w = basictl.JSONAddCommaIfNeeded(w)
	w = append(w, `"header":`...)
	w = item.Header.WriteJSONOpt(tctx, w, item.FieldsMask)
	return append(w, '}')
}

func (item *StatshouseGetTagMappingBootstrap) MarshalJSON() ([]byte, error) {
	return item.WriteJSON(nil), nil
}

func (item *StatshouseGetTagMappingBootstrap) UnmarshalJSON(b []byte) error {
	if err := item.ReadJSON(true, &basictl.JsonLexer{Data: b}); err != nil {
		return ErrorInvalidJSON("statshouse.getTagMappingBootstrap", err.Error())
	}
	return nil
}

func (item *StatshouseGetTagMappingBootstrap) WriteTL2(w []byte, ctx *basictl.TL2WriteContext) []byte {
	panic(ErrorTL2SerializersNotGenerated("statshouse.getTagMappingBootstrap"))
}

func (item *StatshouseGetTagMappingBootstrap) ReadTL2(r []byte, ctx *basictl.TL2ReadContext) (_ []byte, err error) {
	return r, ErrorTL2SerializersNotGenerated("statshouse.getTagMappingBootstrap")
}

// when local cache is empty, statshouse will ask aggregator for common mappings
type StatshouseGetTagMappingBootstrapBytes struct {
	FieldsMask uint32
	Header     StatshouseCommonProxyHeaderBytes
}

func (StatshouseGetTagMappingBootstrapBytes) TLName() string {
	return "statshouse.getTagMappingBootstrap"
}
func (StatshouseGetTagMappingBootstrapBytes) TLTag() uint32 { return 0x75a7f68e }

func (item *StatshouseGetTagMappingBootstrapBytes) Reset() {
	item.FieldsMask = 0
	item.Header.Reset()
}

func (item *StatshouseGetTagMappingBootstrapBytes) FillRandom(rg *basictl.RandGenerator) {
	item.FieldsMask = basictl.RandomFieldMask(rg, 0b11110000000000000000000000000000)
	item.Header.FillRandom(rg, item.FieldsMask)
}

func (item *StatshouseGetTagMappingBootstrapBytes) ReadTL1(w []byte) (_ []byte, err error) {
	if w, err = basictl.NatRead(w, &item.FieldsMask); err != nil {
		return w, err
	}
	return item.Header.ReadTL1(w, item.FieldsMask)
}

func (item *StatshouseGetTagMappingBootstrapBytes) WriteTL1General(w []byte) (_ []byte, err error) {
	return item.WriteTL1(w), nil
}

func (item *StatshouseGetTagMappingBootstrapBytes) WriteTL1(w []byte) []byte {
	w = basictl.NatWrite(w, item.FieldsMask)
	w = item.Header.WriteTL1(w, item.FieldsMask)
	return w
}

func (item *StatshouseGetTagMappingBootstrapBytes) ReadTL1Boxed(w []byte) (_ []byte, err error) {
	if w, err = basictl.NatReadExactTag(w, 0x75a7f68e); err != nil {
		return w, err
	}
	return item.ReadTL1(w)
}

func (item *StatshouseGetTagMappingBootstrapBytes) WriteTL1BoxedGeneral(w []byte) (_ []byte, err error) {
	return item.WriteTL1Boxed(w), nil
}

func (item *StatshouseGetTagMappingBootstrapBytes) WriteTL1Boxed(w []byte) []byte {
	w = basictl.NatWrite(w, 0x75a7f68e)
	return item.WriteTL1(w)
}

func (item *StatshouseGetTagMappingBootstrapBytes) ReadResultTL1(w []byte, ret *StatshouseGetTagMappingBootstrapResultBytes) (_ []byte, err error) {
	return ret.ReadTL1Boxed(w)
}

func (item *StatshouseGetTagMappingBootstrapBytes) WriteResultTL1(w []byte, ret StatshouseGetTagMappingBootstrapResultBytes) (_ []byte, err error) {
	w = ret.WriteTL1Boxed(w)
	return w, nil
}

func (item *StatshouseGetTagMappingBootstrapBytes) ReadResultJSON(legacyTypeNames bool, in *basictl.JsonLexer, ret *StatshouseGetTagMappingBootstrapResultBytes) error {
	tctx := &basictl.JSONReadContext{LegacyTypeNames: legacyTypeNames}
	if err := ret.ReadJSONGeneral(tctx, in); err != nil {
		return err
	}
	return nil
}

func (item *StatshouseGetTagMappingBootstrapBytes) WriteResultJSON(w []byte, ret StatshouseGetTagMappingBootstrapResultBytes) (_ []byte, err error) {
	tctx := basictl.JSONWriteContext{}
	return item.writeResultJSON(&tctx, w, ret)
}

func (item *StatshouseGetTagMappingBootstrapBytes) writeResultJSON(tctx *basictl.JSONWriteContext, w []byte, ret StatshouseGetTagMappingBootstrapResultBytes) (_ []byte, err error) {
	w = ret.WriteJSONOpt(tctx, w)
	return w, nil
}

func (item *StatshouseGetTagMappingBootstrapBytes) FillRandomResultTL1(rg *basictl.RandGenerator, w []byte) ([]byte, error) {
	var ret StatshouseGetTagMappingBootstrapResultBytes
	ret.FillRandom(rg)
	return item.WriteResultTL1(w, ret)
}

func (item *StatshouseGetTagMappingBootstrapBytes) ReadResultTL1WriteResultJSON(tctx *basictl.JSONWriteContext, r []byte, w []byte) (_ []byte, _ []byte, err error) {
	var ret StatshouseGetTagMappingBootstrapResultBytes
	if r, err = item.ReadResultTL1(r, &ret); err != nil {
		return r, w, err
	}
	w, err = item.writeResultJSON(tctx, w, ret)
	return r, w, err
}

func (item *StatshouseGetTagMappingBootstrapBytes) ReadResultJSONWriteResultTL1(r []byte, w []byte) (_ []byte, _ []byte, err error) {
	var ret StatshouseGetTagMappingBootstrapResultBytes
	if err = item.ReadResultJSON(true, &basictl.JsonLexer{Data: r}, &ret); err != nil {
		return r, w, err
	}
	w, err = item.WriteResultTL1(w, ret)
	return r, w, err
}

func (item *StatshouseGetTagMappingBootstrapBytes) ReadResultTL1WriteResultTL2(tctx *basictl.TL2WriteContext, r []byte, w []byte) (_ []byte, _ []byte, err error) {
	return r, w, ErrorTL2SerializersNotGenerated("statshouse.getTagMappingBootstrap")
}

func (item *StatshouseGetTagMappingBootstrapBytes) ReadResultTL2WriteResultTL1(tctx *basictl.TL2ReadContext, r []byte, w []byte) (_ []byte, _ []byte, err error) {
	return r, w, ErrorTL2SerializersNotGenerated("statshouse.getTagMappingBootstrap")
}

func (item *StatshouseGetTagMappingBootstrapBytes) ReadResultTL2WriteResultJSON(tctx *basictl.TL2ReadContext, jctx *basictl.JSONWriteContext, r []byte, w []byte) (_ []byte, _ []byte, err error) {
	return r, w, ErrorTL2SerializersNotGenerated("statshouse.getTagMappingBootstrap")
}

func (item *StatshouseGetTagMappingBootstrapBytes) ReadResultJSONWriteResultTL2(tctx *basictl.TL2WriteContext, r []byte, w []byte) (_ []byte, _ []byte, err error) {
	return r, w, ErrorTL2SerializersNotGenerated("statshouse.getTagMappingBootstrap")
}

func (item StatshouseGetTagMappingBootstrapBytes) String() string {
	return string(item.WriteJSON(nil))
}

func (item *StatshouseGetTagMappingBootstrapBytes) ReadJSON(legacyTypeNames bool, in *basictl.JsonLexer) error {
	tctx := basictl.JSONReadContext{LegacyTypeNames: legacyTypeNames}
	return item.ReadJSONGeneral(&tctx, in)
}

func (item *StatshouseGetTagMappingBootstrapBytes) ReadJSONGeneral(tctx *basictl.JSONReadContext, in *basictl.JsonLexer) error {
	var propFieldsMaskPresented bool
	var propHeaderPresented bool
	var rawHeader []byte
	if in != nil {
		in.Delim('{')
		if !in.Ok() {
			return in.Error()
		}
		for !in.IsDelim('}') {
			key := in.UnsafeFieldName(true)
			in.WantColon()
			switch key {
			case "fields_mask":
				if propFieldsMaskPresented {
					return ErrorInvalidJSONWithDuplicatingKeys("statshouse.getTagMappingBootstrap", "fields_mask")
				}
				propFieldsMaskPresented = true
				if err := Json2ReadUint32(in, &item.FieldsMask); err != nil {
					return err
				}
			case "header":
				if propHeaderPresented {
					return ErrorInvalidJSONWithDuplicatingKeys("statshouse.getTagMappingBootstrap", "header")
				}
				propHeaderPresented = true
				rawHeader = in.Raw()
				if !in.Ok() {
					return in.Error()
				}
			default:
				return ErrorInvalidJSONExcessElement("statshouse.getTagMappingBootstrap", key)
			}
			in.WantComma()
		}
		in.Delim('}')
		if !in.Ok() {
			return in.Error()
		}
	}
	if !propFieldsMaskPresented {
		item.FieldsMask = 0
	}
	if propHeaderPresented {
		inHeader := &basictl.JsonLexer{Data: rawHeader}
		if err := item.Header.ReadJSONGeneral(tctx, inHeader, item.FieldsMask); err != nil {
			return err
		}
	}
	if !propHeaderPresented {
		if err := item.Header.ReadJSONGeneral(tctx, nil, item.FieldsMask); err != nil {
			return err
		}
	}
	return nil
}

// This method is general version of WriteJSON, use it instead!
func (item *StatshouseGetTagMappingBootstrapBytes) WriteJSONGeneral(tctx *basictl.JSONWriteContext, w []byte) (_ []byte, err error) {
	return item.WriteJSONOpt(tctx, w), nil
}

func (item *StatshouseGetTagMappingBootstrapBytes) WriteJSON(w []byte) []byte {
	tctx := basictl.JSONWriteContext{}
	return item.WriteJSONOpt(&tctx, w)
}
func (item *StatshouseGetTagMappingBootstrapBytes) WriteJSONOpt(tctx *basictl.JSONWriteContext, w []byte) []byte {
	w = append(w, '{')
	backupIndexFieldsMask := len(w)
	w = basictl.JSONAddCommaIfNeeded(w)
	w = append(w, `"fields_mask":`...)
	w = basictl.JSONWriteUint32(w, item.FieldsMask)
	if !(item.FieldsMask != 0) {
		w = w[:backupIndexFieldsMask]
	}
	w = basictl.JSONAddCommaIfNeeded(w)
	w = append(w, `"header":`...)
	w = item.Header.WriteJSONOpt(tctx, w, item.FieldsMask)
	return append(w, '}')
}

func (item *StatshouseGetTagMappingBootstrapBytes) MarshalJSON() ([]byte, error) {
	return item.WriteJSON(nil), nil
}

func (item *StatshouseGetTagMappingBootstrapBytes) UnmarshalJSON(b []byte) error {
	if err := item.ReadJSON(true, &basictl.JsonLexer{Data: b}); err != nil {
		return ErrorInvalidJSON("statshouse.getTagMappingBootstrap", err.Error())
	}
	return nil
}

func (item *StatshouseGetTagMappingBootstrapBytes) WriteTL2(w []byte, ctx *basictl.TL2WriteContext) []byte {
	panic(ErrorTL2SerializersNotGenerated("statshouse.getTagMappingBootstrap"))
}

func (item *StatshouseGetTagMappingBootstrapBytes) ReadTL2(r []byte, ctx *basictl.TL2ReadContext) (_ []byte, err error) {
	return r, ErrorTL2SerializersNotGenerated("statshouse.getTagMappingBootstrap")
}
