// Copyright 2025 V Kontakte LLC
//
// This Source Code Form is subject to the terms of the Mozilla Public
// License, v. 2.0. If a copy of the MPL was not distributed with this
// file, You can obtain one at https://mozilla.org/MPL/2.0/.

// Code generated by tl2gen; DO NOT EDIT.
package internal

import (
	"github.com/VKCOM/statshouse/internal/vkgo/basictl"
)

var _ = basictl.NatWrite

type StatshouseApiQueryResponse struct {
	FieldsMask      uint32
	Series          StatshouseApiSeries
	SeriesMeta      []StatshouseApiSeriesMeta
	ChunkIds        []int32
	TotalTimePoints int32
	ResponseId      int64
	// ExcessPointLeft (TrueType) // Conditional: item.FieldsMask.0
	// ExcessPointRight (TrueType) // Conditional: item.FieldsMask.1
	tl2mask0 byte
}

func (StatshouseApiQueryResponse) TLName() string { return "statshouseApi.queryResponse" }
func (StatshouseApiQueryResponse) TLTag() uint32  { return 0x4487e49a }

func (item *StatshouseApiQueryResponse) SetExcessPointLeft(v bool) {
	if v {
		item.FieldsMask |= 1 << 0
	} else {
		item.FieldsMask &^= 1 << 0
	}
	if v {
		item.tl2mask0 |= 1
	} else {
		item.tl2mask0 &^= 1
	}
}
func (item *StatshouseApiQueryResponse) IsSetExcessPointLeft() bool { return item.tl2mask0&1 != 0 }

func (item *StatshouseApiQueryResponse) SetExcessPointRight(v bool) {
	if v {
		item.FieldsMask |= 1 << 1
	} else {
		item.FieldsMask &^= 1 << 1
	}
	if v {
		item.tl2mask0 |= 2
	} else {
		item.tl2mask0 &^= 2
	}
}
func (item *StatshouseApiQueryResponse) IsSetExcessPointRight() bool { return item.tl2mask0&2 != 0 }

func (item *StatshouseApiQueryResponse) Reset() {
	item.FieldsMask = 0
	item.Series.Reset()
	item.SeriesMeta = item.SeriesMeta[:0]
	item.ChunkIds = item.ChunkIds[:0]
	item.TotalTimePoints = 0
	item.ResponseId = 0
	item.tl2mask0 = 0
}

func (item *StatshouseApiQueryResponse) FillRandom(rg *basictl.RandGenerator, nat_query_fields_mask uint32) {
	item.tl2mask0 = 0
	item.FieldsMask = basictl.RandomFieldMask(rg, 0b11)
	item.Series.FillRandom(rg)
	BuiltinVectorStatshouseApiSeriesMetaFillRandom(rg, &item.SeriesMeta, nat_query_fields_mask)
	BuiltinVectorIntFillRandom(rg, &item.ChunkIds)
	item.TotalTimePoints = basictl.RandomInt(rg)
	item.ResponseId = basictl.RandomLong(rg)
	if item.FieldsMask&(1<<0) != 0 {
		item.tl2mask0 |= 1
	}
	if item.FieldsMask&(1<<1) != 0 {
		item.tl2mask0 |= 2
	}
}

func (item StatshouseApiQueryResponse) RepairMasksValue(nat_query_fields_mask uint32) StatshouseApiQueryResponse {
	item.RepairMasks(nat_query_fields_mask)
	return item
}
func (item *StatshouseApiQueryResponse) RepairMasks(nat_query_fields_mask uint32) {
	item.tl2mask0 = 0
	BuiltinVectorStatshouseApiSeriesMetaRepairMasks(&item.SeriesMeta, nat_query_fields_mask)
	if item.FieldsMask&(1<<0) != 0 {
		item.tl2mask0 |= 1
	}
	if item.FieldsMask&(1<<1) != 0 {
		item.tl2mask0 |= 2
	}
}

func (item *StatshouseApiQueryResponse) ReadTL1(w []byte, nat_query_fields_mask uint32) (_ []byte, err error) {
	item.tl2mask0 = 0
	if w, err = basictl.NatRead(w, &item.FieldsMask); err != nil {
		return w, err
	}
	if w, err = item.Series.ReadTL1(w); err != nil {
		return w, err
	}
	if w, err = BuiltinVectorStatshouseApiSeriesMetaReadTL1(w, &item.SeriesMeta, nat_query_fields_mask); err != nil {
		return w, err
	}
	if w, err = BuiltinVectorIntReadTL1(w, &item.ChunkIds); err != nil {
		return w, err
	}
	if w, err = basictl.IntRead(w, &item.TotalTimePoints); err != nil {
		return w, err
	}
	if w, err = basictl.LongRead(w, &item.ResponseId); err != nil {
		return w, err
	}
	if item.FieldsMask&(1<<0) != 0 {
		item.tl2mask0 |= 1
	}
	if item.FieldsMask&(1<<1) != 0 {
		item.tl2mask0 |= 2
	}
	return w, nil
}

func (item *StatshouseApiQueryResponse) WriteTL1(w []byte, nat_query_fields_mask uint32) []byte {
	w = basictl.NatWrite(w, item.FieldsMask)
	w = item.Series.WriteTL1(w)
	w = BuiltinVectorStatshouseApiSeriesMetaWriteTL1(w, item.SeriesMeta, nat_query_fields_mask)
	w = BuiltinVectorIntWriteTL1(w, item.ChunkIds)
	w = basictl.IntWrite(w, item.TotalTimePoints)
	w = basictl.LongWrite(w, item.ResponseId)
	return w
}

func (item *StatshouseApiQueryResponse) ReadTL1Boxed(w []byte, nat_query_fields_mask uint32) (_ []byte, err error) {
	if w, err = basictl.NatReadExactTag(w, 0x4487e49a); err != nil {
		return w, err
	}
	return item.ReadTL1(w, nat_query_fields_mask)
}

func (item *StatshouseApiQueryResponse) WriteTL1Boxed(w []byte, nat_query_fields_mask uint32) []byte {
	w = basictl.NatWrite(w, 0x4487e49a)
	return item.WriteTL1(w, nat_query_fields_mask)
}

func (item *StatshouseApiQueryResponse) ReadJSONGeneral(tctx *basictl.JSONReadContext, in *basictl.JsonLexer, nat_query_fields_mask uint32) error {
	item.tl2mask0 = 0
	var propFieldsMaskPresented bool
	var propSeriesPresented bool
	var propSeriesMetaPresented bool
	var propChunkIdsPresented bool
	var propTotalTimePointsPresented bool
	var propResponseIdPresented bool
	var propExcessPointLeftPresented bool
	var trueTypeExcessPointLeftValue bool
	var propExcessPointRightPresented bool
	var trueTypeExcessPointRightValue bool
	if in != nil {
		in.Delim('{')
		if !in.Ok() {
			return in.Error()
		}
		for !in.IsDelim('}') {
			key := in.UnsafeFieldName(true)
			in.WantColon()
			switch key {
			case "fields_mask":
				if propFieldsMaskPresented {
					return ErrorInvalidJSONWithDuplicatingKeys("statshouseApi.queryResponse", "fields_mask")
				}
				propFieldsMaskPresented = true
				if err := Json2ReadUint32(in, &item.FieldsMask); err != nil {
					return err
				}
			case "series":
				if propSeriesPresented {
					return ErrorInvalidJSONWithDuplicatingKeys("statshouseApi.queryResponse", "series")
				}
				propSeriesPresented = true
				if err := item.Series.ReadJSONGeneral(tctx, in); err != nil {
					return err
				}
			case "series_meta":
				if propSeriesMetaPresented {
					return ErrorInvalidJSONWithDuplicatingKeys("statshouseApi.queryResponse", "series_meta")
				}
				propSeriesMetaPresented = true
				if err := BuiltinVectorStatshouseApiSeriesMetaReadJSONGeneral(tctx, in, &item.SeriesMeta, nat_query_fields_mask); err != nil {
					return err
				}
			case "chunk_ids":
				if propChunkIdsPresented {
					return ErrorInvalidJSONWithDuplicatingKeys("statshouseApi.queryResponse", "chunk_ids")
				}
				propChunkIdsPresented = true
				if err := BuiltinVectorIntReadJSONGeneral(tctx, in, &item.ChunkIds); err != nil {
					return err
				}
			case "total_time_points":
				if propTotalTimePointsPresented {
					return ErrorInvalidJSONWithDuplicatingKeys("statshouseApi.queryResponse", "total_time_points")
				}
				propTotalTimePointsPresented = true
				if err := Json2ReadInt32(in, &item.TotalTimePoints); err != nil {
					return err
				}
			case "response_id":
				if propResponseIdPresented {
					return ErrorInvalidJSONWithDuplicatingKeys("statshouseApi.queryResponse", "response_id")
				}
				propResponseIdPresented = true
				if err := Json2ReadInt64(in, &item.ResponseId); err != nil {
					return err
				}
			case "excess_point_left":
				if propExcessPointLeftPresented {
					return ErrorInvalidJSONWithDuplicatingKeys("statshouseApi.queryResponse", "excess_point_left")
				}
				propExcessPointLeftPresented = true
				if err := Json2ReadBool(in, &trueTypeExcessPointLeftValue); err != nil {
					return err
				}
				if trueTypeExcessPointLeftValue {
					item.tl2mask0 |= 1
				}
			case "excess_point_right":
				if propExcessPointRightPresented {
					return ErrorInvalidJSONWithDuplicatingKeys("statshouseApi.queryResponse", "excess_point_right")
				}
				propExcessPointRightPresented = true
				if err := Json2ReadBool(in, &trueTypeExcessPointRightValue); err != nil {
					return err
				}
				if trueTypeExcessPointRightValue {
					item.tl2mask0 |= 2
				}
			default:
				return ErrorInvalidJSONExcessElement("statshouseApi.queryResponse", key)
			}
			in.WantComma()
		}
		in.Delim('}')
		if !in.Ok() {
			return in.Error()
		}
	}
	if !propFieldsMaskPresented {
		item.FieldsMask = 0
	}
	if !propSeriesPresented {
		item.Series.Reset()
	}
	if !propChunkIdsPresented {
		item.ChunkIds = item.ChunkIds[:0]
	}
	if !propTotalTimePointsPresented {
		item.TotalTimePoints = 0
	}
	if !propResponseIdPresented {
		item.ResponseId = 0
	}
	if !propExcessPointLeftPresented && item.FieldsMask&(1<<0) != 0 {
		item.tl2mask0 |= 1
	}
	if !propExcessPointRightPresented && item.FieldsMask&(1<<1) != 0 {
		item.tl2mask0 |= 2
	}
	if trueTypeExcessPointLeftValue {
		item.FieldsMask |= 1 << 0
	}
	if trueTypeExcessPointRightValue {
		item.FieldsMask |= 1 << 1
	}
	if !propSeriesMetaPresented {
		if err := BuiltinVectorStatshouseApiSeriesMetaReadJSONGeneral(tctx, nil, &item.SeriesMeta, nat_query_fields_mask); err != nil {
			return err
		}
	}
	return nil
}

// This method is general version of WriteJSON, use it instead!
func (item *StatshouseApiQueryResponse) WriteJSONGeneral(tctx *basictl.JSONWriteContext, w []byte, nat_query_fields_mask uint32) (_ []byte, err error) {
	return item.WriteJSONOpt(tctx, w, nat_query_fields_mask), nil
}

func (item *StatshouseApiQueryResponse) WriteJSON(w []byte, nat_query_fields_mask uint32) []byte {
	tctx := basictl.JSONWriteContext{}
	return item.WriteJSONOpt(&tctx, w, nat_query_fields_mask)
}
func (item *StatshouseApiQueryResponse) WriteJSONOpt(tctx *basictl.JSONWriteContext, w []byte, nat_query_fields_mask uint32) []byte {
	w = append(w, '{')
	backupIndexFieldsMask := len(w)
	w = basictl.JSONAddCommaIfNeeded(w)
	w = append(w, `"fields_mask":`...)
	w = basictl.JSONWriteUint32(w, item.FieldsMask)
	if !(item.FieldsMask != 0) {
		w = w[:backupIndexFieldsMask]
	}
	w = basictl.JSONAddCommaIfNeeded(w)
	w = append(w, `"series":`...)
	w = item.Series.WriteJSONOpt(tctx, w)
	backupIndexSeriesMeta := len(w)
	w = basictl.JSONAddCommaIfNeeded(w)
	w = append(w, `"series_meta":`...)
	w = BuiltinVectorStatshouseApiSeriesMetaWriteJSONOpt(tctx, w, item.SeriesMeta, nat_query_fields_mask)
	if !(len(item.SeriesMeta) != 0) {
		w = w[:backupIndexSeriesMeta]
	}
	backupIndexChunkIds := len(w)
	w = basictl.JSONAddCommaIfNeeded(w)
	w = append(w, `"chunk_ids":`...)
	w = BuiltinVectorIntWriteJSONOpt(tctx, w, item.ChunkIds)
	if !(len(item.ChunkIds) != 0) {
		w = w[:backupIndexChunkIds]
	}
	backupIndexTotalTimePoints := len(w)
	w = basictl.JSONAddCommaIfNeeded(w)
	w = append(w, `"total_time_points":`...)
	w = basictl.JSONWriteInt32(w, item.TotalTimePoints)
	if !(item.TotalTimePoints != 0) {
		w = w[:backupIndexTotalTimePoints]
	}
	backupIndexResponseId := len(w)
	w = basictl.JSONAddCommaIfNeeded(w)
	w = append(w, `"response_id":`...)
	w = basictl.JSONWriteInt64(w, item.ResponseId)
	if !(item.ResponseId != 0) {
		w = w[:backupIndexResponseId]
	}
	if item.tl2mask0&1 != 0 {
		w = basictl.JSONAddCommaIfNeeded(w)
		w = append(w, `"excess_point_left":true`...)
	}
	if item.tl2mask0&2 != 0 {
		w = basictl.JSONAddCommaIfNeeded(w)
		w = append(w, `"excess_point_right":true`...)
	}
	return append(w, '}')
}

func (item *StatshouseApiQueryResponse) CalculateLayout(sizes []int, optimizeEmpty bool) ([]int, int) {
	sizes = append(sizes, 3399832794)
	sizePosition := len(sizes)
	sizes = append(sizes, 0)

	currentSize := 1
	lastUsedByte := 0
	var sz int

	if item.FieldsMask != 0 {
		currentSize += 4
		lastUsedByte = currentSize
	}
	if sizes, sz = item.Series.CalculateLayout(sizes, true); sz != 0 {
		currentSize += sz
		lastUsedByte = currentSize
	}
	if sizes, sz = BuiltinVectorStatshouseApiSeriesMetaCalculateLayout(sizes, true, &item.SeriesMeta); sz != 0 {
		currentSize += sz
		lastUsedByte = currentSize
	}
	if sizes, sz = BuiltinVectorIntCalculateLayout(sizes, true, &item.ChunkIds); sz != 0 {
		currentSize += sz
		lastUsedByte = currentSize
	}
	if item.TotalTimePoints != 0 {
		currentSize += 4
		lastUsedByte = currentSize
	}
	if item.ResponseId != 0 {
		currentSize += 8
		lastUsedByte = currentSize
	}
	if item.tl2mask0&1 != 0 {
		lastUsedByte = currentSize
	}
	currentSize++
	if item.tl2mask0&2 != 0 {
		lastUsedByte = currentSize
	}

	if lastUsedByte < currentSize {
		currentSize = lastUsedByte
	}
	sizes[sizePosition] = currentSize
	if currentSize == 0 {
		sizes = sizes[:sizePosition+1]
	}
	if !optimizeEmpty || currentSize != 0 {
		currentSize += basictl.TL2CalculateSize(currentSize)
	}
	Unused(sz)
	return sizes, currentSize
}

func (item *StatshouseApiQueryResponse) InternalWriteTL2(w []byte, sizes []int, optimizeEmpty bool) ([]byte, []int, int) {
	if sizes[0] != 3399832794 {
		panic("tl2: tag mismatch between calculate and write")
	}
	currentSize := sizes[1]
	sizes = sizes[2:]
	if optimizeEmpty && currentSize == 0 {
		return w, sizes, 0
	}
	w = basictl.TL2WriteSize(w, currentSize)
	if currentSize == 0 {
		return w, sizes, 1
	}
	oldLen := len(w)
	var sz int
	var currentBlock byte
	currentBlockPosition := len(w)
	w = append(w, 0)
	if item.FieldsMask != 0 {
		w = basictl.NatWrite(w, item.FieldsMask)
		currentBlock |= 2
	}
	if w, sizes, sz = item.Series.InternalWriteTL2(w, sizes, true); sz != 0 {
		currentBlock |= 4
	}
	if w, sizes, sz = BuiltinVectorStatshouseApiSeriesMetaInternalWriteTL2(w, sizes, true, &item.SeriesMeta); sz != 0 {
		currentBlock |= 8
	}
	if w, sizes, sz = BuiltinVectorIntInternalWriteTL2(w, sizes, true, &item.ChunkIds); sz != 0 {
		currentBlock |= 16
	}
	if item.TotalTimePoints != 0 {
		w = basictl.IntWrite(w, item.TotalTimePoints)
		currentBlock |= 32
	}
	if item.ResponseId != 0 {
		w = basictl.LongWrite(w, item.ResponseId)
		currentBlock |= 64
	}
	if item.tl2mask0&1 != 0 {
		currentBlock |= 128
	}
	if currentBlockPosition < len(w) {
		w[currentBlockPosition] = currentBlock
	}
	currentBlock = 0
	currentBlockPosition = len(w)
	if len(w)-oldLen < currentSize {
		w = append(w, 0)
	}
	if item.tl2mask0&2 != 0 {
		currentBlock |= 1
	}
	if currentBlockPosition < len(w) {
		w[currentBlockPosition] = currentBlock
	}
	if len(w)-oldLen != currentSize {
		panic("tl2: mismatch between calculate and write")
	}
	Unused(sz)
	return w, sizes, 1
}

func (item *StatshouseApiQueryResponse) WriteTL2(w []byte, ctx *basictl.TL2WriteContext) []byte {
	var sizes, sizes2 []int
	if ctx != nil {
		sizes = ctx.SizeBuffer[:0]
	}
	sizes, _ = item.CalculateLayout(sizes, false)
	w, sizes2, _ = item.InternalWriteTL2(w, sizes, false)
	if len(sizes2) != 0 {
		panic("tl2: internal write did not consume all size data")
	}
	if ctx != nil {
		ctx.SizeBuffer = sizes
	}
	return w
}

func (item *StatshouseApiQueryResponse) InternalReadTL2(r []byte) (_ []byte, err error) {
	currentSize := 0
	if r, currentSize, err = basictl.TL2ParseSize(r); err != nil {
		return r, err
	}
	if currentSize == 0 {
		item.Reset()
		return r, nil
	}
	if len(r) < currentSize {
		return r, basictl.TL2Error("not enough data: expected %d, got %d", currentSize, len(r))
	}

	currentR := r[:currentSize]
	r = r[currentSize:]

	var block byte
	if currentR, err = basictl.ByteRead(currentR, &block); err != nil {
		return currentR, err
	}
	// read No of constructor
	if block&1 != 0 {
		var index int
		if currentR, index, err = basictl.TL2ParseSize(currentR); err != nil {
			return currentR, err
		}
		if index != 0 {
			return r, ErrorInvalidUnionIndex("statshouseApi.queryResponse", index)
		}
	}
	item.tl2mask0 = 0
	if block&2 != 0 {
		if currentR, err = basictl.NatRead(currentR, &item.FieldsMask); err != nil {
			return currentR, err
		}
	} else {
		item.FieldsMask = 0
	}
	if block&4 != 0 {
		if currentR, err = item.Series.InternalReadTL2(currentR); err != nil {
			return currentR, err
		}
	} else {
		item.Series.Reset()
	}
	if block&8 != 0 {
		if currentR, err = BuiltinVectorStatshouseApiSeriesMetaInternalReadTL2(currentR, &item.SeriesMeta); err != nil {
			return currentR, err
		}
	} else {
		item.SeriesMeta = item.SeriesMeta[:0]
	}
	if block&16 != 0 {
		if currentR, err = BuiltinVectorIntInternalReadTL2(currentR, &item.ChunkIds); err != nil {
			return currentR, err
		}
	} else {
		item.ChunkIds = item.ChunkIds[:0]
	}
	if block&32 != 0 {
		if currentR, err = basictl.IntRead(currentR, &item.TotalTimePoints); err != nil {
			return currentR, err
		}
	} else {
		item.TotalTimePoints = 0
	}
	if block&64 != 0 {
		if currentR, err = basictl.LongRead(currentR, &item.ResponseId); err != nil {
			return currentR, err
		}
	} else {
		item.ResponseId = 0
	}
	if block&128 != 0 {
		item.tl2mask0 |= 1
	}
	// start the next block
	if len(currentR) > 0 {
		if currentR, err = basictl.ByteRead(currentR, &block); err != nil {
			return currentR, err
		}
	} else {
		block = 0
	}
	if block&1 != 0 {
		item.tl2mask0 |= 2
	}
	Unused(currentR)
	return r, nil
}

func (item *StatshouseApiQueryResponse) ReadTL2(r []byte, ctx *basictl.TL2ReadContext) (_ []byte, err error) {
	return item.InternalReadTL2(r)
}
