// Copyright 2023 V Kontakte LLC
//
// This Source Code Form is subject to the terms of the Mozilla Public
// License, v. 2.0. If a copy of the MPL was not distributed with this
// file, You can obtain one at https://mozilla.org/MPL/2.0/.

// Code generated by vktl/cmd/tlgen2; DO NOT EDIT.
package internal

import (
	"github.com/vkcom/statshouse/internal/vkgo/basictl"
)

var _ = basictl.NatWrite

func BuiltinVectorStatshouseApiTagValueRead(w []byte, vec *[]StatshouseApiTagValue) (_ []byte, err error) {
	var l uint32
	if w, err = basictl.NatRead(w, &l); err != nil {
		return w, err
	}
	if err = basictl.CheckLengthSanity(w, l, 4); err != nil {
		return w, err
	}
	if uint32(cap(*vec)) < l {
		*vec = make([]StatshouseApiTagValue, l)
	} else {
		*vec = (*vec)[:l]
	}
	for i := range *vec {
		if w, err = (*vec)[i].Read(w); err != nil {
			return w, err
		}
	}
	return w, nil
}

func BuiltinVectorStatshouseApiTagValueWrite(w []byte, vec []StatshouseApiTagValue) (_ []byte, err error) {
	w = basictl.NatWrite(w, uint32(len(vec)))
	for _, elem := range vec {
		if w, err = elem.Write(w); err != nil {
			return w, err
		}
	}
	return w, nil
}

func BuiltinVectorStatshouseApiTagValueReadJSON(legacyTypeNames bool, in *basictl.JsonLexer, vec *[]StatshouseApiTagValue) error {
	*vec = (*vec)[:cap(*vec)]
	index := 0
	if in != nil {
		in.Delim('[')
		if !in.Ok() {
			return ErrorInvalidJSON("[]StatshouseApiTagValue", "expected json array")
		}
		for ; !in.IsDelim(']'); index++ {
			if len(*vec) <= index {
				var newValue StatshouseApiTagValue
				*vec = append(*vec, newValue)
				*vec = (*vec)[:cap(*vec)]
			}
			if err := (*vec)[index].ReadJSON(legacyTypeNames, in); err != nil {
				return err
			}
			in.WantComma()
		}
		in.Delim(']')
		if !in.Ok() {
			return ErrorInvalidJSON("[]StatshouseApiTagValue", "expected json array's end")
		}
	}
	*vec = (*vec)[:index]
	return nil
}

func BuiltinVectorStatshouseApiTagValueWriteJSON(w []byte, vec []StatshouseApiTagValue) (_ []byte, err error) {
	return BuiltinVectorStatshouseApiTagValueWriteJSONOpt(true, false, w, vec)
}
func BuiltinVectorStatshouseApiTagValueWriteJSONOpt(newTypeNames bool, short bool, w []byte, vec []StatshouseApiTagValue) (_ []byte, err error) {
	w = append(w, '[')
	for _, elem := range vec {
		w = basictl.JSONAddCommaIfNeeded(w)
		if w, err = elem.WriteJSONOpt(newTypeNames, short, w); err != nil {
			return w, err
		}
	}
	return append(w, ']'), nil
}

type StatshouseApiTagValue struct {
	FieldsMask uint32
	In         bool
	Value      string
	Flag       StatshouseApiFlag
}

func (StatshouseApiTagValue) TLName() string { return "statshouseApi.tagValue" }
func (StatshouseApiTagValue) TLTag() uint32  { return 0x43eeb763 }

func (item *StatshouseApiTagValue) Reset() {
	item.FieldsMask = 0
	item.In = false
	item.Value = ""
	item.Flag.Reset()
}

func (item *StatshouseApiTagValue) Read(w []byte) (_ []byte, err error) {
	if w, err = basictl.NatRead(w, &item.FieldsMask); err != nil {
		return w, err
	}
	if w, err = BoolReadBoxed(w, &item.In); err != nil {
		return w, err
	}
	if w, err = basictl.StringRead(w, &item.Value); err != nil {
		return w, err
	}
	return item.Flag.ReadBoxed(w)
}

func (item *StatshouseApiTagValue) Write(w []byte) (_ []byte, err error) {
	w = basictl.NatWrite(w, item.FieldsMask)
	if w, err = BoolWriteBoxed(w, item.In); err != nil {
		return w, err
	}
	w = basictl.StringWrite(w, item.Value)
	return item.Flag.WriteBoxed(w)
}

func (item *StatshouseApiTagValue) ReadBoxed(w []byte) (_ []byte, err error) {
	if w, err = basictl.NatReadExactTag(w, 0x43eeb763); err != nil {
		return w, err
	}
	return item.Read(w)
}

func (item *StatshouseApiTagValue) WriteBoxed(w []byte) ([]byte, error) {
	w = basictl.NatWrite(w, 0x43eeb763)
	return item.Write(w)
}

func (item StatshouseApiTagValue) String() string {
	w, err := item.WriteJSON(nil)
	if err != nil {
		return err.Error()
	}
	return string(w)
}

func (item *StatshouseApiTagValue) ReadJSON(legacyTypeNames bool, in *basictl.JsonLexer) error {
	var propFieldsMaskPresented bool
	var propInPresented bool
	var propValuePresented bool
	var propFlagPresented bool

	if in != nil {
		in.Delim('{')
		if !in.Ok() {
			return in.Error()
		}
		for !in.IsDelim('}') {
			key := in.UnsafeFieldName(true)
			in.WantColon()
			switch key {
			case "fields_mask":
				if propFieldsMaskPresented {
					return ErrorInvalidJSONWithDuplicatingKeys("statshouseApi.tagValue", "fields_mask")
				}
				if err := Json2ReadUint32(in, &item.FieldsMask); err != nil {
					return err
				}
				propFieldsMaskPresented = true
			case "in":
				if propInPresented {
					return ErrorInvalidJSONWithDuplicatingKeys("statshouseApi.tagValue", "in")
				}
				if err := Json2ReadBool(in, &item.In); err != nil {
					return err
				}
				propInPresented = true
			case "value":
				if propValuePresented {
					return ErrorInvalidJSONWithDuplicatingKeys("statshouseApi.tagValue", "value")
				}
				if err := Json2ReadString(in, &item.Value); err != nil {
					return err
				}
				propValuePresented = true
			case "flag":
				if propFlagPresented {
					return ErrorInvalidJSONWithDuplicatingKeys("statshouseApi.tagValue", "flag")
				}
				if err := item.Flag.ReadJSON(legacyTypeNames, in); err != nil {
					return err
				}
				propFlagPresented = true
			default:
				return ErrorInvalidJSONExcessElement("statshouseApi.tagValue", key)
			}
			in.WantComma()
		}
		in.Delim('}')
		if !in.Ok() {
			return in.Error()
		}
	}
	if !propFieldsMaskPresented {
		item.FieldsMask = 0
	}
	if !propInPresented {
		item.In = false
	}
	if !propValuePresented {
		item.Value = ""
	}
	if !propFlagPresented {
		item.Flag.Reset()
	}
	return nil
}

func (item *StatshouseApiTagValue) WriteJSON(w []byte) (_ []byte, err error) {
	return item.WriteJSONOpt(true, false, w)
}
func (item *StatshouseApiTagValue) WriteJSONOpt(newTypeNames bool, short bool, w []byte) (_ []byte, err error) {
	w = append(w, '{')
	backupIndexFieldsMask := len(w)
	w = basictl.JSONAddCommaIfNeeded(w)
	w = append(w, `"fields_mask":`...)
	w = basictl.JSONWriteUint32(w, item.FieldsMask)
	if (item.FieldsMask != 0) == false {
		w = w[:backupIndexFieldsMask]
	}
	backupIndexIn := len(w)
	w = basictl.JSONAddCommaIfNeeded(w)
	w = append(w, `"in":`...)
	w = basictl.JSONWriteBool(w, item.In)
	if (item.In) == false {
		w = w[:backupIndexIn]
	}
	backupIndexValue := len(w)
	w = basictl.JSONAddCommaIfNeeded(w)
	w = append(w, `"value":`...)
	w = basictl.JSONWriteString(w, item.Value)
	if (len(item.Value) != 0) == false {
		w = w[:backupIndexValue]
	}
	w = basictl.JSONAddCommaIfNeeded(w)
	w = append(w, `"flag":`...)
	if w, err = item.Flag.WriteJSONOpt(newTypeNames, short, w); err != nil {
		return w, err
	}
	return append(w, '}'), nil
}

func (item *StatshouseApiTagValue) MarshalJSON() ([]byte, error) {
	return item.WriteJSON(nil)
}

func (item *StatshouseApiTagValue) UnmarshalJSON(b []byte) error {
	if err := item.ReadJSON(true, &basictl.JsonLexer{Data: b}); err != nil {
		return ErrorInvalidJSON("statshouseApi.tagValue", err.Error())
	}
	return nil
}
