// Copyright 2025 V Kontakte LLC
//
// This Source Code Form is subject to the terms of the Mozilla Public
// License, v. 2.0. If a copy of the MPL was not distributed with this
// file, You can obtain one at https://mozilla.org/MPL/2.0/.

// Code generated by vktl/cmd/tlgen2; DO NOT EDIT.
package internal

import (
	"github.com/vkcom/statshouse/internal/vkgo/basictl"
)

var _ = basictl.NatWrite

type StatshouseGetMetrics3 struct {
	FieldsMask uint32
	Header     StatshouseCommonProxyHeader
	FieldMask  uint32
	From       int64
	Limit      int64
	// ReturnIfEmpty (TrueType) // Conditional: item.FieldMask.3
	// NewJournal (TrueType) // Conditional: item.FieldMask.15
	// CompactJournal (TrueType) // Conditional: item.FieldMask.4
}

func (StatshouseGetMetrics3) TLName() string { return "statshouse.getMetrics3" }
func (StatshouseGetMetrics3) TLTag() uint32  { return 0x42855554 }

func (item *StatshouseGetMetrics3) SetReturnIfEmpty(v bool) {
	if v {
		item.FieldMask |= 1 << 3
	} else {
		item.FieldMask &^= 1 << 3
	}
}
func (item StatshouseGetMetrics3) IsSetReturnIfEmpty() bool { return item.FieldMask&(1<<3) != 0 }

func (item *StatshouseGetMetrics3) SetNewJournal(v bool) {
	if v {
		item.FieldMask |= 1 << 15
	} else {
		item.FieldMask &^= 1 << 15
	}
}
func (item StatshouseGetMetrics3) IsSetNewJournal() bool { return item.FieldMask&(1<<15) != 0 }

func (item *StatshouseGetMetrics3) SetCompactJournal(v bool) {
	if v {
		item.FieldMask |= 1 << 4
	} else {
		item.FieldMask &^= 1 << 4
	}
}
func (item StatshouseGetMetrics3) IsSetCompactJournal() bool { return item.FieldMask&(1<<4) != 0 }

func (item *StatshouseGetMetrics3) Reset() {
	item.FieldsMask = 0
	item.Header.Reset()
	item.FieldMask = 0
	item.From = 0
	item.Limit = 0
}

func (item *StatshouseGetMetrics3) Read(w []byte) (_ []byte, err error) {
	if w, err = basictl.NatRead(w, &item.FieldsMask); err != nil {
		return w, err
	}
	if w, err = item.Header.Read(w, item.FieldsMask); err != nil {
		return w, err
	}
	if w, err = basictl.NatRead(w, &item.FieldMask); err != nil {
		return w, err
	}
	if w, err = basictl.LongRead(w, &item.From); err != nil {
		return w, err
	}
	if w, err = basictl.LongRead(w, &item.Limit); err != nil {
		return w, err
	}
	return w, nil
}

// This method is general version of Write, use it instead!
func (item *StatshouseGetMetrics3) WriteGeneral(w []byte) (_ []byte, err error) {
	return item.Write(w), nil
}

func (item *StatshouseGetMetrics3) Write(w []byte) []byte {
	w = basictl.NatWrite(w, item.FieldsMask)
	w = item.Header.Write(w, item.FieldsMask)
	w = basictl.NatWrite(w, item.FieldMask)
	w = basictl.LongWrite(w, item.From)
	w = basictl.LongWrite(w, item.Limit)
	return w
}

func (item *StatshouseGetMetrics3) ReadBoxed(w []byte) (_ []byte, err error) {
	if w, err = basictl.NatReadExactTag(w, 0x42855554); err != nil {
		return w, err
	}
	return item.Read(w)
}

// This method is general version of WriteBoxed, use it instead!
func (item *StatshouseGetMetrics3) WriteBoxedGeneral(w []byte) (_ []byte, err error) {
	return item.WriteBoxed(w), nil
}

func (item *StatshouseGetMetrics3) WriteBoxed(w []byte) []byte {
	w = basictl.NatWrite(w, 0x42855554)
	return item.Write(w)
}

func (item *StatshouseGetMetrics3) ReadResult(w []byte, ret *MetadataGetJournalResponsenew) (_ []byte, err error) {
	return ret.ReadBoxed(w, item.FieldsMask)
}

func (item *StatshouseGetMetrics3) WriteResult(w []byte, ret MetadataGetJournalResponsenew) (_ []byte, err error) {
	w = ret.WriteBoxed(w, item.FieldsMask)
	return w, nil
}

func (item *StatshouseGetMetrics3) ReadResultJSON(legacyTypeNames bool, in *basictl.JsonLexer, ret *MetadataGetJournalResponsenew) error {
	if err := ret.ReadJSON(legacyTypeNames, in, item.FieldsMask); err != nil {
		return err
	}
	return nil
}

func (item *StatshouseGetMetrics3) WriteResultJSON(w []byte, ret MetadataGetJournalResponsenew) (_ []byte, err error) {
	return item.writeResultJSON(true, false, w, ret)
}

func (item *StatshouseGetMetrics3) writeResultJSON(newTypeNames bool, short bool, w []byte, ret MetadataGetJournalResponsenew) (_ []byte, err error) {
	w = ret.WriteJSONOpt(newTypeNames, short, w, item.FieldsMask)
	return w, nil
}

func (item *StatshouseGetMetrics3) ReadResultWriteResultJSON(r []byte, w []byte) (_ []byte, _ []byte, err error) {
	var ret MetadataGetJournalResponsenew
	if r, err = item.ReadResult(r, &ret); err != nil {
		return r, w, err
	}
	w, err = item.WriteResultJSON(w, ret)
	return r, w, err
}

func (item *StatshouseGetMetrics3) ReadResultWriteResultJSONOpt(newTypeNames bool, short bool, r []byte, w []byte) (_ []byte, _ []byte, err error) {
	var ret MetadataGetJournalResponsenew
	if r, err = item.ReadResult(r, &ret); err != nil {
		return r, w, err
	}
	w, err = item.writeResultJSON(newTypeNames, short, w, ret)
	return r, w, err
}

func (item *StatshouseGetMetrics3) ReadResultJSONWriteResult(r []byte, w []byte) ([]byte, []byte, error) {
	var ret MetadataGetJournalResponsenew
	err := item.ReadResultJSON(true, &basictl.JsonLexer{Data: r}, &ret)
	if err != nil {
		return r, w, err
	}
	w, err = item.WriteResult(w, ret)
	return r, w, err
}

func (item StatshouseGetMetrics3) String() string {
	return string(item.WriteJSON(nil))
}

func (item *StatshouseGetMetrics3) ReadJSON(legacyTypeNames bool, in *basictl.JsonLexer) error {
	var propFieldsMaskPresented bool
	var rawHeader []byte
	var propFieldMaskPresented bool
	var propFromPresented bool
	var propLimitPresented bool
	var trueTypeReturnIfEmptyPresented bool
	var trueTypeReturnIfEmptyValue bool
	var trueTypeNewJournalPresented bool
	var trueTypeNewJournalValue bool
	var trueTypeCompactJournalPresented bool
	var trueTypeCompactJournalValue bool

	if in != nil {
		in.Delim('{')
		if !in.Ok() {
			return in.Error()
		}
		for !in.IsDelim('}') {
			key := in.UnsafeFieldName(true)
			in.WantColon()
			switch key {
			case "fields_mask":
				if propFieldsMaskPresented {
					return ErrorInvalidJSONWithDuplicatingKeys("statshouse.getMetrics3", "fields_mask")
				}
				if err := Json2ReadUint32(in, &item.FieldsMask); err != nil {
					return err
				}
				propFieldsMaskPresented = true
			case "header":
				if rawHeader != nil {
					return ErrorInvalidJSONWithDuplicatingKeys("statshouse.getMetrics3", "header")
				}
				rawHeader = in.Raw()
				if !in.Ok() {
					return in.Error()
				}
			case "field_mask":
				if propFieldMaskPresented {
					return ErrorInvalidJSONWithDuplicatingKeys("statshouse.getMetrics3", "field_mask")
				}
				if err := Json2ReadUint32(in, &item.FieldMask); err != nil {
					return err
				}
				propFieldMaskPresented = true
			case "from":
				if propFromPresented {
					return ErrorInvalidJSONWithDuplicatingKeys("statshouse.getMetrics3", "from")
				}
				if err := Json2ReadInt64(in, &item.From); err != nil {
					return err
				}
				propFromPresented = true
			case "limit":
				if propLimitPresented {
					return ErrorInvalidJSONWithDuplicatingKeys("statshouse.getMetrics3", "limit")
				}
				if err := Json2ReadInt64(in, &item.Limit); err != nil {
					return err
				}
				propLimitPresented = true
			case "return_if_empty":
				if trueTypeReturnIfEmptyPresented {
					return ErrorInvalidJSONWithDuplicatingKeys("statshouse.getMetrics3", "return_if_empty")
				}
				if err := Json2ReadBool(in, &trueTypeReturnIfEmptyValue); err != nil {
					return err
				}
				trueTypeReturnIfEmptyPresented = true
			case "new_journal":
				if trueTypeNewJournalPresented {
					return ErrorInvalidJSONWithDuplicatingKeys("statshouse.getMetrics3", "new_journal")
				}
				if err := Json2ReadBool(in, &trueTypeNewJournalValue); err != nil {
					return err
				}
				trueTypeNewJournalPresented = true
			case "compact_journal":
				if trueTypeCompactJournalPresented {
					return ErrorInvalidJSONWithDuplicatingKeys("statshouse.getMetrics3", "compact_journal")
				}
				if err := Json2ReadBool(in, &trueTypeCompactJournalValue); err != nil {
					return err
				}
				trueTypeCompactJournalPresented = true
			default:
				return ErrorInvalidJSONExcessElement("statshouse.getMetrics3", key)
			}
			in.WantComma()
		}
		in.Delim('}')
		if !in.Ok() {
			return in.Error()
		}
	}
	if !propFieldsMaskPresented {
		item.FieldsMask = 0
	}
	if !propFieldMaskPresented {
		item.FieldMask = 0
	}
	if !propFromPresented {
		item.From = 0
	}
	if !propLimitPresented {
		item.Limit = 0
	}
	if trueTypeReturnIfEmptyPresented {
		if trueTypeReturnIfEmptyValue {
			item.FieldMask |= 1 << 3
		}
	}
	if trueTypeNewJournalPresented {
		if trueTypeNewJournalValue {
			item.FieldMask |= 1 << 15
		}
	}
	if trueTypeCompactJournalPresented {
		if trueTypeCompactJournalValue {
			item.FieldMask |= 1 << 4
		}
	}
	var inHeaderPointer *basictl.JsonLexer
	inHeader := basictl.JsonLexer{Data: rawHeader}
	if rawHeader != nil {
		inHeaderPointer = &inHeader
	}
	if err := item.Header.ReadJSON(legacyTypeNames, inHeaderPointer, item.FieldsMask); err != nil {
		return err
	}

	// tries to set bit to zero if it is 1
	if trueTypeReturnIfEmptyPresented && !trueTypeReturnIfEmptyValue && (item.FieldMask&(1<<3) != 0) {
		return ErrorInvalidJSON("statshouse.getMetrics3", "fieldmask bit field_mask.2 is indefinite because of the contradictions in values")
	}
	// tries to set bit to zero if it is 1
	if trueTypeNewJournalPresented && !trueTypeNewJournalValue && (item.FieldMask&(1<<15) != 0) {
		return ErrorInvalidJSON("statshouse.getMetrics3", "fieldmask bit field_mask.2 is indefinite because of the contradictions in values")
	}
	// tries to set bit to zero if it is 1
	if trueTypeCompactJournalPresented && !trueTypeCompactJournalValue && (item.FieldMask&(1<<4) != 0) {
		return ErrorInvalidJSON("statshouse.getMetrics3", "fieldmask bit field_mask.2 is indefinite because of the contradictions in values")
	}
	return nil
}

// This method is general version of WriteJSON, use it instead!
func (item *StatshouseGetMetrics3) WriteJSONGeneral(w []byte) (_ []byte, err error) {
	return item.WriteJSONOpt(true, false, w), nil
}

func (item *StatshouseGetMetrics3) WriteJSON(w []byte) []byte {
	return item.WriteJSONOpt(true, false, w)
}
func (item *StatshouseGetMetrics3) WriteJSONOpt(newTypeNames bool, short bool, w []byte) []byte {
	w = append(w, '{')
	backupIndexFieldsMask := len(w)
	w = basictl.JSONAddCommaIfNeeded(w)
	w = append(w, `"fields_mask":`...)
	w = basictl.JSONWriteUint32(w, item.FieldsMask)
	if (item.FieldsMask != 0) == false {
		w = w[:backupIndexFieldsMask]
	}
	w = basictl.JSONAddCommaIfNeeded(w)
	w = append(w, `"header":`...)
	w = item.Header.WriteJSONOpt(newTypeNames, short, w, item.FieldsMask)
	backupIndexFieldMask := len(w)
	w = basictl.JSONAddCommaIfNeeded(w)
	w = append(w, `"field_mask":`...)
	w = basictl.JSONWriteUint32(w, item.FieldMask)
	if (item.FieldMask != 0) == false {
		w = w[:backupIndexFieldMask]
	}
	backupIndexFrom := len(w)
	w = basictl.JSONAddCommaIfNeeded(w)
	w = append(w, `"from":`...)
	w = basictl.JSONWriteInt64(w, item.From)
	if (item.From != 0) == false {
		w = w[:backupIndexFrom]
	}
	backupIndexLimit := len(w)
	w = basictl.JSONAddCommaIfNeeded(w)
	w = append(w, `"limit":`...)
	w = basictl.JSONWriteInt64(w, item.Limit)
	if (item.Limit != 0) == false {
		w = w[:backupIndexLimit]
	}
	if item.FieldMask&(1<<3) != 0 {
		w = basictl.JSONAddCommaIfNeeded(w)
		w = append(w, `"return_if_empty":true`...)
	}
	if item.FieldMask&(1<<15) != 0 {
		w = basictl.JSONAddCommaIfNeeded(w)
		w = append(w, `"new_journal":true`...)
	}
	if item.FieldMask&(1<<4) != 0 {
		w = basictl.JSONAddCommaIfNeeded(w)
		w = append(w, `"compact_journal":true`...)
	}
	return append(w, '}')
}

func (item *StatshouseGetMetrics3) MarshalJSON() ([]byte, error) {
	return item.WriteJSON(nil), nil
}

func (item *StatshouseGetMetrics3) UnmarshalJSON(b []byte) error {
	if err := item.ReadJSON(true, &basictl.JsonLexer{Data: b}); err != nil {
		return ErrorInvalidJSON("statshouse.getMetrics3", err.Error())
	}
	return nil
}

type StatshouseGetMetrics3Bytes struct {
	FieldsMask uint32
	Header     StatshouseCommonProxyHeaderBytes
	FieldMask  uint32
	From       int64
	Limit      int64
	// ReturnIfEmpty (TrueType) // Conditional: item.FieldMask.3
	// NewJournal (TrueType) // Conditional: item.FieldMask.15
	// CompactJournal (TrueType) // Conditional: item.FieldMask.4
}

func (StatshouseGetMetrics3Bytes) TLName() string { return "statshouse.getMetrics3" }
func (StatshouseGetMetrics3Bytes) TLTag() uint32  { return 0x42855554 }

func (item *StatshouseGetMetrics3Bytes) SetReturnIfEmpty(v bool) {
	if v {
		item.FieldMask |= 1 << 3
	} else {
		item.FieldMask &^= 1 << 3
	}
}
func (item StatshouseGetMetrics3Bytes) IsSetReturnIfEmpty() bool { return item.FieldMask&(1<<3) != 0 }

func (item *StatshouseGetMetrics3Bytes) SetNewJournal(v bool) {
	if v {
		item.FieldMask |= 1 << 15
	} else {
		item.FieldMask &^= 1 << 15
	}
}
func (item StatshouseGetMetrics3Bytes) IsSetNewJournal() bool { return item.FieldMask&(1<<15) != 0 }

func (item *StatshouseGetMetrics3Bytes) SetCompactJournal(v bool) {
	if v {
		item.FieldMask |= 1 << 4
	} else {
		item.FieldMask &^= 1 << 4
	}
}
func (item StatshouseGetMetrics3Bytes) IsSetCompactJournal() bool { return item.FieldMask&(1<<4) != 0 }

func (item *StatshouseGetMetrics3Bytes) Reset() {
	item.FieldsMask = 0
	item.Header.Reset()
	item.FieldMask = 0
	item.From = 0
	item.Limit = 0
}

func (item *StatshouseGetMetrics3Bytes) Read(w []byte) (_ []byte, err error) {
	if w, err = basictl.NatRead(w, &item.FieldsMask); err != nil {
		return w, err
	}
	if w, err = item.Header.Read(w, item.FieldsMask); err != nil {
		return w, err
	}
	if w, err = basictl.NatRead(w, &item.FieldMask); err != nil {
		return w, err
	}
	if w, err = basictl.LongRead(w, &item.From); err != nil {
		return w, err
	}
	if w, err = basictl.LongRead(w, &item.Limit); err != nil {
		return w, err
	}
	return w, nil
}

// This method is general version of Write, use it instead!
func (item *StatshouseGetMetrics3Bytes) WriteGeneral(w []byte) (_ []byte, err error) {
	return item.Write(w), nil
}

func (item *StatshouseGetMetrics3Bytes) Write(w []byte) []byte {
	w = basictl.NatWrite(w, item.FieldsMask)
	w = item.Header.Write(w, item.FieldsMask)
	w = basictl.NatWrite(w, item.FieldMask)
	w = basictl.LongWrite(w, item.From)
	w = basictl.LongWrite(w, item.Limit)
	return w
}

func (item *StatshouseGetMetrics3Bytes) ReadBoxed(w []byte) (_ []byte, err error) {
	if w, err = basictl.NatReadExactTag(w, 0x42855554); err != nil {
		return w, err
	}
	return item.Read(w)
}

// This method is general version of WriteBoxed, use it instead!
func (item *StatshouseGetMetrics3Bytes) WriteBoxedGeneral(w []byte) (_ []byte, err error) {
	return item.WriteBoxed(w), nil
}

func (item *StatshouseGetMetrics3Bytes) WriteBoxed(w []byte) []byte {
	w = basictl.NatWrite(w, 0x42855554)
	return item.Write(w)
}

func (item *StatshouseGetMetrics3Bytes) ReadResult(w []byte, ret *MetadataGetJournalResponsenewBytes) (_ []byte, err error) {
	return ret.ReadBoxed(w, item.FieldsMask)
}

func (item *StatshouseGetMetrics3Bytes) WriteResult(w []byte, ret MetadataGetJournalResponsenewBytes) (_ []byte, err error) {
	w = ret.WriteBoxed(w, item.FieldsMask)
	return w, nil
}

func (item *StatshouseGetMetrics3Bytes) ReadResultJSON(legacyTypeNames bool, in *basictl.JsonLexer, ret *MetadataGetJournalResponsenewBytes) error {
	if err := ret.ReadJSON(legacyTypeNames, in, item.FieldsMask); err != nil {
		return err
	}
	return nil
}

func (item *StatshouseGetMetrics3Bytes) WriteResultJSON(w []byte, ret MetadataGetJournalResponsenewBytes) (_ []byte, err error) {
	return item.writeResultJSON(true, false, w, ret)
}

func (item *StatshouseGetMetrics3Bytes) writeResultJSON(newTypeNames bool, short bool, w []byte, ret MetadataGetJournalResponsenewBytes) (_ []byte, err error) {
	w = ret.WriteJSONOpt(newTypeNames, short, w, item.FieldsMask)
	return w, nil
}

func (item *StatshouseGetMetrics3Bytes) ReadResultWriteResultJSON(r []byte, w []byte) (_ []byte, _ []byte, err error) {
	var ret MetadataGetJournalResponsenewBytes
	if r, err = item.ReadResult(r, &ret); err != nil {
		return r, w, err
	}
	w, err = item.WriteResultJSON(w, ret)
	return r, w, err
}

func (item *StatshouseGetMetrics3Bytes) ReadResultWriteResultJSONOpt(newTypeNames bool, short bool, r []byte, w []byte) (_ []byte, _ []byte, err error) {
	var ret MetadataGetJournalResponsenewBytes
	if r, err = item.ReadResult(r, &ret); err != nil {
		return r, w, err
	}
	w, err = item.writeResultJSON(newTypeNames, short, w, ret)
	return r, w, err
}

func (item *StatshouseGetMetrics3Bytes) ReadResultJSONWriteResult(r []byte, w []byte) ([]byte, []byte, error) {
	var ret MetadataGetJournalResponsenewBytes
	err := item.ReadResultJSON(true, &basictl.JsonLexer{Data: r}, &ret)
	if err != nil {
		return r, w, err
	}
	w, err = item.WriteResult(w, ret)
	return r, w, err
}

func (item StatshouseGetMetrics3Bytes) String() string {
	return string(item.WriteJSON(nil))
}

func (item *StatshouseGetMetrics3Bytes) ReadJSON(legacyTypeNames bool, in *basictl.JsonLexer) error {
	var propFieldsMaskPresented bool
	var rawHeader []byte
	var propFieldMaskPresented bool
	var propFromPresented bool
	var propLimitPresented bool
	var trueTypeReturnIfEmptyPresented bool
	var trueTypeReturnIfEmptyValue bool
	var trueTypeNewJournalPresented bool
	var trueTypeNewJournalValue bool
	var trueTypeCompactJournalPresented bool
	var trueTypeCompactJournalValue bool

	if in != nil {
		in.Delim('{')
		if !in.Ok() {
			return in.Error()
		}
		for !in.IsDelim('}') {
			key := in.UnsafeFieldName(true)
			in.WantColon()
			switch key {
			case "fields_mask":
				if propFieldsMaskPresented {
					return ErrorInvalidJSONWithDuplicatingKeys("statshouse.getMetrics3", "fields_mask")
				}
				if err := Json2ReadUint32(in, &item.FieldsMask); err != nil {
					return err
				}
				propFieldsMaskPresented = true
			case "header":
				if rawHeader != nil {
					return ErrorInvalidJSONWithDuplicatingKeys("statshouse.getMetrics3", "header")
				}
				rawHeader = in.Raw()
				if !in.Ok() {
					return in.Error()
				}
			case "field_mask":
				if propFieldMaskPresented {
					return ErrorInvalidJSONWithDuplicatingKeys("statshouse.getMetrics3", "field_mask")
				}
				if err := Json2ReadUint32(in, &item.FieldMask); err != nil {
					return err
				}
				propFieldMaskPresented = true
			case "from":
				if propFromPresented {
					return ErrorInvalidJSONWithDuplicatingKeys("statshouse.getMetrics3", "from")
				}
				if err := Json2ReadInt64(in, &item.From); err != nil {
					return err
				}
				propFromPresented = true
			case "limit":
				if propLimitPresented {
					return ErrorInvalidJSONWithDuplicatingKeys("statshouse.getMetrics3", "limit")
				}
				if err := Json2ReadInt64(in, &item.Limit); err != nil {
					return err
				}
				propLimitPresented = true
			case "return_if_empty":
				if trueTypeReturnIfEmptyPresented {
					return ErrorInvalidJSONWithDuplicatingKeys("statshouse.getMetrics3", "return_if_empty")
				}
				if err := Json2ReadBool(in, &trueTypeReturnIfEmptyValue); err != nil {
					return err
				}
				trueTypeReturnIfEmptyPresented = true
			case "new_journal":
				if trueTypeNewJournalPresented {
					return ErrorInvalidJSONWithDuplicatingKeys("statshouse.getMetrics3", "new_journal")
				}
				if err := Json2ReadBool(in, &trueTypeNewJournalValue); err != nil {
					return err
				}
				trueTypeNewJournalPresented = true
			case "compact_journal":
				if trueTypeCompactJournalPresented {
					return ErrorInvalidJSONWithDuplicatingKeys("statshouse.getMetrics3", "compact_journal")
				}
				if err := Json2ReadBool(in, &trueTypeCompactJournalValue); err != nil {
					return err
				}
				trueTypeCompactJournalPresented = true
			default:
				return ErrorInvalidJSONExcessElement("statshouse.getMetrics3", key)
			}
			in.WantComma()
		}
		in.Delim('}')
		if !in.Ok() {
			return in.Error()
		}
	}
	if !propFieldsMaskPresented {
		item.FieldsMask = 0
	}
	if !propFieldMaskPresented {
		item.FieldMask = 0
	}
	if !propFromPresented {
		item.From = 0
	}
	if !propLimitPresented {
		item.Limit = 0
	}
	if trueTypeReturnIfEmptyPresented {
		if trueTypeReturnIfEmptyValue {
			item.FieldMask |= 1 << 3
		}
	}
	if trueTypeNewJournalPresented {
		if trueTypeNewJournalValue {
			item.FieldMask |= 1 << 15
		}
	}
	if trueTypeCompactJournalPresented {
		if trueTypeCompactJournalValue {
			item.FieldMask |= 1 << 4
		}
	}
	var inHeaderPointer *basictl.JsonLexer
	inHeader := basictl.JsonLexer{Data: rawHeader}
	if rawHeader != nil {
		inHeaderPointer = &inHeader
	}
	if err := item.Header.ReadJSON(legacyTypeNames, inHeaderPointer, item.FieldsMask); err != nil {
		return err
	}

	// tries to set bit to zero if it is 1
	if trueTypeReturnIfEmptyPresented && !trueTypeReturnIfEmptyValue && (item.FieldMask&(1<<3) != 0) {
		return ErrorInvalidJSON("statshouse.getMetrics3", "fieldmask bit field_mask.2 is indefinite because of the contradictions in values")
	}
	// tries to set bit to zero if it is 1
	if trueTypeNewJournalPresented && !trueTypeNewJournalValue && (item.FieldMask&(1<<15) != 0) {
		return ErrorInvalidJSON("statshouse.getMetrics3", "fieldmask bit field_mask.2 is indefinite because of the contradictions in values")
	}
	// tries to set bit to zero if it is 1
	if trueTypeCompactJournalPresented && !trueTypeCompactJournalValue && (item.FieldMask&(1<<4) != 0) {
		return ErrorInvalidJSON("statshouse.getMetrics3", "fieldmask bit field_mask.2 is indefinite because of the contradictions in values")
	}
	return nil
}

// This method is general version of WriteJSON, use it instead!
func (item *StatshouseGetMetrics3Bytes) WriteJSONGeneral(w []byte) (_ []byte, err error) {
	return item.WriteJSONOpt(true, false, w), nil
}

func (item *StatshouseGetMetrics3Bytes) WriteJSON(w []byte) []byte {
	return item.WriteJSONOpt(true, false, w)
}
func (item *StatshouseGetMetrics3Bytes) WriteJSONOpt(newTypeNames bool, short bool, w []byte) []byte {
	w = append(w, '{')
	backupIndexFieldsMask := len(w)
	w = basictl.JSONAddCommaIfNeeded(w)
	w = append(w, `"fields_mask":`...)
	w = basictl.JSONWriteUint32(w, item.FieldsMask)
	if (item.FieldsMask != 0) == false {
		w = w[:backupIndexFieldsMask]
	}
	w = basictl.JSONAddCommaIfNeeded(w)
	w = append(w, `"header":`...)
	w = item.Header.WriteJSONOpt(newTypeNames, short, w, item.FieldsMask)
	backupIndexFieldMask := len(w)
	w = basictl.JSONAddCommaIfNeeded(w)
	w = append(w, `"field_mask":`...)
	w = basictl.JSONWriteUint32(w, item.FieldMask)
	if (item.FieldMask != 0) == false {
		w = w[:backupIndexFieldMask]
	}
	backupIndexFrom := len(w)
	w = basictl.JSONAddCommaIfNeeded(w)
	w = append(w, `"from":`...)
	w = basictl.JSONWriteInt64(w, item.From)
	if (item.From != 0) == false {
		w = w[:backupIndexFrom]
	}
	backupIndexLimit := len(w)
	w = basictl.JSONAddCommaIfNeeded(w)
	w = append(w, `"limit":`...)
	w = basictl.JSONWriteInt64(w, item.Limit)
	if (item.Limit != 0) == false {
		w = w[:backupIndexLimit]
	}
	if item.FieldMask&(1<<3) != 0 {
		w = basictl.JSONAddCommaIfNeeded(w)
		w = append(w, `"return_if_empty":true`...)
	}
	if item.FieldMask&(1<<15) != 0 {
		w = basictl.JSONAddCommaIfNeeded(w)
		w = append(w, `"new_journal":true`...)
	}
	if item.FieldMask&(1<<4) != 0 {
		w = basictl.JSONAddCommaIfNeeded(w)
		w = append(w, `"compact_journal":true`...)
	}
	return append(w, '}')
}

func (item *StatshouseGetMetrics3Bytes) MarshalJSON() ([]byte, error) {
	return item.WriteJSON(nil), nil
}

func (item *StatshouseGetMetrics3Bytes) UnmarshalJSON(b []byte) error {
	if err := item.ReadJSON(true, &basictl.JsonLexer{Data: b}); err != nil {
		return ErrorInvalidJSON("statshouse.getMetrics3", err.Error())
	}
	return nil
}
