// Copyright 2025 V Kontakte LLC
//
// This Source Code Form is subject to the terms of the Mozilla Public
// License, v. 2.0. If a copy of the MPL was not distributed with this
// file, You can obtain one at https://mozilla.org/MPL/2.0/.

// Code generated by tl2gen; DO NOT EDIT.
package internal

import (
	"github.com/VKCOM/statshouse/internal/vkgo/basictl"
)

var _ = basictl.NatWrite

type StatshouseSendKeepAlive3 struct {
	FieldsMask uint32
	Header     StatshouseCommonProxyHeader
}

func (StatshouseSendKeepAlive3) TLName() string { return "statshouse.sendKeepAlive3" }
func (StatshouseSendKeepAlive3) TLTag() uint32  { return 0x4285ff54 }

func (item *StatshouseSendKeepAlive3) Reset() {
	item.FieldsMask = 0
	item.Header.Reset()
}

func (item *StatshouseSendKeepAlive3) FillRandom(rg *basictl.RandGenerator) {
	item.FieldsMask = basictl.RandomFieldMask(rg, 0b11110000000000000000000000000000)
	item.Header.FillRandom(rg, item.FieldsMask)
}

func (item *StatshouseSendKeepAlive3) ReadTL1(w []byte) (_ []byte, err error) {
	if w, err = basictl.NatRead(w, &item.FieldsMask); err != nil {
		return w, err
	}
	return item.Header.ReadTL1(w, item.FieldsMask)
}

func (item *StatshouseSendKeepAlive3) WriteTL1General(w []byte) (_ []byte, err error) {
	return item.WriteTL1(w), nil
}

func (item *StatshouseSendKeepAlive3) WriteTL1(w []byte) []byte {
	w = basictl.NatWrite(w, item.FieldsMask)
	w = item.Header.WriteTL1(w, item.FieldsMask)
	return w
}

func (item *StatshouseSendKeepAlive3) ReadTL1Boxed(w []byte) (_ []byte, err error) {
	if w, err = basictl.NatReadExactTag(w, 0x4285ff54); err != nil {
		return w, err
	}
	return item.ReadTL1(w)
}

func (item *StatshouseSendKeepAlive3) WriteTL1BoxedGeneral(w []byte) (_ []byte, err error) {
	return item.WriteTL1Boxed(w), nil
}

func (item *StatshouseSendKeepAlive3) WriteTL1Boxed(w []byte) []byte {
	w = basictl.NatWrite(w, 0x4285ff54)
	return item.WriteTL1(w)
}

func (item *StatshouseSendKeepAlive3) ReadResultTL1(w []byte, ret *StatshouseSendSourceBucket3Response) (_ []byte, err error) {
	return ret.ReadTL1Boxed(w)
}

func (item *StatshouseSendKeepAlive3) WriteResultTL1(w []byte, ret StatshouseSendSourceBucket3Response) (_ []byte, err error) {
	w = ret.WriteTL1Boxed(w)
	return w, nil
}

func (item *StatshouseSendKeepAlive3) ReadResultJSON(legacyTypeNames bool, in *basictl.JsonLexer, ret *StatshouseSendSourceBucket3Response) error {
	tctx := &basictl.JSONReadContext{LegacyTypeNames: legacyTypeNames}
	if err := ret.ReadJSONGeneral(tctx, in); err != nil {
		return err
	}
	return nil
}

func (item *StatshouseSendKeepAlive3) WriteResultJSON(w []byte, ret StatshouseSendSourceBucket3Response) (_ []byte, err error) {
	tctx := basictl.JSONWriteContext{}
	return item.writeResultJSON(&tctx, w, ret)
}

func (item *StatshouseSendKeepAlive3) writeResultJSON(tctx *basictl.JSONWriteContext, w []byte, ret StatshouseSendSourceBucket3Response) (_ []byte, err error) {
	w = ret.WriteJSONOpt(tctx, w)
	return w, nil
}

func (item *StatshouseSendKeepAlive3) FillRandomResultTL1(rg *basictl.RandGenerator, w []byte) ([]byte, error) {
	var ret StatshouseSendSourceBucket3Response
	ret.FillRandom(rg)
	return item.WriteResultTL1(w, ret)
}

func (item *StatshouseSendKeepAlive3) ReadResultTL1WriteResultJSON(tctx *basictl.JSONWriteContext, r []byte, w []byte) (_ []byte, _ []byte, err error) {
	var ret StatshouseSendSourceBucket3Response
	if r, err = item.ReadResultTL1(r, &ret); err != nil {
		return r, w, err
	}
	w, err = item.writeResultJSON(tctx, w, ret)
	return r, w, err
}

func (item *StatshouseSendKeepAlive3) ReadResultJSONWriteResultTL1(r []byte, w []byte) (_ []byte, _ []byte, err error) {
	var ret StatshouseSendSourceBucket3Response
	if err = item.ReadResultJSON(true, &basictl.JsonLexer{Data: r}, &ret); err != nil {
		return r, w, err
	}
	w, err = item.WriteResultTL1(w, ret)
	return r, w, err
}

func (item *StatshouseSendKeepAlive3) ReadResultTL1WriteResultTL2(tctx *basictl.TL2WriteContext, r []byte, w []byte) (_ []byte, _ []byte, err error) {
	return r, w, ErrorTL2SerializersNotGenerated("statshouse.sendKeepAlive3")
}

func (item *StatshouseSendKeepAlive3) ReadResultTL2WriteResultTL1(tctx *basictl.TL2ReadContext, r []byte, w []byte) (_ []byte, _ []byte, err error) {
	return r, w, ErrorTL2SerializersNotGenerated("statshouse.sendKeepAlive3")
}

func (item *StatshouseSendKeepAlive3) ReadResultTL2WriteResultJSON(tctx *basictl.TL2ReadContext, jctx *basictl.JSONWriteContext, r []byte, w []byte) (_ []byte, _ []byte, err error) {
	return r, w, ErrorTL2SerializersNotGenerated("statshouse.sendKeepAlive3")
}

func (item *StatshouseSendKeepAlive3) ReadResultJSONWriteResultTL2(tctx *basictl.TL2WriteContext, r []byte, w []byte) (_ []byte, _ []byte, err error) {
	return r, w, ErrorTL2SerializersNotGenerated("statshouse.sendKeepAlive3")
}

func (item StatshouseSendKeepAlive3) String() string {
	return string(item.WriteJSON(nil))
}

func (item *StatshouseSendKeepAlive3) ReadJSON(legacyTypeNames bool, in *basictl.JsonLexer) error {
	tctx := basictl.JSONReadContext{LegacyTypeNames: legacyTypeNames}
	return item.ReadJSONGeneral(&tctx, in)
}

func (item *StatshouseSendKeepAlive3) ReadJSONGeneral(tctx *basictl.JSONReadContext, in *basictl.JsonLexer) error {
	var propFieldsMaskPresented bool
	var propHeaderPresented bool
	var rawHeader []byte
	if in != nil {
		in.Delim('{')
		if !in.Ok() {
			return in.Error()
		}
		for !in.IsDelim('}') {
			key := in.UnsafeFieldName(true)
			in.WantColon()
			switch key {
			case "fields_mask":
				if propFieldsMaskPresented {
					return ErrorInvalidJSONWithDuplicatingKeys("statshouse.sendKeepAlive3", "fields_mask")
				}
				propFieldsMaskPresented = true
				if err := Json2ReadUint32(in, &item.FieldsMask); err != nil {
					return err
				}
			case "header":
				if propHeaderPresented {
					return ErrorInvalidJSONWithDuplicatingKeys("statshouse.sendKeepAlive3", "header")
				}
				propHeaderPresented = true
				rawHeader = in.Raw()
				if !in.Ok() {
					return in.Error()
				}
			default:
				return ErrorInvalidJSONExcessElement("statshouse.sendKeepAlive3", key)
			}
			in.WantComma()
		}
		in.Delim('}')
		if !in.Ok() {
			return in.Error()
		}
	}
	if !propFieldsMaskPresented {
		item.FieldsMask = 0
	}
	if propHeaderPresented {
		inHeader := &basictl.JsonLexer{Data: rawHeader}
		if err := item.Header.ReadJSONGeneral(tctx, inHeader, item.FieldsMask); err != nil {
			return err
		}
	}
	if !propHeaderPresented {
		if err := item.Header.ReadJSONGeneral(tctx, nil, item.FieldsMask); err != nil {
			return err
		}
	}
	return nil
}

// This method is general version of WriteJSON, use it instead!
func (item *StatshouseSendKeepAlive3) WriteJSONGeneral(tctx *basictl.JSONWriteContext, w []byte) (_ []byte, err error) {
	return item.WriteJSONOpt(tctx, w), nil
}

func (item *StatshouseSendKeepAlive3) WriteJSON(w []byte) []byte {
	tctx := basictl.JSONWriteContext{}
	return item.WriteJSONOpt(&tctx, w)
}
func (item *StatshouseSendKeepAlive3) WriteJSONOpt(tctx *basictl.JSONWriteContext, w []byte) []byte {
	w = append(w, '{')
	backupIndexFieldsMask := len(w)
	w = basictl.JSONAddCommaIfNeeded(w)
	w = append(w, `"fields_mask":`...)
	w = basictl.JSONWriteUint32(w, item.FieldsMask)
	if !(item.FieldsMask != 0) {
		w = w[:backupIndexFieldsMask]
	}
	w = basictl.JSONAddCommaIfNeeded(w)
	w = append(w, `"header":`...)
	w = item.Header.WriteJSONOpt(tctx, w, item.FieldsMask)
	return append(w, '}')
}

func (item *StatshouseSendKeepAlive3) MarshalJSON() ([]byte, error) {
	return item.WriteJSON(nil), nil
}

func (item *StatshouseSendKeepAlive3) UnmarshalJSON(b []byte) error {
	if err := item.ReadJSON(true, &basictl.JsonLexer{Data: b}); err != nil {
		return ErrorInvalidJSON("statshouse.sendKeepAlive3", err.Error())
	}
	return nil
}

func (item *StatshouseSendKeepAlive3) WriteTL2(w []byte, ctx *basictl.TL2WriteContext) []byte {
	panic(ErrorTL2SerializersNotGenerated("statshouse.sendKeepAlive3"))
}

func (item *StatshouseSendKeepAlive3) ReadTL2(r []byte, ctx *basictl.TL2ReadContext) (_ []byte, err error) {
	return r, ErrorTL2SerializersNotGenerated("statshouse.sendKeepAlive3")
}

type StatshouseSendKeepAlive3Bytes struct {
	FieldsMask uint32
	Header     StatshouseCommonProxyHeaderBytes
}

func (StatshouseSendKeepAlive3Bytes) TLName() string { return "statshouse.sendKeepAlive3" }
func (StatshouseSendKeepAlive3Bytes) TLTag() uint32  { return 0x4285ff54 }

func (item *StatshouseSendKeepAlive3Bytes) Reset() {
	item.FieldsMask = 0
	item.Header.Reset()
}

func (item *StatshouseSendKeepAlive3Bytes) FillRandom(rg *basictl.RandGenerator) {
	item.FieldsMask = basictl.RandomFieldMask(rg, 0b11110000000000000000000000000000)
	item.Header.FillRandom(rg, item.FieldsMask)
}

func (item *StatshouseSendKeepAlive3Bytes) ReadTL1(w []byte) (_ []byte, err error) {
	if w, err = basictl.NatRead(w, &item.FieldsMask); err != nil {
		return w, err
	}
	return item.Header.ReadTL1(w, item.FieldsMask)
}

func (item *StatshouseSendKeepAlive3Bytes) WriteTL1General(w []byte) (_ []byte, err error) {
	return item.WriteTL1(w), nil
}

func (item *StatshouseSendKeepAlive3Bytes) WriteTL1(w []byte) []byte {
	w = basictl.NatWrite(w, item.FieldsMask)
	w = item.Header.WriteTL1(w, item.FieldsMask)
	return w
}

func (item *StatshouseSendKeepAlive3Bytes) ReadTL1Boxed(w []byte) (_ []byte, err error) {
	if w, err = basictl.NatReadExactTag(w, 0x4285ff54); err != nil {
		return w, err
	}
	return item.ReadTL1(w)
}

func (item *StatshouseSendKeepAlive3Bytes) WriteTL1BoxedGeneral(w []byte) (_ []byte, err error) {
	return item.WriteTL1Boxed(w), nil
}

func (item *StatshouseSendKeepAlive3Bytes) WriteTL1Boxed(w []byte) []byte {
	w = basictl.NatWrite(w, 0x4285ff54)
	return item.WriteTL1(w)
}

func (item *StatshouseSendKeepAlive3Bytes) ReadResultTL1(w []byte, ret *StatshouseSendSourceBucket3ResponseBytes) (_ []byte, err error) {
	return ret.ReadTL1Boxed(w)
}

func (item *StatshouseSendKeepAlive3Bytes) WriteResultTL1(w []byte, ret StatshouseSendSourceBucket3ResponseBytes) (_ []byte, err error) {
	w = ret.WriteTL1Boxed(w)
	return w, nil
}

func (item *StatshouseSendKeepAlive3Bytes) ReadResultJSON(legacyTypeNames bool, in *basictl.JsonLexer, ret *StatshouseSendSourceBucket3ResponseBytes) error {
	tctx := &basictl.JSONReadContext{LegacyTypeNames: legacyTypeNames}
	if err := ret.ReadJSONGeneral(tctx, in); err != nil {
		return err
	}
	return nil
}

func (item *StatshouseSendKeepAlive3Bytes) WriteResultJSON(w []byte, ret StatshouseSendSourceBucket3ResponseBytes) (_ []byte, err error) {
	tctx := basictl.JSONWriteContext{}
	return item.writeResultJSON(&tctx, w, ret)
}

func (item *StatshouseSendKeepAlive3Bytes) writeResultJSON(tctx *basictl.JSONWriteContext, w []byte, ret StatshouseSendSourceBucket3ResponseBytes) (_ []byte, err error) {
	w = ret.WriteJSONOpt(tctx, w)
	return w, nil
}

func (item *StatshouseSendKeepAlive3Bytes) FillRandomResultTL1(rg *basictl.RandGenerator, w []byte) ([]byte, error) {
	var ret StatshouseSendSourceBucket3ResponseBytes
	ret.FillRandom(rg)
	return item.WriteResultTL1(w, ret)
}

func (item *StatshouseSendKeepAlive3Bytes) ReadResultTL1WriteResultJSON(tctx *basictl.JSONWriteContext, r []byte, w []byte) (_ []byte, _ []byte, err error) {
	var ret StatshouseSendSourceBucket3ResponseBytes
	if r, err = item.ReadResultTL1(r, &ret); err != nil {
		return r, w, err
	}
	w, err = item.writeResultJSON(tctx, w, ret)
	return r, w, err
}

func (item *StatshouseSendKeepAlive3Bytes) ReadResultJSONWriteResultTL1(r []byte, w []byte) (_ []byte, _ []byte, err error) {
	var ret StatshouseSendSourceBucket3ResponseBytes
	if err = item.ReadResultJSON(true, &basictl.JsonLexer{Data: r}, &ret); err != nil {
		return r, w, err
	}
	w, err = item.WriteResultTL1(w, ret)
	return r, w, err
}

func (item *StatshouseSendKeepAlive3Bytes) ReadResultTL1WriteResultTL2(tctx *basictl.TL2WriteContext, r []byte, w []byte) (_ []byte, _ []byte, err error) {
	return r, w, ErrorTL2SerializersNotGenerated("statshouse.sendKeepAlive3")
}

func (item *StatshouseSendKeepAlive3Bytes) ReadResultTL2WriteResultTL1(tctx *basictl.TL2ReadContext, r []byte, w []byte) (_ []byte, _ []byte, err error) {
	return r, w, ErrorTL2SerializersNotGenerated("statshouse.sendKeepAlive3")
}

func (item *StatshouseSendKeepAlive3Bytes) ReadResultTL2WriteResultJSON(tctx *basictl.TL2ReadContext, jctx *basictl.JSONWriteContext, r []byte, w []byte) (_ []byte, _ []byte, err error) {
	return r, w, ErrorTL2SerializersNotGenerated("statshouse.sendKeepAlive3")
}

func (item *StatshouseSendKeepAlive3Bytes) ReadResultJSONWriteResultTL2(tctx *basictl.TL2WriteContext, r []byte, w []byte) (_ []byte, _ []byte, err error) {
	return r, w, ErrorTL2SerializersNotGenerated("statshouse.sendKeepAlive3")
}

func (item StatshouseSendKeepAlive3Bytes) String() string {
	return string(item.WriteJSON(nil))
}

func (item *StatshouseSendKeepAlive3Bytes) ReadJSON(legacyTypeNames bool, in *basictl.JsonLexer) error {
	tctx := basictl.JSONReadContext{LegacyTypeNames: legacyTypeNames}
	return item.ReadJSONGeneral(&tctx, in)
}

func (item *StatshouseSendKeepAlive3Bytes) ReadJSONGeneral(tctx *basictl.JSONReadContext, in *basictl.JsonLexer) error {
	var propFieldsMaskPresented bool
	var propHeaderPresented bool
	var rawHeader []byte
	if in != nil {
		in.Delim('{')
		if !in.Ok() {
			return in.Error()
		}
		for !in.IsDelim('}') {
			key := in.UnsafeFieldName(true)
			in.WantColon()
			switch key {
			case "fields_mask":
				if propFieldsMaskPresented {
					return ErrorInvalidJSONWithDuplicatingKeys("statshouse.sendKeepAlive3", "fields_mask")
				}
				propFieldsMaskPresented = true
				if err := Json2ReadUint32(in, &item.FieldsMask); err != nil {
					return err
				}
			case "header":
				if propHeaderPresented {
					return ErrorInvalidJSONWithDuplicatingKeys("statshouse.sendKeepAlive3", "header")
				}
				propHeaderPresented = true
				rawHeader = in.Raw()
				if !in.Ok() {
					return in.Error()
				}
			default:
				return ErrorInvalidJSONExcessElement("statshouse.sendKeepAlive3", key)
			}
			in.WantComma()
		}
		in.Delim('}')
		if !in.Ok() {
			return in.Error()
		}
	}
	if !propFieldsMaskPresented {
		item.FieldsMask = 0
	}
	if propHeaderPresented {
		inHeader := &basictl.JsonLexer{Data: rawHeader}
		if err := item.Header.ReadJSONGeneral(tctx, inHeader, item.FieldsMask); err != nil {
			return err
		}
	}
	if !propHeaderPresented {
		if err := item.Header.ReadJSONGeneral(tctx, nil, item.FieldsMask); err != nil {
			return err
		}
	}
	return nil
}

// This method is general version of WriteJSON, use it instead!
func (item *StatshouseSendKeepAlive3Bytes) WriteJSONGeneral(tctx *basictl.JSONWriteContext, w []byte) (_ []byte, err error) {
	return item.WriteJSONOpt(tctx, w), nil
}

func (item *StatshouseSendKeepAlive3Bytes) WriteJSON(w []byte) []byte {
	tctx := basictl.JSONWriteContext{}
	return item.WriteJSONOpt(&tctx, w)
}
func (item *StatshouseSendKeepAlive3Bytes) WriteJSONOpt(tctx *basictl.JSONWriteContext, w []byte) []byte {
	w = append(w, '{')
	backupIndexFieldsMask := len(w)
	w = basictl.JSONAddCommaIfNeeded(w)
	w = append(w, `"fields_mask":`...)
	w = basictl.JSONWriteUint32(w, item.FieldsMask)
	if !(item.FieldsMask != 0) {
		w = w[:backupIndexFieldsMask]
	}
	w = basictl.JSONAddCommaIfNeeded(w)
	w = append(w, `"header":`...)
	w = item.Header.WriteJSONOpt(tctx, w, item.FieldsMask)
	return append(w, '}')
}

func (item *StatshouseSendKeepAlive3Bytes) MarshalJSON() ([]byte, error) {
	return item.WriteJSON(nil), nil
}

func (item *StatshouseSendKeepAlive3Bytes) UnmarshalJSON(b []byte) error {
	if err := item.ReadJSON(true, &basictl.JsonLexer{Data: b}); err != nil {
		return ErrorInvalidJSON("statshouse.sendKeepAlive3", err.Error())
	}
	return nil
}

func (item *StatshouseSendKeepAlive3Bytes) WriteTL2(w []byte, ctx *basictl.TL2WriteContext) []byte {
	panic(ErrorTL2SerializersNotGenerated("statshouse.sendKeepAlive3"))
}

func (item *StatshouseSendKeepAlive3Bytes) ReadTL2(r []byte, ctx *basictl.TL2ReadContext) (_ []byte, err error) {
	return r, ErrorTL2SerializersNotGenerated("statshouse.sendKeepAlive3")
}
