// Copyright 2025 V Kontakte LLC
//
// This Source Code Form is subject to the terms of the Mozilla Public
// License, v. 2.0. If a copy of the MPL was not distributed with this
// file, You can obtain one at https://mozilla.org/MPL/2.0/.

// Code generated by tl2gen; DO NOT EDIT.
package internal

import (
	"github.com/VKCOM/statshouse/internal/vkgo/basictl"
)

var _ = basictl.NatWrite

type StatshouseAddMetricsBatch struct {
	FieldsMask uint32
	Host       string // Conditional: item.FieldsMask.0
	Metrics    []StatshouseMetric
}

func (StatshouseAddMetricsBatch) TLName() string { return "statshouse.addMetricsBatch" }
func (StatshouseAddMetricsBatch) TLTag() uint32  { return 0x56580239 }

func (item *StatshouseAddMetricsBatch) SetHost(v string) {
	item.Host = v
	item.FieldsMask |= 1 << 0
}
func (item *StatshouseAddMetricsBatch) ClearHost() {
	item.Host = ""
	item.FieldsMask &^= 1 << 0
}
func (item *StatshouseAddMetricsBatch) IsSetHost() bool { return item.FieldsMask&(1<<0) != 0 }

func (item *StatshouseAddMetricsBatch) Reset() {
	item.FieldsMask = 0
	item.Host = ""
	item.Metrics = item.Metrics[:0]
}

func (item *StatshouseAddMetricsBatch) FillRandom(rg *basictl.RandGenerator) {
	item.FieldsMask = basictl.RandomFieldMask(rg, 0b1)
	if item.FieldsMask&(1<<0) != 0 {
		item.Host = basictl.RandomString(rg)
	} else {
		item.Host = ""
	}
	BuiltinVectorStatshouseMetricFillRandom(rg, &item.Metrics)
}

func (item *StatshouseAddMetricsBatch) ReadTL1(w []byte) (_ []byte, err error) {
	if w, err = basictl.NatRead(w, &item.FieldsMask); err != nil {
		return w, err
	}
	if item.FieldsMask&(1<<0) != 0 {
		if w, err = basictl.StringRead(w, &item.Host); err != nil {
			return w, err
		}
	} else {
		item.Host = ""
	}
	return BuiltinVectorStatshouseMetricReadTL1(w, &item.Metrics)
}

func (item *StatshouseAddMetricsBatch) WriteTL1General(w []byte) (_ []byte, err error) {
	return item.WriteTL1(w), nil
}

func (item *StatshouseAddMetricsBatch) WriteTL1(w []byte) []byte {
	w = basictl.NatWrite(w, item.FieldsMask)
	if item.FieldsMask&(1<<0) != 0 {
		w = basictl.StringWrite(w, item.Host)
	}
	w = BuiltinVectorStatshouseMetricWriteTL1(w, item.Metrics)
	return w
}

func (item *StatshouseAddMetricsBatch) ReadTL1Boxed(w []byte) (_ []byte, err error) {
	if w, err = basictl.NatReadExactTag(w, 0x56580239); err != nil {
		return w, err
	}
	return item.ReadTL1(w)
}

func (item *StatshouseAddMetricsBatch) WriteTL1BoxedGeneral(w []byte) (_ []byte, err error) {
	return item.WriteTL1Boxed(w), nil
}

func (item *StatshouseAddMetricsBatch) WriteTL1Boxed(w []byte) []byte {
	w = basictl.NatWrite(w, 0x56580239)
	return item.WriteTL1(w)
}

func (item *StatshouseAddMetricsBatch) ReadResultTL1(w []byte, ret *True) (_ []byte, err error) {
	return ret.ReadTL1Boxed(w)
}

func (item *StatshouseAddMetricsBatch) WriteResultTL1(w []byte, ret True) (_ []byte, err error) {
	w = ret.WriteTL1Boxed(w)
	return w, nil
}

func (item *StatshouseAddMetricsBatch) ReadResultJSON(legacyTypeNames bool, in *basictl.JsonLexer, ret *True) error {
	tctx := &basictl.JSONReadContext{LegacyTypeNames: legacyTypeNames}
	if err := ret.ReadJSONGeneral(tctx, in); err != nil {
		return err
	}
	return nil
}

func (item *StatshouseAddMetricsBatch) WriteResultJSON(w []byte, ret True) (_ []byte, err error) {
	tctx := basictl.JSONWriteContext{}
	return item.writeResultJSON(&tctx, w, ret)
}

func (item *StatshouseAddMetricsBatch) writeResultJSON(tctx *basictl.JSONWriteContext, w []byte, ret True) (_ []byte, err error) {
	w = ret.WriteJSONOpt(tctx, w)
	return w, nil
}

func (item *StatshouseAddMetricsBatch) FillRandomResultTL1(rg *basictl.RandGenerator, w []byte) ([]byte, error) {
	var ret True
	ret.FillRandom(rg)
	return item.WriteResultTL1(w, ret)
}

func (item *StatshouseAddMetricsBatch) ReadResultTL1WriteResultJSON(tctx *basictl.JSONWriteContext, r []byte, w []byte) (_ []byte, _ []byte, err error) {
	var ret True
	if r, err = item.ReadResultTL1(r, &ret); err != nil {
		return r, w, err
	}
	w, err = item.writeResultJSON(tctx, w, ret)
	return r, w, err
}

func (item *StatshouseAddMetricsBatch) ReadResultJSONWriteResultTL1(r []byte, w []byte) (_ []byte, _ []byte, err error) {
	var ret True
	if err = item.ReadResultJSON(true, &basictl.JsonLexer{Data: r}, &ret); err != nil {
		return r, w, err
	}
	w, err = item.WriteResultTL1(w, ret)
	return r, w, err
}

func (item *StatshouseAddMetricsBatch) ReadResultTL1WriteResultTL2(tctx *basictl.TL2WriteContext, r []byte, w []byte) (_ []byte, _ []byte, err error) {
	return r, w, ErrorTL2SerializersNotGenerated("statshouse.addMetricsBatch")
}

func (item *StatshouseAddMetricsBatch) ReadResultTL2WriteResultTL1(tctx *basictl.TL2ReadContext, r []byte, w []byte) (_ []byte, _ []byte, err error) {
	return r, w, ErrorTL2SerializersNotGenerated("statshouse.addMetricsBatch")
}

func (item *StatshouseAddMetricsBatch) ReadResultTL2WriteResultJSON(tctx *basictl.TL2ReadContext, jctx *basictl.JSONWriteContext, r []byte, w []byte) (_ []byte, _ []byte, err error) {
	return r, w, ErrorTL2SerializersNotGenerated("statshouse.addMetricsBatch")
}

func (item *StatshouseAddMetricsBatch) ReadResultJSONWriteResultTL2(tctx *basictl.TL2WriteContext, r []byte, w []byte) (_ []byte, _ []byte, err error) {
	return r, w, ErrorTL2SerializersNotGenerated("statshouse.addMetricsBatch")
}

func (item StatshouseAddMetricsBatch) String() string {
	return string(item.WriteJSON(nil))
}

func (item *StatshouseAddMetricsBatch) ReadJSON(legacyTypeNames bool, in *basictl.JsonLexer) error {
	tctx := basictl.JSONReadContext{LegacyTypeNames: legacyTypeNames}
	return item.ReadJSONGeneral(&tctx, in)
}

func (item *StatshouseAddMetricsBatch) ReadJSONGeneral(tctx *basictl.JSONReadContext, in *basictl.JsonLexer) error {
	var propFieldsMaskPresented bool
	var propHostPresented bool
	var propMetricsPresented bool
	if in != nil {
		in.Delim('{')
		if !in.Ok() {
			return in.Error()
		}
		for !in.IsDelim('}') {
			key := in.UnsafeFieldName(true)
			in.WantColon()
			switch key {
			case "fields_mask":
				if propFieldsMaskPresented {
					return ErrorInvalidJSONWithDuplicatingKeys("statshouse.addMetricsBatch", "fields_mask")
				}
				propFieldsMaskPresented = true
				if err := Json2ReadUint32(in, &item.FieldsMask); err != nil {
					return err
				}
			case "host":
				if propHostPresented {
					return ErrorInvalidJSONWithDuplicatingKeys("statshouse.addMetricsBatch", "host")
				}
				propHostPresented = true
				if err := Json2ReadString(in, &item.Host); err != nil {
					return err
				}
			case "metrics":
				if propMetricsPresented {
					return ErrorInvalidJSONWithDuplicatingKeys("statshouse.addMetricsBatch", "metrics")
				}
				propMetricsPresented = true
				if err := BuiltinVectorStatshouseMetricReadJSONGeneral(tctx, in, &item.Metrics); err != nil {
					return err
				}
			default:
				return ErrorInvalidJSONExcessElement("statshouse.addMetricsBatch", key)
			}
			in.WantComma()
		}
		in.Delim('}')
		if !in.Ok() {
			return in.Error()
		}
	}
	if !propFieldsMaskPresented {
		item.FieldsMask = 0
	}
	if !propHostPresented {
		item.Host = ""
	}
	if !propMetricsPresented {
		item.Metrics = item.Metrics[:0]
	}
	if propHostPresented {
		item.FieldsMask |= 1 << 0
	}
	return nil
}

// This method is general version of WriteJSON, use it instead!
func (item *StatshouseAddMetricsBatch) WriteJSONGeneral(tctx *basictl.JSONWriteContext, w []byte) (_ []byte, err error) {
	return item.WriteJSONOpt(tctx, w), nil
}

func (item *StatshouseAddMetricsBatch) WriteJSON(w []byte) []byte {
	tctx := basictl.JSONWriteContext{}
	return item.WriteJSONOpt(&tctx, w)
}
func (item *StatshouseAddMetricsBatch) WriteJSONOpt(tctx *basictl.JSONWriteContext, w []byte) []byte {
	w = append(w, '{')
	backupIndexFieldsMask := len(w)
	w = basictl.JSONAddCommaIfNeeded(w)
	w = append(w, `"fields_mask":`...)
	w = basictl.JSONWriteUint32(w, item.FieldsMask)
	if !(item.FieldsMask != 0) {
		w = w[:backupIndexFieldsMask]
	}
	if item.FieldsMask&(1<<0) != 0 {
		w = basictl.JSONAddCommaIfNeeded(w)
		w = append(w, `"host":`...)
		w = basictl.JSONWriteString(w, item.Host)
	}
	backupIndexMetrics := len(w)
	w = basictl.JSONAddCommaIfNeeded(w)
	w = append(w, `"metrics":`...)
	w = BuiltinVectorStatshouseMetricWriteJSONOpt(tctx, w, item.Metrics)
	if !(len(item.Metrics) != 0) {
		w = w[:backupIndexMetrics]
	}
	return append(w, '}')
}

func (item *StatshouseAddMetricsBatch) MarshalJSON() ([]byte, error) {
	return item.WriteJSON(nil), nil
}

func (item *StatshouseAddMetricsBatch) UnmarshalJSON(b []byte) error {
	if err := item.ReadJSON(true, &basictl.JsonLexer{Data: b}); err != nil {
		return ErrorInvalidJSON("statshouse.addMetricsBatch", err.Error())
	}
	return nil
}

func (item *StatshouseAddMetricsBatch) WriteTL2(w []byte, ctx *basictl.TL2WriteContext) []byte {
	panic(ErrorTL2SerializersNotGenerated("statshouse.addMetricsBatch"))
}

func (item *StatshouseAddMetricsBatch) ReadTL2(r []byte, ctx *basictl.TL2ReadContext) (_ []byte, err error) {
	return r, ErrorTL2SerializersNotGenerated("statshouse.addMetricsBatch")
}

type StatshouseAddMetricsBatchBytes struct {
	FieldsMask uint32
	Host       []byte // Conditional: item.FieldsMask.0
	Metrics    []StatshouseMetricBytes
}

func (StatshouseAddMetricsBatchBytes) TLName() string { return "statshouse.addMetricsBatch" }
func (StatshouseAddMetricsBatchBytes) TLTag() uint32  { return 0x56580239 }

func (item *StatshouseAddMetricsBatchBytes) SetHost(v []byte) {
	item.Host = v
	item.FieldsMask |= 1 << 0
}
func (item *StatshouseAddMetricsBatchBytes) ClearHost() {
	item.Host = item.Host[:0]
	item.FieldsMask &^= 1 << 0
}
func (item *StatshouseAddMetricsBatchBytes) IsSetHost() bool { return item.FieldsMask&(1<<0) != 0 }

func (item *StatshouseAddMetricsBatchBytes) Reset() {
	item.FieldsMask = 0
	item.Host = item.Host[:0]
	item.Metrics = item.Metrics[:0]
}

func (item *StatshouseAddMetricsBatchBytes) FillRandom(rg *basictl.RandGenerator) {
	item.FieldsMask = basictl.RandomFieldMask(rg, 0b1)
	if item.FieldsMask&(1<<0) != 0 {
		item.Host = basictl.RandomStringBytes(rg)
	} else {
		item.Host = item.Host[:0]
	}
	BuiltinVectorStatshouseMetricBytesFillRandom(rg, &item.Metrics)
}

func (item *StatshouseAddMetricsBatchBytes) ReadTL1(w []byte) (_ []byte, err error) {
	if w, err = basictl.NatRead(w, &item.FieldsMask); err != nil {
		return w, err
	}
	if item.FieldsMask&(1<<0) != 0 {
		if w, err = basictl.StringReadBytes(w, &item.Host); err != nil {
			return w, err
		}
	} else {
		item.Host = item.Host[:0]
	}
	return BuiltinVectorStatshouseMetricBytesReadTL1(w, &item.Metrics)
}

func (item *StatshouseAddMetricsBatchBytes) WriteTL1General(w []byte) (_ []byte, err error) {
	return item.WriteTL1(w), nil
}

func (item *StatshouseAddMetricsBatchBytes) WriteTL1(w []byte) []byte {
	w = basictl.NatWrite(w, item.FieldsMask)
	if item.FieldsMask&(1<<0) != 0 {
		w = basictl.StringWriteBytes(w, item.Host)
	}
	w = BuiltinVectorStatshouseMetricBytesWriteTL1(w, item.Metrics)
	return w
}

func (item *StatshouseAddMetricsBatchBytes) ReadTL1Boxed(w []byte) (_ []byte, err error) {
	if w, err = basictl.NatReadExactTag(w, 0x56580239); err != nil {
		return w, err
	}
	return item.ReadTL1(w)
}

func (item *StatshouseAddMetricsBatchBytes) WriteTL1BoxedGeneral(w []byte) (_ []byte, err error) {
	return item.WriteTL1Boxed(w), nil
}

func (item *StatshouseAddMetricsBatchBytes) WriteTL1Boxed(w []byte) []byte {
	w = basictl.NatWrite(w, 0x56580239)
	return item.WriteTL1(w)
}

func (item *StatshouseAddMetricsBatchBytes) ReadResultTL1(w []byte, ret *True) (_ []byte, err error) {
	return ret.ReadTL1Boxed(w)
}

func (item *StatshouseAddMetricsBatchBytes) WriteResultTL1(w []byte, ret True) (_ []byte, err error) {
	w = ret.WriteTL1Boxed(w)
	return w, nil
}

func (item *StatshouseAddMetricsBatchBytes) ReadResultJSON(legacyTypeNames bool, in *basictl.JsonLexer, ret *True) error {
	tctx := &basictl.JSONReadContext{LegacyTypeNames: legacyTypeNames}
	if err := ret.ReadJSONGeneral(tctx, in); err != nil {
		return err
	}
	return nil
}

func (item *StatshouseAddMetricsBatchBytes) WriteResultJSON(w []byte, ret True) (_ []byte, err error) {
	tctx := basictl.JSONWriteContext{}
	return item.writeResultJSON(&tctx, w, ret)
}

func (item *StatshouseAddMetricsBatchBytes) writeResultJSON(tctx *basictl.JSONWriteContext, w []byte, ret True) (_ []byte, err error) {
	w = ret.WriteJSONOpt(tctx, w)
	return w, nil
}

func (item *StatshouseAddMetricsBatchBytes) FillRandomResultTL1(rg *basictl.RandGenerator, w []byte) ([]byte, error) {
	var ret True
	ret.FillRandom(rg)
	return item.WriteResultTL1(w, ret)
}

func (item *StatshouseAddMetricsBatchBytes) ReadResultTL1WriteResultJSON(tctx *basictl.JSONWriteContext, r []byte, w []byte) (_ []byte, _ []byte, err error) {
	var ret True
	if r, err = item.ReadResultTL1(r, &ret); err != nil {
		return r, w, err
	}
	w, err = item.writeResultJSON(tctx, w, ret)
	return r, w, err
}

func (item *StatshouseAddMetricsBatchBytes) ReadResultJSONWriteResultTL1(r []byte, w []byte) (_ []byte, _ []byte, err error) {
	var ret True
	if err = item.ReadResultJSON(true, &basictl.JsonLexer{Data: r}, &ret); err != nil {
		return r, w, err
	}
	w, err = item.WriteResultTL1(w, ret)
	return r, w, err
}

func (item *StatshouseAddMetricsBatchBytes) ReadResultTL1WriteResultTL2(tctx *basictl.TL2WriteContext, r []byte, w []byte) (_ []byte, _ []byte, err error) {
	return r, w, ErrorTL2SerializersNotGenerated("statshouse.addMetricsBatch")
}

func (item *StatshouseAddMetricsBatchBytes) ReadResultTL2WriteResultTL1(tctx *basictl.TL2ReadContext, r []byte, w []byte) (_ []byte, _ []byte, err error) {
	return r, w, ErrorTL2SerializersNotGenerated("statshouse.addMetricsBatch")
}

func (item *StatshouseAddMetricsBatchBytes) ReadResultTL2WriteResultJSON(tctx *basictl.TL2ReadContext, jctx *basictl.JSONWriteContext, r []byte, w []byte) (_ []byte, _ []byte, err error) {
	return r, w, ErrorTL2SerializersNotGenerated("statshouse.addMetricsBatch")
}

func (item *StatshouseAddMetricsBatchBytes) ReadResultJSONWriteResultTL2(tctx *basictl.TL2WriteContext, r []byte, w []byte) (_ []byte, _ []byte, err error) {
	return r, w, ErrorTL2SerializersNotGenerated("statshouse.addMetricsBatch")
}

func (item StatshouseAddMetricsBatchBytes) String() string {
	return string(item.WriteJSON(nil))
}

func (item *StatshouseAddMetricsBatchBytes) ReadJSON(legacyTypeNames bool, in *basictl.JsonLexer) error {
	tctx := basictl.JSONReadContext{LegacyTypeNames: legacyTypeNames}
	return item.ReadJSONGeneral(&tctx, in)
}

func (item *StatshouseAddMetricsBatchBytes) ReadJSONGeneral(tctx *basictl.JSONReadContext, in *basictl.JsonLexer) error {
	var propFieldsMaskPresented bool
	var propHostPresented bool
	var propMetricsPresented bool
	if in != nil {
		in.Delim('{')
		if !in.Ok() {
			return in.Error()
		}
		for !in.IsDelim('}') {
			key := in.UnsafeFieldName(true)
			in.WantColon()
			switch key {
			case "fields_mask":
				if propFieldsMaskPresented {
					return ErrorInvalidJSONWithDuplicatingKeys("statshouse.addMetricsBatch", "fields_mask")
				}
				propFieldsMaskPresented = true
				if err := Json2ReadUint32(in, &item.FieldsMask); err != nil {
					return err
				}
			case "host":
				if propHostPresented {
					return ErrorInvalidJSONWithDuplicatingKeys("statshouse.addMetricsBatch", "host")
				}
				propHostPresented = true
				if err := Json2ReadStringBytes(in, &item.Host); err != nil {
					return err
				}
			case "metrics":
				if propMetricsPresented {
					return ErrorInvalidJSONWithDuplicatingKeys("statshouse.addMetricsBatch", "metrics")
				}
				propMetricsPresented = true
				if err := BuiltinVectorStatshouseMetricBytesReadJSONGeneral(tctx, in, &item.Metrics); err != nil {
					return err
				}
			default:
				return ErrorInvalidJSONExcessElement("statshouse.addMetricsBatch", key)
			}
			in.WantComma()
		}
		in.Delim('}')
		if !in.Ok() {
			return in.Error()
		}
	}
	if !propFieldsMaskPresented {
		item.FieldsMask = 0
	}
	if !propHostPresented {
		item.Host = item.Host[:0]
	}
	if !propMetricsPresented {
		item.Metrics = item.Metrics[:0]
	}
	if propHostPresented {
		item.FieldsMask |= 1 << 0
	}
	return nil
}

// This method is general version of WriteJSON, use it instead!
func (item *StatshouseAddMetricsBatchBytes) WriteJSONGeneral(tctx *basictl.JSONWriteContext, w []byte) (_ []byte, err error) {
	return item.WriteJSONOpt(tctx, w), nil
}

func (item *StatshouseAddMetricsBatchBytes) WriteJSON(w []byte) []byte {
	tctx := basictl.JSONWriteContext{}
	return item.WriteJSONOpt(&tctx, w)
}
func (item *StatshouseAddMetricsBatchBytes) WriteJSONOpt(tctx *basictl.JSONWriteContext, w []byte) []byte {
	w = append(w, '{')
	backupIndexFieldsMask := len(w)
	w = basictl.JSONAddCommaIfNeeded(w)
	w = append(w, `"fields_mask":`...)
	w = basictl.JSONWriteUint32(w, item.FieldsMask)
	if !(item.FieldsMask != 0) {
		w = w[:backupIndexFieldsMask]
	}
	if item.FieldsMask&(1<<0) != 0 {
		w = basictl.JSONAddCommaIfNeeded(w)
		w = append(w, `"host":`...)
		w = basictl.JSONWriteStringBytes(w, item.Host)
	}
	backupIndexMetrics := len(w)
	w = basictl.JSONAddCommaIfNeeded(w)
	w = append(w, `"metrics":`...)
	w = BuiltinVectorStatshouseMetricBytesWriteJSONOpt(tctx, w, item.Metrics)
	if !(len(item.Metrics) != 0) {
		w = w[:backupIndexMetrics]
	}
	return append(w, '}')
}

func (item *StatshouseAddMetricsBatchBytes) MarshalJSON() ([]byte, error) {
	return item.WriteJSON(nil), nil
}

func (item *StatshouseAddMetricsBatchBytes) UnmarshalJSON(b []byte) error {
	if err := item.ReadJSON(true, &basictl.JsonLexer{Data: b}); err != nil {
		return ErrorInvalidJSON("statshouse.addMetricsBatch", err.Error())
	}
	return nil
}

func (item *StatshouseAddMetricsBatchBytes) WriteTL2(w []byte, ctx *basictl.TL2WriteContext) []byte {
	panic(ErrorTL2SerializersNotGenerated("statshouse.addMetricsBatch"))
}

func (item *StatshouseAddMetricsBatchBytes) ReadTL2(r []byte, ctx *basictl.TL2ReadContext) (_ []byte, err error) {
	return r, ErrorTL2SerializersNotGenerated("statshouse.addMetricsBatch")
}
