// Copyright 2025 V Kontakte LLC
//
// This Source Code Form is subject to the terms of the Mozilla Public
// License, v. 2.0. If a copy of the MPL was not distributed with this
// file, You can obtain one at https://mozilla.org/MPL/2.0/.

// Code generated by vktl/cmd/tlgen2; DO NOT EDIT.
package internal

import (
	"github.com/VKCOM/statshouse/internal/vkgo/basictl"
)

var _ = basictl.NatWrite

type StatshouseApiGetMappingResponse struct {
	IntValue    int32  // Conditional: nat_fields_mask.3
	StringValue string // Conditional: nat_fields_mask.4
	tl2mask0    byte
}

func (StatshouseApiGetMappingResponse) TLName() string { return "statshouseApi.getMappingResponse" }
func (StatshouseApiGetMappingResponse) TLTag() uint32  { return 0xfd15ff23 }

func (item *StatshouseApiGetMappingResponse) SetIntValue(v int32, nat_fields_mask *uint32) {
	item.IntValue = v
	if nat_fields_mask != nil {
		*nat_fields_mask |= 1 << 3
	}
	item.tl2mask0 |= 1
}
func (item *StatshouseApiGetMappingResponse) ClearIntValue(nat_fields_mask *uint32) {
	item.IntValue = 0
	if nat_fields_mask != nil {
		*nat_fields_mask &^= 1 << 3
	}
	item.tl2mask0 &^= 1
}
func (item *StatshouseApiGetMappingResponse) IsSetIntValue() bool { return item.tl2mask0&1 != 0 }

func (item *StatshouseApiGetMappingResponse) SetStringValue(v string, nat_fields_mask *uint32) {
	item.StringValue = v
	if nat_fields_mask != nil {
		*nat_fields_mask |= 1 << 4
	}
	item.tl2mask0 |= 2
}
func (item *StatshouseApiGetMappingResponse) ClearStringValue(nat_fields_mask *uint32) {
	item.StringValue = ""
	if nat_fields_mask != nil {
		*nat_fields_mask &^= 1 << 4
	}
	item.tl2mask0 &^= 2
}
func (item *StatshouseApiGetMappingResponse) IsSetStringValue() bool { return item.tl2mask0&2 != 0 }

func (item *StatshouseApiGetMappingResponse) Reset() {
	item.IntValue = 0
	item.StringValue = ""
	item.tl2mask0 = 0
}

func (item *StatshouseApiGetMappingResponse) FillRandom(rg *basictl.RandGenerator, nat_fields_mask uint32) {
	item.tl2mask0 = 0
	if nat_fields_mask&(1<<3) != 0 {
		item.tl2mask0 |= 1
		item.IntValue = basictl.RandomInt(rg)
	} else {
		item.IntValue = 0
	}
	if nat_fields_mask&(1<<4) != 0 {
		item.tl2mask0 |= 2
		item.StringValue = basictl.RandomString(rg)
	} else {
		item.StringValue = ""
	}
}

func (item *StatshouseApiGetMappingResponse) Read(w []byte, nat_fields_mask uint32) (_ []byte, err error) {
	item.tl2mask0 = 0
	if nat_fields_mask&(1<<3) != 0 {
		item.tl2mask0 |= 1
		if w, err = basictl.IntRead(w, &item.IntValue); err != nil {
			return w, err
		}
	} else {
		item.IntValue = 0
	}
	if nat_fields_mask&(1<<4) != 0 {
		item.tl2mask0 |= 2
		if w, err = basictl.StringRead(w, &item.StringValue); err != nil {
			return w, err
		}
	} else {
		item.StringValue = ""
	}
	return w, nil
}

func (item *StatshouseApiGetMappingResponse) WriteGeneral(w []byte, nat_fields_mask uint32) (_ []byte, err error) {
	return item.Write(w, nat_fields_mask), nil
}

func (item *StatshouseApiGetMappingResponse) Write(w []byte, nat_fields_mask uint32) []byte {
	if nat_fields_mask&(1<<3) != 0 {
		w = basictl.IntWrite(w, item.IntValue)
	}
	if nat_fields_mask&(1<<4) != 0 {
		w = basictl.StringWrite(w, item.StringValue)
	}
	return w
}

func (item *StatshouseApiGetMappingResponse) ReadBoxed(w []byte, nat_fields_mask uint32) (_ []byte, err error) {
	if w, err = basictl.NatReadExactTag(w, 0xfd15ff23); err != nil {
		return w, err
	}
	return item.Read(w, nat_fields_mask)
}

func (item *StatshouseApiGetMappingResponse) WriteBoxedGeneral(w []byte, nat_fields_mask uint32) (_ []byte, err error) {
	return item.WriteBoxed(w, nat_fields_mask), nil
}

func (item *StatshouseApiGetMappingResponse) WriteBoxed(w []byte, nat_fields_mask uint32) []byte {
	w = basictl.NatWrite(w, 0xfd15ff23)
	return item.Write(w, nat_fields_mask)
}

func (item *StatshouseApiGetMappingResponse) ReadJSONGeneral(tctx *basictl.JSONReadContext, in *basictl.JsonLexer, nat_fields_mask uint32) error {
	var propIntValuePresented bool
	var propStringValuePresented bool

	if in != nil {
		in.Delim('{')
		if !in.Ok() {
			return in.Error()
		}
		for !in.IsDelim('}') {
			key := in.UnsafeFieldName(true)
			in.WantColon()
			switch key {
			case "intValue":
				if propIntValuePresented {
					return ErrorInvalidJSONWithDuplicatingKeys("statshouseApi.getMappingResponse", "intValue")
				}
				if nat_fields_mask&(1<<3) == 0 {
					return ErrorInvalidJSON("statshouseApi.getMappingResponse", "field 'intValue' is defined, while corresponding implicit fieldmask bit is 0")
				}
				if err := Json2ReadInt32(in, &item.IntValue); err != nil {
					return err
				}
				propIntValuePresented = true
			case "stringValue":
				if propStringValuePresented {
					return ErrorInvalidJSONWithDuplicatingKeys("statshouseApi.getMappingResponse", "stringValue")
				}
				if nat_fields_mask&(1<<4) == 0 {
					return ErrorInvalidJSON("statshouseApi.getMappingResponse", "field 'stringValue' is defined, while corresponding implicit fieldmask bit is 0")
				}
				if err := Json2ReadString(in, &item.StringValue); err != nil {
					return err
				}
				propStringValuePresented = true
			default:
				return ErrorInvalidJSONExcessElement("statshouseApi.getMappingResponse", key)
			}
			in.WantComma()
		}
		in.Delim('}')
		if !in.Ok() {
			return in.Error()
		}
	}
	if !propIntValuePresented {
		item.IntValue = 0
	}
	if !propStringValuePresented {
		item.StringValue = ""
	}
	if nat_fields_mask&(1<<3) != 0 {
		item.tl2mask0 |= 1
	}
	if nat_fields_mask&(1<<4) != 0 {
		item.tl2mask0 |= 2
	}
	return nil
}

// This method is general version of WriteJSON, use it instead!
func (item *StatshouseApiGetMappingResponse) WriteJSONGeneral(tctx *basictl.JSONWriteContext, w []byte, nat_fields_mask uint32) (_ []byte, err error) {
	return item.WriteJSONOpt(tctx, w, nat_fields_mask), nil
}

func (item *StatshouseApiGetMappingResponse) WriteJSON(w []byte, nat_fields_mask uint32) []byte {
	tctx := basictl.JSONWriteContext{}
	return item.WriteJSONOpt(&tctx, w, nat_fields_mask)
}
func (item *StatshouseApiGetMappingResponse) WriteJSONOpt(tctx *basictl.JSONWriteContext, w []byte, nat_fields_mask uint32) []byte {
	w = append(w, '{')
	if nat_fields_mask&(1<<3) != 0 {
		w = basictl.JSONAddCommaIfNeeded(w)
		w = append(w, `"intValue":`...)
		w = basictl.JSONWriteInt32(w, item.IntValue)
	}
	if nat_fields_mask&(1<<4) != 0 {
		w = basictl.JSONAddCommaIfNeeded(w)
		w = append(w, `"stringValue":`...)
		w = basictl.JSONWriteString(w, item.StringValue)
	}
	return append(w, '}')
}

func (item *StatshouseApiGetMappingResponse) CalculateLayout(sizes []int, optimizeEmpty bool) ([]int, int) {
	sizes = append(sizes, 4246077219)
	sizePosition := len(sizes)
	sizes = append(sizes, 0)

	currentSize := 1
	lastUsedByte := 0
	var sz int

	if item.tl2mask0&1 != 0 {
		currentSize += 4
		lastUsedByte = currentSize
	}
	if item.tl2mask0&2 != 0 {
		currentSize += basictl.TL2CalculateSize(len(item.StringValue)) + len(item.StringValue)
		lastUsedByte = currentSize
	}

	if lastUsedByte < currentSize {
		currentSize = lastUsedByte
	}
	sizes[sizePosition] = currentSize
	if currentSize == 0 {
		sizes = sizes[:sizePosition+1]
	}
	if !optimizeEmpty || currentSize != 0 {
		currentSize += basictl.TL2CalculateSize(currentSize)
	}
	Unused(sz)
	return sizes, currentSize
}

func (item *StatshouseApiGetMappingResponse) InternalWriteTL2(w []byte, sizes []int, optimizeEmpty bool) ([]byte, []int, int) {
	if sizes[0] != 4246077219 {
		panic("tl2: tag mismatch between calculate and write")
	}
	currentSize := sizes[1]
	sizes = sizes[2:]
	if optimizeEmpty && currentSize == 0 {
		return w, sizes, 0
	}
	w = basictl.TL2WriteSize(w, currentSize)
	oldLen := len(w)
	if len(w)-oldLen == currentSize {
		return w, sizes, 1
	}
	var sz int
	var currentBlock byte
	currentBlockPosition := len(w)
	w = append(w, 0)
	if item.tl2mask0&1 != 0 {
		w = basictl.IntWrite(w, item.IntValue)
		currentBlock |= 2
	}
	if item.tl2mask0&2 != 0 {
		w = basictl.StringWriteTL2(w, item.StringValue)
		currentBlock |= 4
	}
	if currentBlockPosition < len(w) {
		w[currentBlockPosition] = currentBlock
	}
	if len(w)-oldLen != currentSize {
		panic("tl2: mismatch between calculate and write")
	}
	Unused(sz)
	return w, sizes, 1
}

func (item *StatshouseApiGetMappingResponse) WriteTL2(w []byte, ctx *basictl.TL2WriteContext) []byte {
	var sizes, sizes2 []int
	if ctx != nil {
		sizes = ctx.SizeBuffer[:0]
	}
	sizes, _ = item.CalculateLayout(sizes, false)
	w, sizes2, _ = item.InternalWriteTL2(w, sizes, false)
	if len(sizes2) != 0 {
		panic("tl2: internal write did not consume all size data")
	}
	if ctx != nil {
		ctx.SizeBuffer = sizes
	}
	return w
}

func (item *StatshouseApiGetMappingResponse) InternalReadTL2(r []byte) (_ []byte, err error) {
	currentSize := 0
	if r, currentSize, err = basictl.TL2ParseSize(r); err != nil {
		return r, err
	}
	if len(r) < currentSize {
		return r, basictl.TL2Error("not enough data: expected %d, got %d", currentSize, len(r))
	}

	if currentSize == 0 {
		item.Reset()
		return r, nil
	}
	currentR := r[:currentSize]
	r = r[currentSize:]

	var block byte
	if currentR, err = basictl.ByteReadTL2(currentR, &block); err != nil {
		return currentR, err
	}
	// read No of constructor
	if block&1 != 0 {
		var index int
		if currentR, err = basictl.TL2ReadSize(currentR, &index); err != nil {
			return currentR, err
		}
		if index != 0 {
			return r, ErrorInvalidUnionIndex("statshouseApi.getMappingResponse", index)
		}
	}
	item.tl2mask0 = 0
	if block&2 != 0 {
		item.tl2mask0 |= 1
		if currentR, err = basictl.IntRead(currentR, &item.IntValue); err != nil {
			return currentR, err
		}
	} else {
		item.IntValue = 0
	}
	if block&4 != 0 {
		item.tl2mask0 |= 2
		if currentR, err = basictl.StringReadTL2(currentR, &item.StringValue); err != nil {
			return currentR, err
		}
	} else {
		item.StringValue = ""
	}
	Unused(currentR)
	return r, nil
}

func (item *StatshouseApiGetMappingResponse) ReadTL2(r []byte, ctx *basictl.TL2ReadContext) (_ []byte, err error) {
	return item.InternalReadTL2(r)
}
