// Copyright 2025 V Kontakte LLC
//
// This Source Code Form is subject to the terms of the Mozilla Public
// License, v. 2.0. If a copy of the MPL was not distributed with this
// file, You can obtain one at https://mozilla.org/MPL/2.0/.

// Code generated by tl2gen; DO NOT EDIT.
package tl

import (
	"github.com/VKCOM/statshouse/internal/data_model/gen2/internal"
)

type (
	BoolStat                   = internal.BoolStat
	DictFieldStringString      = internal.DictFieldStringString
	DictFieldStringStringBytes = internal.DictFieldStringStringBytes
	DictionaryString           = internal.DictionaryString
	DictionaryStringBytes      = internal.DictionaryStringBytes
	Int                        = internal.Int
	Stat                       = internal.Stat
	String                     = internal.String
	StringBytes                = internal.StringBytes
	True                       = internal.True
	TupleDouble2               = internal.TupleDouble2
	VectorDouble               = internal.VectorDouble
	VectorInt                  = internal.VectorInt
	VectorLong                 = internal.VectorLong
	VectorString               = internal.VectorString
	VectorStringBytes          = internal.VectorStringBytes
	VectorTupleDouble2         = internal.VectorTupleDouble2
	VectorVectorDouble         = internal.VectorVectorDouble
)

func BoolReadTL1Boxed(w []byte, v *bool) ([]byte, error) {
	return internal.BoolReadTL1Boxed(w, v)
}
func BoolWriteTL1Boxed(w []byte, v bool) []byte {
	return internal.BoolWriteTL1Boxed(w, v)
}
