on: workflow_dispatch
jobs:
  debian:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        debian_release: [jessie, stretch, buster, bullseye]
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 1
      - run: ./build/makedeb.sh ${{ matrix.debian_release }}
      - uses: actions/upload-artifact@v3
        with:
          name: ${{ matrix.debian_release }}
          path: ./target/*.deb
