on:
  workflow_call:
    inputs:
      ref:
        type: string
        required: true
      ref_timestamp:
        type: string
        required: true
      timestamp:
        type: string
        required: true
      version:
        type: string
        required: true
      name:
        type: string
        required: true
      release:
        type: string
        required: true
      frontend-artifact:
        type: string
        required: true
    outputs:
      artifact:
        value: statshouse-${{inputs.version}}-rpm
jobs:
  binaries:
    uses: ./.github/workflows/build_binaries.yml
    with:
      container_json: '{"image":"${{inputs.name}}:${{inputs.release}}"}'
      ref: ${{inputs.ref}}
      ref_timestamp: ${{inputs.ref_timestamp}}
      timestamp: ${{inputs.timestamp}}
      version: ${{inputs.version}}
      name: ${{inputs.name}}
      release: ${{inputs.release}}
      run: 'dnf group install -y "Development Tools"'
      setup-go: true
  package:
    needs: [binaries]
    runs-on: ubuntu-latest
    container:
      image: ${{inputs.name}}:${{inputs.release}}
    steps:
      - run: dnf group install -y "Development Tools"
      - uses: actions/checkout@v4
        with:
          repository: VKCOM/statshouse
          ref: ${{inputs.ref}}
          fetch-depth: 0
      - uses: actions/download-artifact@v4
        with:
          name: ${{needs.binaries.outputs.artifact}}
          path: target
      - uses: actions/download-artifact@v4
        with:
          name: ${{inputs.frontend-artifact}}
      - run: echo "BUILD_VERSION=`echo ${{inputs.version}} | sed -e 's:-:.:g'`" >> $GITHUB_ENV
      - run: |
          chmod +x target/*
          mkdir -p BUILD BUILDROOT SOURCES SPECS SRPMS RPMS
          cp build/statshouse.spec SPECS/
          rpmbuild --define "_topdir `pwd`" --define "BUILD_VERSION $BUILD_VERSION" --define "OS_NAME_RELEASE ${{inputs.name}}${{inputs.release}}" -bb SPECS/statshouse.spec
      - uses: actions/upload-artifact@v4
        with:
          name: statshouse-${{inputs.version}}-rpm
          path: RPMS/statshouse-${{env.BUILD_VERSION}}*.rpm
