on:
  pull_request:
    branches:
      - master
    paths:
      - 'statshouse-ui/**'
jobs:
  ci-ui:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 1
      - uses: actions/setup-node@v3
        with:
          node-version: 18.x
          cache: 'npm'
          cache-dependency-path: statshouse-ui/package-lock.json
      - run: npm ci
        working-directory: statshouse-ui
      - run: npm run build
        working-directory: statshouse-ui
      - run: CI=true npm run test
        working-directory: statshouse-ui
